### ISSUE TITLE
Android X compatibility

### ISSUE THREAD

**Issue by synw** [eopeter/flutter_mapbox_navigation#1]
When I enable Android X in a project the plugin does not compile. Traceback:

> 
> e: /home/me/bin/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.2/android/src/main/kotlin/com/dormmom/flutter_mapbox_navigation/FlutterMapboxNavigationPlugin.kt: (9, 24): Unresolved reference: annotation
> e: /home/me/bin/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.2/android/src/main/kotlin/com/dormmom/flutter_mapbox_navigation/FlutterMapboxNavigationPlugin.kt: (10, 31): Unresolved reference: ActivityCompat
> e: /home/me/bin/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.2/android/src/main/kotlin/com/dormmom/flutter_mapbox_navigation/FlutterMapboxNavigationPlugin.kt: (11, 24): Unresolved reference: v7
> e: /home/me/bin/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.2/android/src/main/kotlin/com/dormmom/flutter_mapbox_navigation/FlutterMapboxNavigationPlugin.kt: (199, 39): Unresolved reference: NonNull
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':flutter_mapbox_navigation:compileDebugKotlin'.
> > Compilation error. See log for more details
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 56s
> Gradle task assembleDebug failed with exit code 1

Flutter doctor:

> [✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale fr_FR.UTF-8)
>     • Flutter version 1.7.8+hotfix.4 at /home/me/bin/flutter/flutter
>     • Framework revision 20e59316b8 (il y a 2 semaines), 2019-07-18 20:04:33 -0700
>     • Engine revision fee001c93f
>     • Dart version 2.4.0
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /home/me/Android/Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • ANDROID_HOME = /home/me/Android/Sdk
>     • Java binary at: /home/me/bin/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
>     • All Android licenses accepted.
> 
> [✓] Android Studio (version 3.4)
>     • Android Studio at /home/me/bin/android-studio
>     • Flutter plugin version 35.3.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
> 
> [✓] Connected device (1 available)
>     • SM N910F • bd704008 • android-arm • Android 6.0.1 (API 23)

**Comment by eopeter** [comment]
Added AndroidX Support
