### ISSUE TITLE
Error in using example

### ISSUE THREAD

**Issue by xenups** [eopeter/flutter_mapbox_navigation#10]
Hello when i want to run the example file its shows :
Unhandled Exception: MissingPluginException(No implementation found for method startNavigation on channel flutter_mapbox_navigation)

so how i cant avoid this

**Comment by eopeter** [comment]
In what environment are you running it. What device?

**Comment by xenups** [comment]
i tried to clone ur project and run ur example , so when i wanted to run its shows an error that 

> > Could not resolve all artifacts for configuration ':classpath'.
>    > Could not find builder.jar (com.android.tools.build:builder:3.5.2).

so i changed to gradle in dependencies to 3.5.0
after that its shows 

> > Could not resolve all artifacts for configuration ':flutter_mapbox_navigation:debugCompileClasspath'.
>    > Could not find legacy-support-core-utils.jar (androidx.legacy:legacy-support-core-utils:1.0.0)

so i tried to create a new package and just get ur package in dependencies and its shows : 

> Could not determine the dependencies of task ':flutter_mapbox_navigation:compileDebugAidl'.
> > Could not resolve all task dependencies for configuration ':flutter_mapbox_navigation:debugCompileClasspath'.
>    > Could not find com.mapbox.navigator:mapbox-navigation-native:6.2.1.
>      Required by:
>          project :flutter_mapbox_navigation > com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.3

**Comment by eopeter** [comment]
Can you upgrade to the latest version of the Plugin and try again? The version is 0.0.8
