### ISSUE TITLE
allowsUTurnAtWayPoints = false is ignored when simulating in Android

### ISSUE THREAD

**Issue by ulrichbjerre** [eopeter/flutter_mapbox_navigation#101]
allowsUTurnAtWayPoints = false is ignored when simulating in Android
Release 0.0.18
Android 8.0.0

**Comment by eopeter** [comment]
This should be resolved in v0.0.19

**Comment by ulrichbjerre** [comment]
When do you expect to release v0.0.19?

**Comment by eopeter** [comment]
It is now deployed.
