### ISSUE TITLE
Unable to set a custom night style for navigation map

### ISSUE THREAD

**Issue by flother** [eopeter/flutter_mapbox_navigation#104]
In the current version, 0.0.18, you can only customise the map's day style. The night style will always be Mapbox's own style. This is a problem for me because I want to use my own style all the time. Currently my own map style will only be used between sunrise and sunset — which, in the winter at 64°N, is not that long ;)

In the iOS code, [line 205 in `SwiftFlutterMapboxNavigationPlugin.swift`](https://github.com/eopeter/flutter_mapbox_navigation/blob/c2f219aea9554c11d2f363878d45cfd714a620e0/ios/Classes/SwiftFlutterMapboxNavigationPlugin.swift#L205) only includes the custom style in the day style:

```swift
NavigationOptions(styles: [CustomDayStyle(url: strongSelf._mapStyleURL), CustomNightStyle()])
```

I didn't manage to track down the equivalent Kotlin code, so I'm not sure if there's the same problem there.

I'd like to see the map style be included in the night style (`CustomNightStyle(url: strongSelf._mapStyleURL)`), although there's also a case for being able to set two styles, night and day.

**Comment by bossbeagle1509** [comment]
Wait, a minute ! You're able to set a custom map style ?! [It's been breaking when a bunch of other people tried.](https://github.com/eopeter/flutter_mapbox_navigation/issues/87#issue-718441472) Do you have a public style that I can try using ?

**Comment by flother** [comment]
I've only tried this out on the iOS simulator, while the comments on #87 are focused on Android. Having said that, yes, it works for me (see screenshot). The style I'm using covers Iceland only and isn't for commercial use, but feel free to use it to test this: https://tiles.ja.is/vector/styles/v3/ja-streets/ja-streets.json.

![mapbox-navigation](https://user-images.githubusercontent.com/48392/101167056-3a0a8f00-3631-11eb-9025-210cf21d234d.png)

**Comment by bossbeagle1509** [comment]
😔 Still crashes...thanks though.
  
However, out of curiosity, was this particular style made in mapbox style editor and then hosted on an nginx server ? Because the url doesn't start with mapbox, as compared to mine `mapbox://styles/pransypansy/ckenyljlg06xs19ppveli6bgf`

**Comment by flother** [comment]
Correct. I actually wrote this style by hand in a code editor instead of using Mapbox's tools. You can see it in action at [ja.is/kort](https://en.ja.is/kort/). It's still in the [Mapbox Style Spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/) format and we still use [Mapbox GL JS](https://docs.mapbox.com/mapbox-gl-js/api/) to render it in the browser, but we host it — and our custom vector tile data — on our own servers.

The `mapbox://` schema is a mock schema that's really just shorthand for a real `https://` URL. Mapbox perhaps use it for some optimistions somewhere in their libraries.

**Comment by bossbeagle1509** [comment]
Much thanks ! Hopefully when I get to college they'll teach me all that !

**Comment by eopeter** [comment]
You can now set Day and Night MapStyleUrl in v 0.0.19

**Comment by flother** [comment]
Thanks for looking into this @eopeter. Looking at [commit c24b1356](https://github.com/eopeter/flutter_mapbox_navigation/commit/c24b1356dc3ed3d71de9767c008b1b08cfed81b7) though, it seems you can only set the night style for Android, not for iOS. Am I right to say that in the Swift code it's [still fixed to Mapbox's night style](https://github.com/eopeter/flutter_mapbox_navigation/blob/3c03c0910a52269aedd685033859a9dcf7d62245/ios/Classes/SwiftFlutterMapboxNavigationPlugin.swift#L1101)?

**Comment by eopeter** [comment]
This is corrected sand published to pubspec.
