### ISSUE TITLE
need tiimplement a specific route based on polylines or list of coor

### ISSUE THREAD

**Issue by Aymen-Brahim** [eopeter/flutter_mapbox_navigation#108]
Hello,
Is it possible to add a custom route to the navigation.
I have a list of coordinates and i use that list to draw a route with polyline. Can i take that polyline or list of coordinates to use in route of Mapbox Navigation ?

Best regards 
Aymen

**Comment by eopeter** [comment]
Stale issue message

**Comment by neildunlop** [comment]
Not sure if these is still a challenge for you guys, but yes, you can add a list of waypoints to define a route.

**Comment by eopeter** [comment]
this is same as #160
