### ISSUE TITLE
Add a marker 

### ISSUE THREAD

**Issue by briceAlex** [eopeter/flutter_mapbox_navigation#109]
Hi, 
I just want to know how to put a marker on the map ( if it's possible ) 

Thank you !

**Comment by Satendra124** [comment]
yes with ```MapBoxMapcontroller.addSymbol()```

**Comment by bossbeagle1509** [comment]
From where did you get/see that method ?

**Comment by Satendra124** [comment]
Through the example given in the repo.

**Comment by bossbeagle1509** [comment]
From [here](https://github.com/eopeter/flutter_mapbox_navigation/blob/master/example/lib/main.dart) ? Because I couldn't find it there

**Comment by Satendra124** [comment]
oh no! sorry i got a lil confused it was in mapbox_gl pakage but the problem is that having both pakages creates error .

**Comment by Luismi74** [comment]
There is a package that doesnt conflict with both and also has markers @Satendra124 @bossbeagle1509 : 
[flutter_plugin_mapbox](https://github.com/jzpenga/flutter_plugin_mapbox)

**Comment by kabilsharma** [comment]
does this with custom vector tilea (self hosted) and  our own routing engine Api (server side) . If yes

How? 

Thanks in advance.

**Comment by Luismi74** [comment]
@kabilsharma @briceAlex @Satendra124 Found a better implementation and its using mapbox https://medium.com/zipper-studios/flutter-map-custom-and-dynamic-popup-over-the-marker-732d26ef9bc7

**Comment by eopeter** [comment]
Stale issue message
