### ISSUE TITLE
Build plugin error

### ISSUE THREAD

**Issue by EHGOLDFISH** [eopeter/flutter_mapbox_navigation#11]
Not really sure why this is happening. I pulled the example code from git and ran it with my own key and works fine. But tried to run this in my own app and it seems to crash in the build. Any clues on how to fix this? I have the permissions setup and strings.xml added. This build was on android 

error: constructor FlutterMapboxNavigationPlugin in class FlutterMapboxNavigationPlugin cannot be applied to given types;
    flutterEngine.getPlugins().add(new com.dormmom.flutter_mapbox_navigation.FlutterMapboxNavigationPlugin());
                                   ^
  required: Context,Activity
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error

FAILURE: Build failed with an exception.

**Comment by eopeter** [comment]
Is your project AndroidX?

**Comment by ranjan435** [comment]
Same problem here. What does it mean by androidx?

**Comment by EHGOLDFISH** [comment]
The androidx is supported with this project.

**Comment by ranjan435** [comment]
Compiler message:                                                       
../../../flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.1/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {           
                       ^                                                
../../../flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);             
                       ^                                                
../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.7.2/lib/src/layer/tile_provider/mbtiles_image_provider.dart:90:24: Error: The method 'MBTileImage.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(MBTileImage key) {                          
                       ^                                                
../../../flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);             
                       ^                                                
../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_image-2.0.0/lib/network.dart:73:24: Error: The method 'NetworkImageWithRetry.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(NetworkImageWithRetry key) {                
                       ^                                                
../../../flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);             
                       ^                                                
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/home/debian/Documents/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildDebug'.              
> Process 'command '/home/debian/Documents/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 47s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        49.1s
Gradle task assembleDebug failed with exit code 1

**Comment by ranjan435** [comment]
I need to have the best route suggestion with my own logic. Can this code does it so? If yes, how?

**Comment by EHGOLDFISH** [comment]
one work around would be to just build on top of the example but it's not an ideal fix

**Comment by EHGOLDFISH** [comment]
@ranjan435 this is a great way to get between from a starting location to an end location

**Comment by yuniargb** [comment]
hi can someone show me tutorial for this package?

**Comment by eopeter** [comment]
Plugin was updated to be compliant with Flutter 1.12. Please upgrade the plugin to version 0.0.8 and try again.

**Comment by EHGOLDFISH** [comment]
Thanks man your awesome!!

**Comment by yuniargb** [comment]
> 
> 
> Plugin was updated to be compliant with Flutter 1.12. Please upgrade the plugin to version 0.0.8 and try again.

Big Thanks!!, but how to get estimation data?
