### ISSUE TITLE
Units are not set right on iOS

### ISSUE THREAD

**Issue by ulrichbjerre** [eopeter/flutter_mapbox_navigation#115]
I'm using metric units (see settings below), but the units does not match on the iOS platform (see video):
The units on iOS are imperial.
The units on Android are metric.

Simulation test with v0.0.19
Simulated on:
- Physical iPhone 8 running iOS 14.4.2
- iPhone simulator running iOS 13.5
- Flutter simulator running Android 9
- Physical Huawei P20 lite running Android 8.0

Video/screen recordings of simulation behaviours are available here: https://drive.google.com/drive/folders/1XDpenC7-0i_ZRdj6G8a_TMvYX_-qPm9M?usp=sharing

Using the example application.
Using the "Start Multi Stop" function (button)
Using these waypoints (with start = stop)

		Lat		Lng
Origin 		56.1395		8.9591 (START)
WayPoint1	56.1370		8.9596
WayPoint2	56.1396		8.9631
WayPoint3	56.1405		8.9636
WayPoint5 	56.1395		8.9591 (STOP)

MapboxOptions: 

    _options = MapBoxOptions(
        //initialLatitude: 36.1175275,
        //initialLongitude: -115.1839524,
        zoom: 15.0,
        tilt: 0.0,
        bearing: 0.0,
        enableRefresh: false,
        alternatives: false,
        voiceInstructionsEnabled: true,
        bannerInstructionsEnabled: true,
        allowsUTurnAtWayPoints: false,
        mode: MapBoxNavigationMode.driving,
        units: VoiceUnits.imperial,
        simulateRoute: false,
        animateBuildRoute: true,
        longPressDestinationEnabled: true,
        language: "en");

Simulation options (in the Start Multi Stop method):

options: MapBoxOptions(
                                    mode: MapBoxNavigationMode.driving,
                                    simulateRoute: true,
                                    language: "en",
                                    allowsUTurnAtWayPoints: false,
                                    units: VoiceUnits.imperial));

**Comment by ulrichbjerre** [comment]
Any updates on this one?

**Comment by hainv-ohio** [comment]
Hi, I'm having the same issue on iOS. Has this issue been fixed?
