### ISSUE TITLE
Different behaviour on Android

### ISSUE THREAD

**Issue by ulrichbjerre** [eopeter/flutter_mapbox_navigation#117]
Using the exact same waypoints and settings the route (simulation) behaves different on Android devices and simulators compared to iOS (which behaves as expected).
The main problem seems to be, that the "allowsUTurnAtWayPoints: false" option fails on Android.
Please see linked videos for demonstration.

Simulation test with v0.0.19
Simulated on:
- Physical iPhone 8 running iOS 14.4.2
- iPhone simulator running iOS 13.5
- Flutter simulator running Android 9
- Physical Huawei P20 lite running Android 8.0

Video/screen recordings of simulation behaviours are available here: https://drive.google.com/drive/folders/1XDpenC7-0i_ZRdj6G8a_TMvYX_-qPm9M?usp=sharing

Using the example application.
Using the "Start Multi Stop" function (button)
Using these waypoints (with start = stop)

		Lat		Lng
Origin 		56.1395		8.9591 (START)
WayPoint1	56.1370		8.9596
WayPoint2	56.1396		8.9631
WayPoint3	56.1405		8.9636
WayPoint5 	56.1395		8.9591 (STOP)

MapboxOptions: 

    _options = MapBoxOptions(
        //initialLatitude: 36.1175275,
        //initialLongitude: -115.1839524,
        zoom: 15.0,
        tilt: 0.0,
        bearing: 0.0,
        enableRefresh: false,
        alternatives: false,
        voiceInstructionsEnabled: true,
        bannerInstructionsEnabled: true,
        allowsUTurnAtWayPoints: false,
        mode: MapBoxNavigationMode.driving,
        units: VoiceUnits.imperial,
        simulateRoute: false,
        animateBuildRoute: true,
        longPressDestinationEnabled: true,
        language: "en");

Simulation options (in the Start Multi Stop method):

options: MapBoxOptions(
                                    mode: MapBoxNavigationMode.driving,
                                    simulateRoute: true,
                                    language: "en",
                                    allowsUTurnAtWayPoints: false,
                                    units: VoiceUnits.imperial));

**Comment by raghebzaki** [comment]
Can you send source code please

**Comment by ulrichbjerre** [comment]
I'm using the sample application (source code) provided within the example folder.

**Comment by raghebzaki** [comment]
When i use example it work fine
But when i copy example in new project and add acces token ( like example ) i found that error
![117779534-0e727d00-b23f-11eb-92bd-381ffa05138f](https://user-images.githubusercontent.com/73133205/118401940-f1d3ac00-b667-11eb-8327-4b13a1705c4c.png)

**Comment by ulrichbjerre** [comment]
I don't know much about that?
I had issues with my own app. So, I decided to test the example application and modify the settings to verify identical behaviour and to verify if I'm doing something wrong in my own app. 

It does however seem to be a bug in the demo application too - so not just my own work 🤷🏼‍♂️

**Comment by ulrichbjerre** [comment]
Any updates on this one....?

**Comment by FarahBedoui96** [comment]
@raghebzaki you should open android module to build your app  that way the navigation sdk will be installed

**Comment by ulrichbjerre** [comment]
Are you suggesting to build the app inside Android Studio?
I usually build from Visual Studio Code - which is my preferred routine...

**Comment by FarahBedoui96** [comment]
> Are you suggesting to build the app inside Android Studio?
> I usually build from Visual Studio Code - which is my preferred routine...

yes you should build it from Android studio I got the same error and it was resolved like that! because it should be downloaded first! and you should also remove any other similar sdk to avoid ambiguity issues. (use the sdk-update branch)
but anyway the package seems to be broken I was able to run the example and got other runtime issues!

**Comment by ulrichbjerre** [comment]
Hmmmm.....well - that kinda sucks. 

I've tried to get rid of the tedious build in Xcode and Android Studio. Often something goes wrong - and I'm just plain sick and tired of maintaining both platforms as there are often conflicts 🙄

**Comment by eopeter** [comment]
Stale issue message
