### ISSUE TITLE
Incompatible versions of the Mapbox-SDK-iOS

### ISSUE THREAD

**Issue by yadames** [eopeter/flutter_mapbox_navigation#119]
I am developing an application where I need to use the mapbox maps and also use the flutter_mapbox_navigation package to launch the navigation function.

I am using these versions:
mapbox_gl: ^ 0.12.0
flutter_mapbox_navigation: ^ 0.0.19

Using both, I get an error on iOS when installing Cocoapods dependencies as they use different versions of Mapbox-SDK-iOS.

mapbox_gl => Mapbox-SDK-iOS 6.3.0
flutter_mapbox_navigation => Mapbox-SDK-iOS 5.9.0

Has someone presented the same situation and managed to solve it?

**Comment by paraslamsong** [comment]
@yadames Have you solved this?

**Comment by eopeter** [comment]
Please update version of both to latest
