### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by yuniargb** [eopeter/flutter_mapbox_navigation#12]
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > D:\project\study\flutter\aplikasi_hello\build\flutter_mapbox_navigation\intermediates\compile_library_classes\debug\classes.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 19s
Gradle task assembleDebug failed with exit code 1

hello, whats the problem this? from me or plugin? thanks for answer

**Comment by eopeter** [comment]
try version 0.0.8
