### ISSUE TITLE
Android embedded navigation problem

### ISSUE THREAD

**Issue by yadames** [eopeter/flutter_mapbox_navigation#120]
I am developing an application where I need to use flutter_mapbox_navigation to launch the embedded navigation function in the MapBoxNavigationView.

I am using these versions:
mapbox_gl: ^ 0.12.0
flutter_mapbox_navigation: ^ 0.0.19

It happens that nothing happens on Android. The route is created and the route is simulated, but the guide view or controls do not appear, or visual or sound signals associated with the directions.

On iOS it does work

Has someone presented the same situation and managed to solve it?

**Comment by SoundSonic1** [comment]
When I looked into the Code I saw that the NavigationView is not implemented in Android. The variable doesn't even get initialized.

**Comment by eopeter** [comment]
This issue is resolved
