### ISSUE TITLE
Execution failed for task ':app:checkDebugAarMetadata'.

### ISSUE THREAD

**Issue by raghebzaki** [eopeter/flutter_mapbox_navigation#123]
![image](https://user-images.githubusercontent.com/73133205/117779534-0e727d00-b23f-11eb-92bd-381ffa05138f.png)
i have this error anyone can help me

**Comment by raphaelscartezini** [comment]
Make sure you follow the installation steps in the Mapbox site: https://docs.mapbox.com/android/beta/navigation/guides/install/
It is important to generate the secret tokens and all that, as per the instructions 
I had a similar error and fixed that way. I hope that helps.

**Comment by raghebzaki** [comment]
> Did you manage to solve this? I'm running into same issues
