### ISSUE TITLE
Method "finishNavigation" was called on null

### ISSUE THREAD

**Issue by Luismi74** [eopeter/flutter_mapbox_navigation#124]
[![forthebadge](https://forthebadge.com/images/badges/not-a-bug-a-feature.svg)](https://forthebadge.com) 

Having some issues trying to automatically close the full screen turn by turn navigation on arrival. Tried different methods and didn't work. 

### Flutter Info
Flutter (Channel master, 2.3.0-1.0.pre.79, on Microsoft Windows [Version 10.0.18363.1556], locale en-US)
    • Flutter version 2.3.0-1.0.pre.79 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d1f73a1065 (3 weeks ago), 2021-04-24 00:44:02 -0400
    • Engine revision eba9efd1c3
    • Dart version 2.14.0 (build 2.14.0-37.0.dev)

![image](https://user-images.githubusercontent.com/15695141/118177524-cef38e80-b400-11eb-898a-6b44013b06e6.png)

**Comment by lexprimost** [comment]
is working now ?

**Comment by Luismi74** [comment]
@lexprimost yes it is working now!

**Comment by lexprimost** [comment]
have you been able to draw route before starting navigation ? im getting this error everytime i tried to buil a route or when i long press on the map. the app crash after tthat

`E/flutter (20345): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Missing required properties: baseUrl user requestUuid, null, java.lang.IllegalStateException: Missing required properties: baseUrl user requestUuid`

**Comment by Luismi74** [comment]
![image](https://user-images.githubusercontent.com/15695141/123551957-09f81a00-d742-11eb-8bd8-59b19e77e86e.png)

**Comment by Luismi74** [comment]
Yes, here is the route built @lexprimost. Can you share your code?

![image](https://user-images.githubusercontent.com/15695141/123551971-18463600-d742-11eb-8d42-431a0e85c307.png)

**Comment by lexprimost** [comment]
i used the demo exmaple and also my own implementation here is the gist of the page [](https://gist.github.com/lexprimost/e82a6581f55587975b3844066407c2f6 )

**Comment by lexprimost** [comment]
it should draw a route in the beginning but it only shows a long and lat that i give in the beginning . even when i create a button to create a route it logs
`E/flutter (20345): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Missing required properties: baseUrl user requestUuid, null, java.lang.IllegalStateException: Missing required properties: baseUrl user requestUuid`
![Screenshot_20210627-173704 1](https://user-images.githubusercontent.com/5768206/123554270-aa643380-d76e-11eb-84b1-81cfdb6b4fde.jpg)
