### ISSUE TITLE
I can't  seem to be able to install this

### ISSUE THREAD

**Issue by DaveWillie** [eopeter/flutter_mapbox_navigation#127]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':flutter_mapbox_navigation:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':flutter_mapbox_navigation:debugCompileClasspath'.
   > Could not resolve com.mapbox.navigation:ui:1.2.0.
     Required by:
         project :flutter_mapbox_navigation
      > Could not resolve com.mapbox.navigation:ui:1.2.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui/1.2.0/ui-1.2.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui/1.2.0/ui-1.2.0.pom'. Received status code 403 from server: Forbidden
      > Could not resolve com.mapbox.navigation:ui:1.2.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui/1.2.0/ui-1.2.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui/1.2.0/ui-1.2.0.pom'. Received status code 403 from server: Forbidden

**Comment by DaveWillie** [comment]
I've added the keys and everything, anyway you can do a demo of how to install correctly please?

**Comment by Cybernetics354** [comment]
I think your token is not enabled for `Downloads:Read` scope, you need to enabled it on your token, for more details you can read the documentation from mapbox.

https://docs.mapbox.com/android/maps/guides/install/

**Comment by eopeter** [comment]
Did enabling the scope work for you?

**Comment by Luismi74** [comment]
I'm having the same issue but a bit different: 
`> Could not resolve com.google.android.gms:play-services-location:16.+.
     Required by:
         project :app > project :location
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Could not GET 'https://mapbox.bintray.com/mapbox/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 403 from server: Forbidden
      > Failed to list versions for com.google.android.gms:play-services-location.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/google/android/gms/play-services-location/maven-metadata.xml'. Received status code 403 from server: Forbidden
`
and found out in this issue that Jfrog bintray is shutting down... I've also tried to access the repository and it is not available any more on JFrog.

![image](https://user-images.githubusercontent.com/15695141/124503312-4b687500-dd93-11eb-9f62-b55fb937df17.png)

it shows indexed on google but when you click on it, doesn't show the correct page.

**Comment by DaveWillie** [comment]
@eopeter  @Cybernetics354  Thank you guys, yes that was the problem on my side....so created the secret key with the Downloads:Read scope, which I missed.

**Comment by icofans** [comment]
1、creat a secret token
![image](https://user-images.githubusercontent.com/13825591/126930772-fec320b3-900e-428e-baf5-48347568779b.png)
2、add property in grade.properties
```
MAPBOX_DOWNLOADS_TOKEN=TOKEN_YOUR_CREATE
```
2、add this to build.grade
```
repositories {
        google()
        jcenter()
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be `mapbox` (not your username). 
                username = 'mapbox'
                // Use the secret token you stored in gradle.properties as the password
                password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
            }
        }
    }
```
