### ISSUE TITLE
The startNavigation method dont work

### ISSUE THREAD

**Issue by YUND4** [eopeter/flutter_mapbox_navigation#13]
When using this plugin and following all the installation steps, it is impossible to register it correctly. It seems a compatibility issue.
my pubspect.ymal and my implementation

`name: apppalermodev
description: A new Flutter project.
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  expandable: ^4.0.1
  fluttertoast: ^3.1.3
  english_words: ^3.1.3
  cupertino_icons: ^0.1.2
  flutter_socket_io: ^0.6.0
  rxdart: ^0.22.2
  device_info: ^0.4.0+3
  shared_preferences: ^0.5.2
  http: ^0.12.0+2
  sqflite: ^1.1.5
  path_provider: ^1.3.0
  connectivity: ^0.4.2
  encrypt: ^3.3.1
  blue_thermal_printer: ^1.0.9
  pull_to_refresh: ^1.4.5
  image_picker: ^0.6.2+3
  badges: ^1.1.0
  progress_hud: ^1.1.0
  carousel_slider: ^1.3.0
  rflutter_alert: ^1.0.3
  crypto: ^2.1.3
  location: ^2.3.5
  flutter_bcrypt: ^1.0.5
  dbcrypt: ^1.0.0
  flutter_speed_dial: ^1.2.5
  flutter_map: ^0.8.2
  latlong: ^0.6.1
  bitmap: ^0.0.6
  flutter_mapbox_navigation: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mapbox_gl:
    path: ./dependencies/flutter-mapbox-gl

module:
  androidX: true

flutter:

  uses-material-design: true
  assets:
   - media/
   - assets/
   - assets/symbols/
   - assets/img/
   - assets/img/modulos/
   - lib/src/utils/languages/
  fonts:
    - family: CenturyGothic
      fonts:
        - asset: assets/fonts/CenturyGothicRegular.ttf
`

`
class MapReconexionState extends State<MapReconexion> {
  bool _arrived = false;
  double _distanceRemaining, _durationRemaining;
  bool _tilesLoaded = false;
...
  @override
  void initState() {
    super.initState();
    _copyTilesIntoPlace();
    initPlatformState();
  }

  Future<void> initPlatformState() async {
    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    _directions = mapbox.MapboxNavigation(onRouteProgress: (arrived) async {
      _distanceRemaining = await _directions.distanceRemaining;
      _durationRemaining = await _directions.durationRemaining;

      setState(() {
        _arrived = arrived;
      });
      if (arrived) await _directions.finishNavigation();
    });
  }
...
Future<void> turnOnNavigation ({String origenName, String targetName, LatLng origin, LatLng target}) async {

    if (origin == null) {
      await getLoaction();
    }

    final _origin = mapbox.Location(name: "City Hall", latitude: 42.886448, longitude: -78.878372);
    final _destination = mapbox.Location(name: "Downtown Buffalo", latitude: 42.8866177, longitude: -78.8814924);

    await _directions.startNavigation(
      origin: _origin,
      destination: _destination,
      mode: mapbox.NavigationMode.drivingWithTraffic,
      simulateRoute: true);
  }
..
                                     PopupMenu(
                                      title: "Empezar viaje",
                                      onTap: () {
                                        turnOnNavigation();
                                      }, icon: Icons.directions_car)
..
}
`
My error

`Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method startNavigation on channel flutter_mapbox_navigation))`

**Comment by eopeter** [comment]
What version of Flutter do you have running?

**Comment by codenamics** [comment]
same here when i try to start navigation pop up asking about allow location pops and app is closed and exited

flutter latest version

**Comment by eopeter** [comment]
What is your exact flutter version. Please provide flutter doctor -v output

**Comment by YUND4** [comment]
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

I think I found the problem, it seems that in the latest versions of flutter plugins are registered differently.
it is well evidenced by comparing the file of a new project
in: android / app / src / main / java / io / flutter / plugins / GeneratedPluginRegistrant.java

package io.flutter.plugins;

import io.flutter.plugin.common.PluginRegistry;
import com.dormmom.flutter_mapbox_navigation.FlutterMapboxNavigationPlugin;
/**
 * Generated file. Do not edit.
 */
public final class GeneratedPluginRegistrant {
  public static void registerWith(PluginRegistry registry) {
    if (alreadyRegisteredWith(registry)) {
      return;
    }
 FlutterMapboxNavigationPlugin.registerWith(registry.registrarFor("com.dormmom.flutter_mapbox_navigation.FlutterMapboxNavigationPlugin"));
  }
    

  private static boolean alreadyRegisteredWith(PluginRegistry registry) {
    final String key = GeneratedPluginRegistrant.class.getCanonicalName();
    if (registry.hasPlugin(key)) {
      return true;
    }
    registry.registrarFor(key);
    return false;
  }
}

With your example in the file:
example / android / app / src / main / java / io / flutter / plugins / GeneratedPluginRegistrant.java
package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    flutterEngine.getPlugins().add(new com.dormmom.flutter_mapbox_navigation.FlutterMapboxNavigationPlugin());
  }
}

**Comment by eopeter** [comment]
Did you get this to run with the new PluginRegistrant?

**Comment by MufakirMairaj** [comment]
Can someone give me a complete code or guide me. I have tried but not getting it worked.

**Comment by rinzinDev** [comment]
I have the same issue the startNavigation throws MissingPluginException. If plugin registered was an issue as mentioned above then I don't understand how all other plugins are working as expected. Please help the error is critical in the development. I updated to latest flutter_mapbox_navigation: ^0.0.9 and still the same issue.

**Comment by Malik056** [comment]
I am having the same issue
<img width="727" alt="Screenshot 2020-02-20 at 2 31 24 PM" src="https://user-images.githubusercontent.com/38656998/74920828-9f68f880-53ee-11ea-990a-e5d847046219.png">





**pubspec.yaml**

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.16.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  google_map_location_picker: ^3.2.1
  flutter_mapbox_navigation: ^0.0.10
  # place_picker: ^0.9.9
  flutter_google_places: ^0.2.3
  # flutter_polyline_points: ^0.1.0
  google_maps_flutter: ^0.5.21+15
  google_map_polyline: ^0.2.0+1
  maps_launcher: ^1.2.0
  geolocator: ^5.2.1
  geocoder: ^0.2.1
  sqflite:
  path:
  location: ^2.3.5
  page_view_indicators: ^1.3.0
  auto_size_text: ^2.1.0
  # carousel_slider: ^1.3.1
  # carousel_pro: ^1.0.0
  pin_code_fields: ^2.3.0+1
  flutter_rating: ^0.0.2
  password: ^1.0.0
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3
  firebase_messaging: ^5.0.2
  flappy_search_bar: ^1.4.1
  bot_toast: ^2.2.0
  argon_buttons_flutter: ^1.0.2
  flutter_email_sender: ^2.2.2
  solid_bottom_sheet: ^0.1.9
  mailer: ^3.0.4
  flutter_speed_dial: ^1.2.5
  random_string: ^2.0.1
  http: ^0.12.0+4
  
  rave_flutter: ^0.0.8-alpha+1
  carousel_slider: ^1.4.1



**Flutter Doctor**

apple@macbook-pro Sennit % flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/apple/Desktop/Sdks/flutter
    • Framework revision 0b8abb4724 (9 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • RMX1821 • W8SOB6FEIBV48LHI • android-arm64 • Android 9 (API 28)

• No issues found!

**Comment by Malik056** [comment]
I have found a workaround for this

Navigate to com.dormmom.flutter_mapbox_navigation.FlutterMapboxNavigationPlugin file as shown below
<img width="426" alt="Screenshot 2020-02-20 at 4 03 29 PM" src="https://user-images.githubusercontent.com/38656998/74928124-b0b80200-53fa-11ea-84b0-84fda5ce9587.png">

**add (act:Activity) as a initializer to the FlutterMapboxNavigationPlugin class**

like this

**class FlutterMapboxNavigationPlugin(act: Activity): FlutterPlugin, ActivityAware**

add initializer in the class

```
init {
        _activity = act;
    }
```

pass registrar.activity() as argument to the FlutterMapboxNavigationPlugin Object

`val instance = FlutterMapboxNavigationPlugin(registrar.activity())`

add following line in private onAttachedToEngine function

```
val handler = FlutterMapboxNavigation(_context, _activity)
        _eventChannel!!.setStreamHandler(handler)
        _methodChannel!!.setMethodCallHandler(handler)
```
And you are done

full code for FlutterMapboxNavigationPlugin file below


```
import android.app.Activity
import android.content.Context

import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.embedding.engine.plugins.activity.ActivityAware
import io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding

import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.PluginRegistry.Registrar

class FlutterMapboxNavigationPlugin(act: Activity): FlutterPlugin, ActivityAware
{
    
    private var _methodChannel: MethodChannel? = null
    private var _eventChannel: EventChannel? = null
    private lateinit var _activity: Activity
    private lateinit var _context: Context

    companion object {
        @Suppress("unused")
        @JvmStatic
        fun registerWith(registrar: Registrar) {

            val instance = FlutterMapboxNavigationPlugin(registrar.activity())
            instance.onAttachedToEngine(registrar.activeContext(), registrar.messenger())

        }
    }

    init {
        _activity = act;
    }

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {

        onAttachedToEngine(binding.applicationContext, binding.binaryMessenger)

    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {

        _methodChannel!!.setMethodCallHandler(null)
        _methodChannel = null
        _eventChannel!!.setStreamHandler(null)
        _eventChannel = null

    }


    private fun onAttachedToEngine(binding: Context, messenger: BinaryMessenger) {

        _context = binding
        _methodChannel = MethodChannel(messenger, "flutter_mapbox_navigation")
        _eventChannel = EventChannel(messenger, "flutter_mapbox_navigation/arrival")
        val handler = FlutterMapboxNavigation(_context, _activity)
        _eventChannel!!.setStreamHandler(handler)
        _methodChannel!!.setMethodCallHandler(handler)

    }

    override fun onDetachedFromActivity() {
        _activity.finish()
    }

    override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {
        
    }

    override fun onAttachedToActivity(binding: ActivityPluginBinding) {
        _activity = binding.activity
        val handler = FlutterMapboxNavigation(_context, _activity)
        _eventChannel!!.setStreamHandler(handler)
        _methodChannel!!.setMethodCallHandler(handler)
    }

    override fun onDetachedFromActivityForConfigChanges() {
        //To change body of created functions use File | Settings | File Templates.
    }


}


```

**Comment by emanuel-cc** [comment]
> I have found a workaround for this
> 
> Navigate to com.dormmom.flutter_mapbox_navigation.FlutterMapboxNavigationPlugin file as shown below
> <img alt="Screenshot 2020-02-20 at 4 03 29 PM" width="426" src="https://user-images.githubusercontent.com/38656998/74928124-b0b80200-53fa-11ea-84b0-84fda5ce9587.png">
> 
> **add (act:Activity) as a initializer to the FlutterMapboxNavigationPlugin class**
> 
> like this
> 
> `class FlutterMapboxNavigationPlugin(act: Activity): FlutterPlugin, ActivityAware`
> 
> add initializer in the class
> 
> ```
> init {
>         _activity = act;
>     }
> ```
> 
> pass registrar.activity() as argument to the FlutterMapboxNavigationPlugin Object
> 
> `val instance = FlutterMapboxNavigationPlugin(registrar.activity())`
> 
> add following line in private onAttachedToEngine function
> 
> ```
> val handler = FlutterMapboxNavigation(_context, _activity)
>         _eventChannel!!.setStreamHandler(handler)
>         _methodChannel!!.setMethodCallHandler(handler)
> ```
> 
> And you are done
> 
> full code for FlutterMapboxNavigationPlugin file below
> 
> ```
> import android.app.Activity
> import android.content.Context
> 
> import io.flutter.embedding.engine.plugins.FlutterPlugin
> import io.flutter.embedding.engine.plugins.activity.ActivityAware
> import io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding
> 
> import io.flutter.plugin.common.BinaryMessenger
> import io.flutter.plugin.common.EventChannel
> import io.flutter.plugin.common.MethodChannel
> import io.flutter.plugin.common.PluginRegistry.Registrar
> 
> class FlutterMapboxNavigationPlugin(act: Activity): FlutterPlugin, ActivityAware
> {
>     
>     private var _methodChannel: MethodChannel? = null
>     private var _eventChannel: EventChannel? = null
>     private lateinit var _activity: Activity
>     private lateinit var _context: Context
> 
>     companion object {
>         @Suppress("unused")
>         @JvmStatic
>         fun registerWith(registrar: Registrar) {
> 
>             val instance = FlutterMapboxNavigationPlugin(registrar.activity())
>             instance.onAttachedToEngine(registrar.activeContext(), registrar.messenger())
> 
>         }
>     }
> 
>     init {
>         _activity = act;
>     }
> 
>     override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
> 
>         onAttachedToEngine(binding.applicationContext, binding.binaryMessenger)
> 
>     }
> 
>     override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
> 
>         _methodChannel!!.setMethodCallHandler(null)
>         _methodChannel = null
>         _eventChannel!!.setStreamHandler(null)
>         _eventChannel = null
> 
>     }
> 
> 
>     private fun onAttachedToEngine(binding: Context, messenger: BinaryMessenger) {
> 
>         _context = binding
>         _methodChannel = MethodChannel(messenger, "flutter_mapbox_navigation")
>         _eventChannel = EventChannel(messenger, "flutter_mapbox_navigation/arrival")
>         val handler = FlutterMapboxNavigation(_context, _activity)
>         _eventChannel!!.setStreamHandler(handler)
>         _methodChannel!!.setMethodCallHandler(handler)
> 
>     }
> 
>     override fun onDetachedFromActivity() {
>         _activity.finish()
>     }
> 
>     override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {
>         
>     }
> 
>     override fun onAttachedToActivity(binding: ActivityPluginBinding) {
>         _activity = binding.activity
>         val handler = FlutterMapboxNavigation(_context, _activity)
>         _eventChannel!!.setStreamHandler(handler)
>         _methodChannel!!.setMethodCallHandler(handler)
>     }
> 
>     override fun onDetachedFromActivityForConfigChanges() {
>         //To change body of created functions use File | Settings | File Templates.
>     }
> 
> 
> }
> ```

y te funcionó con el paquete?

**Comment by emanuel-cc** [comment]
Malik056 te funcionó el paquete?

**Comment by Malik056** [comment]
Yes it worked for me but onRouteProgress callback is not working.

**Comment by emanuel-cc** [comment]
Malik056 podrías ayudar al creador del plugin a que repare el error comentado con lo que hiciste?, Sería de gran ayuda para la comunidad

**Comment by Malik056** [comment]
Ofcource! I would love to.

**Comment by AnasSafi** [comment]
[https://github.com/eopeter/flutter_mapbox_navigation/issues/30](url)

any update to solve this problem?

**Comment by Malik056** [comment]
> I have found a workaround for this
> 
> Navigate to com.dormmom.flutter_mapbox_navigation.FlutterMapboxNavigationPlugin file as shown below
> <img alt="Screenshot 2020-02-20 at 4 03 29 PM" width="426" src="https://user-images.githubusercontent.com/38656998/74928124-b0b80200-53fa-11ea-84b0-84fda5ce9587.png">
> 
> **add (act:Activity) as a initializer to the FlutterMapboxNavigationPlugin class**
> 
> like this
> 
> `class FlutterMapboxNavigationPlugin(act: Activity): FlutterPlugin, ActivityAware`
> 
> add initializer in the class
> 
> ```
> init {
>         _activity = act;
>     }
> ```
> 
> pass registrar.activity() as argument to the FlutterMapboxNavigationPlugin Object
> 
> `val instance = FlutterMapboxNavigationPlugin(registrar.activity())`
> 
> add following line in private onAttachedToEngine function
> 
> ```
> val handler = FlutterMapboxNavigation(_context, _activity)
>         _eventChannel!!.setStreamHandler(handler)
>         _methodChannel!!.setMethodCallHandler(handler)
> ```
> 
> And you are done
> 
> full code for FlutterMapboxNavigationPlugin file below
> 
> ```
> import android.app.Activity
> import android.content.Context
> 
> import io.flutter.embedding.engine.plugins.FlutterPlugin
> import io.flutter.embedding.engine.plugins.activity.ActivityAware
> import io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding
> 
> import io.flutter.plugin.common.BinaryMessenger
> import io.flutter.plugin.common.EventChannel
> import io.flutter.plugin.common.MethodChannel
> import io.flutter.plugin.common.PluginRegistry.Registrar
> 
> class FlutterMapboxNavigationPlugin(act: Activity): FlutterPlugin, ActivityAware
> {
>     
>     private var _methodChannel: MethodChannel? = null
>     private var _eventChannel: EventChannel? = null
>     private lateinit var _activity: Activity
>     private lateinit var _context: Context
> 
>     companion object {
>         @Suppress("unused")
>         @JvmStatic
>         fun registerWith(registrar: Registrar) {
> 
>             val instance = FlutterMapboxNavigationPlugin(registrar.activity())
>             instance.onAttachedToEngine(registrar.activeContext(), registrar.messenger())
> 
>         }
>     }
> 
>     init {
>         _activity = act;
>     }
> 
>     override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
> 
>         onAttachedToEngine(binding.applicationContext, binding.binaryMessenger)
> 
>     }
> 
>     override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
> 
>         _methodChannel!!.setMethodCallHandler(null)
>         _methodChannel = null
>         _eventChannel!!.setStreamHandler(null)
>         _eventChannel = null
> 
>     }
> 
> 
>     private fun onAttachedToEngine(binding: Context, messenger: BinaryMessenger) {
> 
>         _context = binding
>         _methodChannel = MethodChannel(messenger, "flutter_mapbox_navigation")
>         _eventChannel = EventChannel(messenger, "flutter_mapbox_navigation/arrival")
>         val handler = FlutterMapboxNavigation(_context, _activity)
>         _eventChannel!!.setStreamHandler(handler)
>         _methodChannel!!.setMethodCallHandler(handler)
> 
>     }
> 
>     override fun onDetachedFromActivity() {
>         _activity.finish()
>     }
> 
>     override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {
>         
>     }
> 
>     override fun onAttachedToActivity(binding: ActivityPluginBinding) {
>         _activity = binding.activity
>         val handler = FlutterMapboxNavigation(_context, _activity)
>         _eventChannel!!.setStreamHandler(handler)
>         _methodChannel!!.setMethodCallHandler(handler)
>     }
> 
>     override fun onDetachedFromActivityForConfigChanges() {
>         //To change body of created functions use File | Settings | File Templates.
>     }
> 
> 
> }
> ```

This is the work around.

**Comment by AnasSafi** [comment]
@Malik056  thank you but its not work, keep same problem.

**Comment by MufakirMairaj** [comment]
Still Not Working for me.

**Comment by MufakirMairaj** [comment]
The solution is not working for me.

**Comment by emanuel-cc** [comment]
He descubierto algo interesante, cuando cree un nuevo proyecto en flutter,
y probé el plugin, este funciona, lo que llegué a la conclusión es que con
la nueva estructura de flutter es donde funciona el plugin

**Comment by Malik056** [comment]
@emanuel-cc might be, because the only problem was that the ActivityAware interface was not working, flutter might have fixed that. I will try your solution.

Thanks for sharing

**Comment by emanuel-cc** [comment]
A ustedes

**Comment by MufakirMairaj** [comment]
Finally, it worked for me.  Thanks to all.

**Comment by luckyhandler** [comment]
I still have this issue and have to do the workaround on `Channel beta, 1.18.0-11.1.pr`. Is this soon to be fixed?

**Comment by eopeter** [comment]
Should be resolved in the latest version
