### ISSUE TITLE
[Question] How to embed naviagtion view in app 

### ISSUE THREAD

**Issue by codenamics** [eopeter/flutter_mapbox_navigation#14]
Hello,

Can I ask if it is possible to have navigation window inside widget tree? or it should have it's own "tab" like it it now?

regards

**Comment by eopeter** [comment]
An upcoming version will enable embedding

**Comment by brad007** [comment]
has this been enabled yet?

**Comment by eopeter** [comment]
Not yet

**Comment by brad007** [comment]
Are there any timelines as to when this would be implemented?

**Comment by brad007** [comment]
Any updates?

**Comment by mshuffett** [comment]
@eopeter This is important for a current project that my company is working on. If you have any timeline or any guidance on how to implement this we can also potentially take a stab at it if you don't have the bandwidth.

**Comment by eopeter** [comment]
embedding added in version 0.0.16
