### ISSUE TITLE
Android Embedded View Navigation Not Working 

### ISSUE THREAD

**Issue by ngjunya** [eopeter/flutter_mapbox_navigation#140]
W/Mbgl    (18308): {Worker 3}[Style]: Attempt to set an invalid property value -0.048498)
W/Mbgl    (18308): {Worker 4}[Style]: Attempt to set an invalid property value -0.049027)
W/Mbgl    (18308): {Worker 3}[Style]: Attempt to set an invalid property value -0.049421)
W/Mbgl    (18308): {Worker 4}[Style]: Attempt to set an invalid property value -0.049728)
W/Mbgl    (18308): {Worker 3}[Style]: Attempt to set an invalid property value -0.049921)
W/Mbgl    (18308): {Worker 1}[Style]: Attempt to set an invalid property value -0.049997)

Embedded Navigation View works fine in iOS but in android i keep getting this issue and the app not navigating as well.

**Comment by Hegazy360** [comment]
Same issue

**Comment by MrAwesome9140** [comment]
I have the same issue as well

**Comment by siqleomei** [comment]
I also have the same issue!

**Comment by eopeter** [comment]
This issue is resolved
