### ISSUE TITLE
enableFreeDriveMode is ignored

### ISSUE THREAD

**Issue by luis901101** [eopeter/flutter_mapbox_navigation#141]
**enableFreeDriveMode** on **MapBoxOptions** has no effect at all, it seems like an incomplete feature. Am I missing something. Is this going to be a feature any time soon?

**Comment by luis901101** [comment]
In fact there are some other features that doesn't work either like **longPressDestinationEnabled, zoom, tilt, bearing**...

**Comment by LoadJulz** [comment]
Did you find out how to fix it? For me the zoom, tilt etc also don't work :(

**Comment by luis901101** [comment]
Nope. The issue I refer here is on v0.12.0, and I see there is v0.14.0 currently available.
I don't know if this has been fixed in latest version.

**Comment by eopeter** [comment]
this is coming soon

**Comment by eopeter** [comment]
Free Drive Mode Added in v0.1.4
