### ISSUE TITLE
Mapbox Event navigation_cancelled not firing

### ISSUE THREAD

**Issue by jackgregory** [eopeter/flutter_mapbox_navigation#142]
Seems like the  [`navigationViewControllerDidDismiss`](https://github.com/eopeter/flutter_mapbox_navigation/blob/master/ios/Classes/SwiftFlutterMapboxNavigationPlugin.swift#L385) method isn't working at all and not triggering the navigation_cancelled event, worked before the v1 upgrade.

**Comment by eopeter** [comment]
This issue is resolved
