### ISSUE TITLE
App crashes when run the Widget with the plugin

### ISSUE THREAD

**Issue by DevTiago** [eopeter/flutter_mapbox_navigation#143]
Hello there, 

Im trying the plugin for the first time: I've created the Token and all the configuration seems ok. 
I create a sample app like the example and i've got this error:

`I/ecome_estafeta(29572): Explicit concurrent copying GC freed 27886(1644KB) AllocSpace objects, 8(160KB) LOS objects, 86% free, 1921KB/13MB, paused 257us total 55.514ms
I/BufferQueue(29572): [unnamed-29572-0](this:0x791149a800,id:0,api:0,p:-1,c:-1) BufferQueue core=(29572:com.pedecome_estafetas)
E/libc    (29572): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(29572): [unnamed-29572-0](this:0x791149a800,id:0,api:0,p:-1,c:29572) connect(C): consumer=(29572:com.pedecome_estafetas) controlledByApp=true
W/ecome_estafetas(29572): type=1400 audit(0.0:137563): avc: denied { read } for name="u:object_r:debug_bq_dump_prop:s0" dev="tmpfs" ino=12603 scontext=u:r:untrusted_app:s0:c123,c257,c512,c768 tcontext=u:object_r:debug_bq_dump_prop:s0 tclass=file permissive=0
I/BufferQueueConsumer(29572): [SurfaceTexture-0-29572-0](this:0x791149a800,id:0,api:0,p:-1,c:29572) setDefaultBufferSize: width=720 height=628
E/GraphicExt(29572): GraphicExtModuleLoader::CreateGraphicExtInstance false
W/CrashReporter(29572): Root directory doesn't exist
I/BufferQueueProducer(29572): [SurfaceTexture-0-29572-0](this:0x791149a800,id:0,api:1,p:603,c:29572) connect(P): api=1 producer=(603:???) producerControlledByApp=false
W/Gralloc3(29572): allocator 3.x is not supported
E/ion     (29572): ioctl c0044901 failed with code -1: Invalid argument
D/BufferQueueProducer(29572): [SurfaceTexture-0-29572-0](this:0x791149a800,id:0,api:1,p:603,c:29572) cancelBuffer: slot 0
D/BufferQueueProducer(29572): [SurfaceTexture-0-29572-0](this:0x791149a800,id:0,api:1,p:603,c:29572) cancelBuffer: slot 0
D/BufferQueueProducer(29572): [SurfaceTexture-0-29572-0](this:0x791149a800,id:0,api:1,p:603,c:29572) cancelBuffer: slot 0
D/BufferQueueProducer(29572): [SurfaceTexture-0-29572-0](this:0x791149a800,id:0,api:1,p:603,c:29572) cancelBuffer: slot 0
D/BufferQueueProducer(29572): [SurfaceTexture-0-29572-0](this:0x791149a800,id:0,api:1,p:603,c:29572) cancelBuffer: slot 0
D/BufferQueueProducer(29572): [SurfaceTexture-0-29572-0](this:0x791149a800,id:0,api:1,p:603,c:29572) cancelBuffer: slot 0
D/BufferQueueProducer(29572): [SurfaceTexture-0-29572-0](this:0x791149a800,id:0,api:1,p:603,c:29572) cancelBuffer: slot 0
D/BufferQueueProducer(29572): [SurfaceTexture-0-29572-0](this:0x791149a800,id:0,api:1,p:603,c:29572) cancelBuffer: slot 0
D/BufferQueueProducer(29572): [SurfaceTexture-0-29572-0](this:0x791149a800,id:0,api:1,p:603,c:29572) cancelBuffer: slot 0
E/AndroidRuntime(29572): FATAL EXCEPTION: main
E/AndroidRuntime(29572): Process: com.pedecome_estafetas, PID: 29572
E/AndroidRuntime(29572): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/navigation/core/fasterroute/FasterRouteObserver;
E/AndroidRuntime(29572): 	at com.dormmom.flutter_mapbox_navigation.factory.MapViewFactory.create(MapViewFactory.kt:17)
E/AndroidRuntime(29572): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
E/AndroidRuntime(29572): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:454)
E/AndroidRuntime(29572): 	at android.app.Dialog.show(Dialog.java:321)
E/AndroidRuntime(29572): 	at android.app.Presentation.show(Presentation.java:257)
E/AndroidRuntime(29572): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/AndroidRuntime(29572): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/AndroidRuntime(29572): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:212)
E/AndroidRuntime(29572): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:107)
E/AndroidRuntime(29572): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/AndroidRuntime(29572): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(29572): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/AndroidRuntime(29572): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:862)
E/AndroidRuntime(29572): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(29572): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime(29572): 	at android.os.Looper.loop(Looper.java:174)
E/AndroidRuntime(29572): 	at android.app.ActivityThread.main(ActivityThread.java:7540)
E/AndroidRuntime(29572): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29572): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(29572): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
E/AndroidRuntime(29572): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.navigation.core.fasterroute.FasterRouteObserver" on path: DexPathList[[zip file "/data/app/com.pedecome_estafetas-9GzcuM8wQmQwpSDp-w4ysg==/base.apk"],nativeLibraryDirectories=[/data/app/com.pedecome_estafetas-9GzcuM8wQmQwpSDp-w4ysg==/lib/arm64, /data/app/com.pedecome_estafetas-9GzcuM8wQmQwpSDp-w4ysg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
E/AndroidRuntime(29572): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AndroidRuntime(29572): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(29572): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(29572): 	... 20 more
D/BufferQueueProducer(29572): [SurfaceTexture-0-29572-0](this:0x791149a800,id:0,api:1,p:603,c:29572) cancelBuffer: slot 0
I/Process (29572): Sending signal. PID: 29572 SIG: 9`

there's my Flutter Doctor

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 2.5.0-2.0.pre.22, on macOS 11.4 20F71 darwin-x64, locale en-PT)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (2 available)`

**Comment by AmadeoMB** [comment]
Sorry, have you find a solution for this issue?
I had the same issue and I can't really find any solution.
