### ISSUE TITLE
Android folder of firebase_core_web-1.0.2 does not exist

### ISSUE THREAD

**Issue by ShejaEddy** [eopeter/flutter_mapbox_navigation#144]
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'c:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_mapbox_navigation-0.0.26\android\build.gradle' line: 31

* What went wrong:
A problem occurred evaluating project ':flutter_mapbox_navigation'.
> Basedir c:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.0.2\android does not exist

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script 'c:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 346

* What went wrong:
A problem occurred configuring project ':flutter_mapbox_navigation'.
> Could not get unknown property 'android' for project ':flutter_mapbox_navigation' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         9.8s
Exception: Gradle task assembleDebug failed with exit code 1```

I'm having a hardtime even building once. Please help!!!

**Comment by eopeter** [comment]
Do a flutter pub get. Also make sure gradle is up to date

**Comment by ShejaEddy** [comment]
I made `flutter clean && flutter pub get && flutter run` still gives that error. Isn't it because  of these configuration in build.gradle
`allprojects {
    repositories {
        google()
        jcenter()
        url 'https://api.mapbox.com/downloads/v2/releases/maven'
        authentication {
            basic(BasicAuthentication)
        }
        credentials {
            username = 'mapbox'
            password = project.properties['MAPBOX_DOWNLOADS_TOKEN'] ?: ""
        }
    }
}`

And Also I have inspected the missing android in this `c:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.0.2\android` only ios folder is in it. Please Help It's really crucial form to get this turn to turn working.

**Comment by ShejaEddy** [comment]
I updated Gradle but still the problem persists. I'm not using mac book. I'm running on windows, the android folder is still missing in the firebase core used by flutter_mapbox_navigation. I'm really stuck now, any more help would be highly appreciated.

**Comment by ShejaEddy** [comment]
Even After running on mac, I'm still getting the same response. I don't know why It is looking for a missing android folder here in https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core_web

**Comment by ShejaEddy** [comment]
At last it finally built.

I changed this  in `/android/settings.gradle`
`include ':app'

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}`

To: 

`include ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"
`

Thanks for all the help @eopeter . Such a great work with this.
