### ISSUE TITLE
How do I set the magnification in the beginning? I have a maximum of 22

### ISSUE THREAD

**Issue by SPARSHAGGARWAL17** [eopeter/flutter_mapbox_navigation#149]
Mapbox is not magnifying at the start. Here is my code snippet.

_directions.startNavigation(
        wayPoints: [_origin, _destination],
        options: MapBoxOptions(
          mode: MapBoxNavigationMode.drivingWithTraffic,
          simulateRoute: false,
          zoom: 22,
          animateBuildRoute: true,
          language: "German",
          units: VoiceUnits.metric,
        ),
      );

**Comment by eopeter** [comment]
Stale issue message
