### ISSUE TITLE
Incompatible with Geolocator?

### ISSUE THREAD

**Issue by ATrueNovice** [eopeter/flutter_mapbox_navigation#150]
When installing the navigation package I get this message:

[ +294 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Build file '/Users/###/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.26/android/build.gradle' line: 31
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':flutter_mapbox_navigation'.
[        ] > Basedir /Users/###/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator-7.7.1/android does not exist

I've removed Geolocator and it just defaults to an error with the next package after that. 

I am using version 2.5.3 and on the stable channel. JDK 11

**Comment by eopeter** [comment]
The package does not use Geolocator. Please check your dependencies
