### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by AmadeoMB** [eopeter/flutter_mapbox_navigation#151]
Hi there. I'm trying to implement this plugins into my project but my app crash as soon as the widget builds and it gives this error.

> E/AndroidRuntime( 5454): FATAL EXCEPTION: main
E/AndroidRuntime( 5454): Process: com.webkurir4kurir.webkurir4kurir, PID: 5454
E/AndroidRuntime( 5454): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/navigation/core/fasterroute/FasterRouteObserver;
E/AndroidRuntime( 5454): 	at com.dormmom.flutter_mapbox_navigation.factory.MapViewFactory.create(MapViewFactory.kt:17)
E/AndroidRuntime( 5454): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
E/AndroidRuntime( 5454): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:427)
E/AndroidRuntime( 5454): 	at android.app.Dialog.show(Dialog.java:321)
E/AndroidRuntime( 5454): 	at android.app.Presentation.show(Presentation.java:250)
E/AndroidRuntime( 5454): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/AndroidRuntime( 5454): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/AndroidRuntime( 5454): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:212)
E/AndroidRuntime( 5454): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:107)
E/AndroidRuntime( 5454): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/AndroidRuntime( 5454): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime( 5454): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/AndroidRuntime( 5454): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:869)
E/AndroidRuntime( 5454): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 5454): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime( 5454): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 5454): 	at android.app.ActivityThread.main(ActivityThread.java:7441)
E/AndroidRuntime( 5454): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5454): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 5454): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime( 5454): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.navigation.core.fasterroute.FasterRouteObserver" on path: DexPathList[[zip file "/data/app/com.webkurir4kurir.webkurir4kurir-WK46ibk0rvjcV1RWzQSEaQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.webkurir4kurir.webkurir4kurir-WK46ibk0rvjcV1RWzQSEaQ==/lib/arm64, /data/app/com.webkurir4kurir.webkurir4kurir-WK46ibk0rvjcV1RWzQSEaQ==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
E/AndroidRuntime( 5454): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AndroidRuntime( 5454): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 5454): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 5454): 	... 20 more

I'm using flutter_mapbox_navigation: ^0.0.26
This is how I create the navigation widget
`
MapBoxNavigationView(
      options: MapBoxOptions(
        initialLatitude: -7.2461227,
        initialLongitude: 112.7380649
      ),
    );
`

Did I do something wrong? Or maybe I missed some installation steps?

**Comment by Parables** [comment]
Try this and let's see

**Comment by qcasey** [comment]
I fixed this by removing the

```groovy
implementation "com.mapbox.navigation:android:2.1.1"
```

from my dependencies in build.gradle.

**Comment by eopeter** [comment]
this implementation does not exist in the library. May be project specific
