### ISSUE TITLE
is this support offline navigation

### ISSUE THREAD

**Issue by chloechan88** [eopeter/flutter_mapbox_navigation#152]

**Comment by eopeter** [comment]
No it does not.

**Comment by badaruugan** [comment]
When does this plugin support offline navigation? We are planning to use this plugin in our project. If it will not in near future, we are going to choose another plugin. thank you :)

**Comment by eopeter** [comment]
This is an open source project and you can feel free to add the functionality if you need it now. It’s on the roadmap to support offline nav.

**Comment by vpalcar** [comment]
Hi there, how far is this feature? We use your package and would like to collaborate. Cheers

**Comment by eopeter** [comment]
Please send PR. Need more contributors

There is some commented out code but not much progress.

**Comment by Nabinda** [comment]
Any updates on offline features?

**Comment by eopeter** [comment]
Stale issue message

**Comment by eopeter** [comment]
Stale issue message

**Comment by anisalibegic** [comment]
@eopeter You closed this as as completed on Aug 2, does it mean that now it supports offline routing and that you should update readme and mark "Offline Routing" as "[DONE]"?

**Comment by matejthetree** [comment]
Is it still stale, or done?

I guess it is still stale as there is no pr connected as closing
