### ISSUE TITLE
Fields are not initialised 

### ISSUE THREAD

**Issue by plants2002** [eopeter/flutter_mapbox_navigation#159]
Copied the example but i get this error:

lib/navigation.dart:42:20: Error: Field '_directions' should be initialized because its type 'MapBoxNavigation' doesn't allow null.
Running Gradle task 'assembleDebug'...
 - 'MapBoxNavigation' is from 'package:flutter_mapbox_navigation/library.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.26/lib/library.dart').
Running Gradle task 'assembleDebug'...
  MapBoxNavigation _directions;
Running Gradle task 'assembleDebug'...
                   ^^^^^^^^^^^
Running Gradle task 'assembleDebug'...
lib/navigation.dart:43:17: Error: Field '_options' should be initialized because its type 'MapBoxOptions' doesn't allow null.
Running Gradle task 'assembleDebug'...
 - 'MapBoxOptions' is from 'package:flutter_mapbox_navigation/library.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.26/lib/library.dart').
Running Gradle task 'assembleDebug'...
  MapBoxOptions _options;
Running Gradle task 'assembleDebug'...
                ^^^^^^^^
Running Gradle task 'assembleDebug'...
lib/navigation.dart:46:10: Error: Field '_distanceRemaining' should be initialized because its type 'double' doesn't allow null.
Running Gradle task 'assembleDebug'...
  double _distanceRemaining, _durationRemaining;
Running Gradle task 'assembleDebug'...
         ^^^^^^^^^^^^^^^^^^
Running Gradle task 'assembleDebug'...
lib/navigation.dart:46:30: Error: Field '_durationRemaining' should be initialized because its type 'double' doesn't allow null.
Running Gradle task 'assembleDebug'...
  double _distanceRemaining, _durationRemaining;
Running Gradle task 'assembleDebug'...
                             ^^^^^^^^^^^^^^^^^^
Running Gradle task 'assembleDebug'...
lib/navigation.dart:47:34: Error: Field '_controller' should be initialized because its type 'MapBoxNavigationViewController' doesn't allow 
null.
Running Gradle task 'assembleDebug'...
 - 'MapBoxNavigationViewController' is from 'package:flutter_mapbox_navigation/library.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.26/lib/library.dart').

**Comment by razaen801** [comment]
Late initialize or simply initializing to 0 got my app running I was having this same issue

**Comment by renzo-massaro** [comment]
> Late initialize or simply initializing to 0 got my app running I was having this same issue

Im strugling with this.. Where i have to change that? Late initialize not working for what i try with initialize.

**Comment by eopeter** [comment]
Stale issue message
