### ISSUE TITLE
Follow route of predefined route with lat long coordinates

### ISSUE THREAD

**Issue by basvdijk** [eopeter/flutter_mapbox_navigation#160]
I there a way to use the navigation on a predefined route with GPS points? I've tried to use waypoints but it limited to a max of 25. A GPX file could contain over 1000 points which create a trail. I am wondering what would be the best approach to navigate and follow such a route.

```
       var wayPoints = List<WayPoint>();
                            wayPoints.add(_origin);
                            wayPoints.add(_stop1);
                            wayPoints.add(_stop2);
                            wayPoints.add(_stop3);
                            wayPoints.add(_stop4);
                            wayPoints.add(_origin);
                            _controller.buildRoute(wayPoints: wayPoints);
```

Above works, but with a max of 25

**Comment by santiracca** [comment]
Same problem here

**Comment by marcotrumpet** [comment]
Hi, any update on this? I saw that Mapbox can accept a Route object. You call mapbox api to create the object and pass it [here](https://github.com/eopeter/flutter_mapbox_navigation/blob/master/android/src/main/kotlin/com/eopeter/flutter_mapbox_navigation/activity/NavigationActivity.kt#L168). Wondering if there is a way to pass it from Dart. @eopeter

**Comment by marcotrumpet** [comment]
@eopeter I just created a PR to handle this https://github.com/eopeter/flutter_mapbox_navigation/pull/213

**Comment by eopeter** [comment]
When you reach the max and the last WayPoint, can you just add more WayPoints? @marcotrumpet can you reopen the PR?

**Comment by marcotrumpet** [comment]
BTW I removed the PR because, although it's technically possible there are some catches:

1. not totally sure that generate and store directions is permitted by mapbox (it means for them not to charge for api usage) but to be honest I didn't check
2. I had issues on Android that was unable to decode large routes json in mapbox SDK

**Comment by eopeter** [comment]
Stale issue message
