### ISSUE TITLE
`Received status code 401 from server: Unauthorized` means access token was not delivered successfully

### ISSUE THREAD

**Issue by carbatadev** [eopeter/flutter_mapbox_navigation#165]
`Received status code 401 from server: Unauthorized` means access token was not delivered successfully
To download the MapBox SDK, your computer needs to pass access token to their server.

Make sure to create `.netrc` file in your home directory of your computer, not project.
And then add piece of code which is on readme file.
I am using MacOS and my home directory is something like users/NAME_YOU_GAVE
on Windows, it could be different

_Originally posted by @scortumee in https://github.com/eopeter/flutter_mapbox_navigation/issues/126#issuecomment-1035511806_

I keep getting this error and am on windows. I cannot figure out how to create the file needed for the solution. Any resources?

**Comment by eopeter** [comment]
Read the instruction in the ReadMe. You can also add it to you Gradle file.
