### ISSUE TITLE
How to use custom map on my account?

### ISSUE THREAD

**Issue by Riezmann** [eopeter/flutter_mapbox_navigation#167]
Hello everyone, I am new to Flutter development, and currently, I have been trying to use this package to build my first navigation map. However, I am wondering whether or not I can use my own map style created from MapBox in this package? If possible then could you please tell me how I can do that? Thank you

**Comment by sawcce** [comment]
```dart
MapBoxOptions(
        zoom: 15.0,
        tilt: 0.0,
        bearing: 0.0,
        enableRefresh: false,
        alternatives: true,
        voiceInstructionsEnabled: true,
        bannerInstructionsEnabled: true,
        allowsUTurnAtWayPoints: true,
        mode: MapBoxNavigationMode.drivingWithTraffic,
        units: VoiceUnits.imperial,
        simulateRoute: true,
        animateBuildRoute: true,
        longPressDestinationEnabled: true,
        mapStyleUrlDay: "mapbox://",
        mapStyleUrlNight: "mapbox://",
        language: "en");
```
In the mapbox options you can specify styles with "mapStyleUrlDay" and "mapStyleUrlNight"

**Comment by eopeter** [comment]
Stale issue message
