### ISSUE TITLE
App crashes when clicking on estimated time in footer

### ISSUE THREAD

**Issue by omkarkhalipe** [eopeter/flutter_mapbox_navigation#17]
I am able to navigate to the destination but if I click on the footer, it crashes the app

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <FlutterViewController: 0x7f898f09cc00>.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109ece8db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000109471ac5 objc_exception_throw + 48
	2   UIKitCore                           0x0000000112ac16f5 -[UIViewController _presentViewController:withAnimationController:completion:] + 5087
	3   UIKitCore                           0x0000000112ac3dd7 __63-[UIViewController _presentViewController:animated:completion:]_block_invoke + 98
	4   UIKitCore                           0x0000000112ac42ef -[UIViewController _performCoordinatedPresentOrDismiss:animated:] + 511
	5   UIKitCore                           0x0000000112ac3d3e -[UIViewController _presentViewController:animated:completion:] + 172
	6   UIKitCore                           0x0000000112ac3f9c -[UIViewController presentViewController:animated:completion:] + 150
	7   flutter_mapbox_navigation           0x0000000109274692 $s25flutter_mapbox_navigation34SwiftFlutterMapboxNavigationPluginC05startG06origin11destination14simulationModeyAA8LocationC_AISbtFySay0F10Directions8WaypointCGSg_SayAJ5RouteCGSgSo7NSErrorCSgtcfU_ + 1858
	8   flutter_mapbox_navigation           0x0000000109275ccd $s25flutter_mapbox_navigation34SwiftFlutterMapboxNavigationPluginC05startG06origin11destination14simulationModeyAA8LocationC_AISbtFySay0F10Directions8WaypointCGSg_SayAJ5RouteCGSgSo7NSErrorCSgtcfU_TA + 13
	9   MapboxDirections                    0x00000001075f8f50 $s16MapboxDirections0B0C9calculate_17completionHandlerSo20NSURLSessionDataTaskCAA12RouteOptionsC_ySayAA8WaypointCGSg_SayAA0I0CGSgSo7NSErrorCSgtctFySDySSypGcfU_ + 1072
	10  MapboxDirections                    0x00000001075f901d $s16MapboxDirections0B0C9calculate_17completionHandlerSo20NSURLSessionDataTaskCAA12RouteOptionsC_ySayAA8WaypointCGSg_SayAA0I0CGSgSo7NSErrorCSgtctFySDySSypGcfU_TA + 29
	11  MapboxDirections                    0x00000001075fe461 $s16MapboxDirections0B0C8dataTask33_9AB848AFC329A49F8F01862214F64FC2LL14forCalculating17completionHandler05errorO0So016NSURLSessionDataD0CAA0B7OptionsC_ySDySSypGcySo7NSErrorCctFy10Foundation0R0VSg_So13NSURLResponseCSgs5Error_pSgtcfU_yycfU0_ + 145
	12  MapboxDirections                    0x0000000107601bb5 $s16MapboxDirections0B0C8dataTask33_9AB848AFC329A49F8F01862214F64FC2LL14forCalculating17completionHandler05errorO0So016NSURLSessionDataD0CAA0B7OptionsC_ySDySSypGcySo7NSErrorCctFy10Foundation0R0VSg_So13NSURLResponseCSgs5Error_pSgtcfU_yycfU0_TA + 21
	13  MapboxDirections                    0x00000001075fe2fd $sIeg_IeyB_TR + 45
	14  libdispatch.dylib                   0x000000010aef8d7f _dispatch_call_block_and_release + 12
	15  libdispatch.dylib                   0x000000010aef9db5 _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x000000010af07080 _dispatch_main_queue_callback_4CF + 1540
	17  CoreFoundation                      0x0000000109e35a79 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	18  CoreFoundation                      0x0000000109e30126 __CFRunLoopRun + 2310
	19  CoreFoundation                      0x0000000109e2f4d2 CFRunLoopRunSpecific + 626
	20  GraphicsServices                    0x000000010eb0a2fe GSEventRunModal + 65
	21  UIKitCore                           0x00000001130b0fc2 UIApplicationMain + 140
	22  Runner                              0x0000000101162308 main + 72
	23  libdyld.dylib                       0x000000010af6e541 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
![Simulator Screen Shot - iPhone Xʀ - 2020-01-29 at 15 25 57](https://user-images.githubusercontent.com/15224429/73346899-ab104600-42ac-11ea-9a0d-b2e9425362df.png)

**Comment by eopeter** [comment]
Will look into this and get back to you

**Comment by omkarkhalipe** [comment]
> Will look into this and get back to you
> […](#)
> On Jan 29, 2020, at 5:04 AM, Omkar Khalipe ***@***.***> wrote: ﻿ I am able to navigate to the destination but if I click on the footer, it crashes the app Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <FlutterViewController: 0x7f898f09cc00>.' *** First throw call stack: ( 0 CoreFoundation 0x0000000109ece8db __exceptionPreprocess + 331 1 libobjc.A.dylib 0x0000000109471ac5 objc_exception_throw + 48 2 UIKitCore 0x0000000112ac16f5 -[UIViewController _presentViewController:withAnimationController:completion:] + 5087 3 UIKitCore 0x0000000112ac3dd7 __63-[UIViewController _presentViewController:animated:completion:]block_invoke + 98 4 UIKitCore 0x0000000112ac42ef -[UIViewController performCoordinatedPresentOrDismiss:animated:] + 511 5 UIKitCore 0x0000000112ac3d3e -[UIViewController presentViewController:animated:completion:] + 172 6 UIKitCore 0x0000000112ac3f9c -[UIViewController presentViewController:animated:completion:] + 150 7 flutter_mapbox_navigation 0x0000000109274692 $s25flutter_mapbox_navigation34SwiftFlutterMapboxNavigationPluginC05startG06origin11destination14simulationModeyAA8LocationC_AISbtFySay0F10Directions8WaypointCGSg_SayAJ5RouteCGSgSo7NSErrorCSgtcfU + 1858 8 flutter_mapbox_navigation 0x0000000109275ccd $s25flutter_mapbox_navigation34SwiftFlutterMapboxNavigationPluginC05startG06origin11destination14simulationModeyAA8LocationC_AISbtFySay0F10Directions8WaypointCGSg_SayAJ5RouteCGSgSo7NSErrorCSgtcfU_TA + 13 9 MapboxDirections 0x00000001075f8f50 $s16MapboxDirections0B0C9calculate_17completionHandlerSo20NSURLSessionDataTaskCAA12RouteOptionsC_ySayAA8WaypointCGSg_SayAA0I0CGSgSo7NSErrorCSgtctFySDySSypGcfU + 1072 10 MapboxDirections 0x00000001075f901d $s16MapboxDirections0B0C9calculate_17completionHandlerSo20NSURLSessionDataTaskCAA12RouteOptionsC_ySayAA8WaypointCGSg_SayAA0I0CGSgSo7NSErrorCSgtctFySDySSypGcfU_TA + 29 11 MapboxDirections 0x00000001075fe461 $s16MapboxDirections0B0C8dataTask33_9AB848AFC329A49F8F01862214F64FC2LL14forCalculating17completionHandler05errorO0So016NSURLSessionDataD0CAA0B7OptionsC_ySDySSypGcySo7NSErrorCctFy10Foundation0R0VSg_So13NSURLResponseCSgs5Error_pSgtcfU_yycfU0 + 145 12 MapboxDirections 0x0000000107601bb5 $s16MapboxDirections0B0C8dataTask33_9AB848AFC329A49F8F01862214F64FC2LL14forCalculating17completionHandler05errorO0So016NSURLSessionDataD0CAA0B7OptionsC_ySDySSypGcySo7NSErrorCctFy10Foundation0R0VSg_So13NSURLResponseCSgs5Error_pSgtcfU_yycfU0_TA + 21 13 MapboxDirections 0x00000001075fe2fd $sIeg_IeyB_TR + 45 14 libdispatch.dylib 0x000000010aef8d7f _dispatch_call_block_and_release + 12 15 libdispatch.dylib 0x000000010aef9db5 _dispatch_client_callout + 8 16 libdispatch.dylib 0x000000010af07080 _dispatch_main_queue_callback_4CF + 1540 17 CoreFoundation 0x0000000109e35a79 CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 9 18 CoreFoundation 0x0000000109e30126 __CFRunLoopRun + 2310 19 CoreFoundation 0x0000000109e2f4d2 CFRunLoopRunSpecific + 626 20 GraphicsServices 0x000000010eb0a2fe GSEventRunModal + 65 21 UIKitCore 0x00000001130b0fc2 UIApplicationMain + 140 22 Runner 0x0000000101162308 main + 72 23 libdyld.dylib 0x000000010af6e541 start + 1 ) libc++abi.dylib: terminating with uncaught exception of type NSException — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you for quick response, let me know if you need more details. By the way I was on 0.0.7, tried with 0.0.8, I am getting the same issue

**Comment by eopeter** [comment]
I am not able to replicate this issue. Does it still happen?
