### ISSUE TITLE
how to use spoken in chinese

### ISSUE THREAD

**Issue by jiazil** [eopeter/flutter_mapbox_navigation#172]
Chinese | ✅ Simplified | ✅ Mandarin | Uses VoiceOver
-- | -- | -- | --

1、how to use voiceover?
2、Natural-sounding turn instructions powered by [Amazon Polly](https://aws.amazon.com/polly/) (no configuration needed) how to use Amazon Polly?

or 1 of them ?

**Comment by eopeter** [comment]
Stale issue message

**Comment by eopeter** [comment]
Mapbox already uses Polly; have you tried setting the language option?
