### ISSUE TITLE
Getting gradle issue 

### ISSUE THREAD

**Issue by HitendraRathod10** [eopeter/flutter_mapbox_navigation#174]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.mapbox.navigation:android:2.4.1.
     Required by:
         project :app > project :flutter_mapbox_nav
      > Could not resolve com.mapbox.navigation:android:2.4.1.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/android/2.4.1/android-2.4.1.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/android/2.4.1/android-2.4.1.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s
Running Gradle task 'assembleDebug'...
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...

**Comment by akhilgorantala** [comment]
how to fix this
