### ISSUE TITLE
Black screen occurs on back cancel trip and physical back of the phone

### ISSUE THREAD

**Issue by ahmadbahsoun** [eopeter/flutter_mapbox_navigation#175]

**Comment by ahmadbahsoun** [comment]
I/SurfaceControl(29654): nativeRelease nativeObject s[-5476376611697737264] I/SurfaceControl(29654): nativeRelease nativeObject e[-5476376611697737264] I/ViewRootImpl@7e1f156[NavigationActivity](29654): Relayout returned: old=(0,0,720,1600) new=(0,0,720,1600) req=(720,1600)8 dur=4 res=0x5 s={false 0} ch=true fn=55 I/SurfaceView(29654): windowStopped(true) false com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.MapboxGLSurfaceView{af3f8cf V.E...... ........ 0,0-720,1460} of ViewRootImpl@7e1f156[NavigationActivity] I/ViewRootImpl@7e1f156[NavigationActivity](29654): stopped(true) old=false E/libEGL  (29654): call to OpenGL ES API with no current context (logged once per thread) D/MAPBOX_TELEMETRY(29654): MapboxNavigation onDestroy I/ViewRootImpl@7e1f156[NavigationActivity](29654): dispatchDetachedFromWindow D/InputTransport(29654): Input channel destroyed: '86340f7', fd=262

**Comment by shehzadraheem** [comment]
I'm facing the same issue. Do you find any solution?

**Comment by ahmadbahsoun** [comment]
I think In the build context you are going to an empty container or something like that so, in the build context just 
refer it to the previous page you have.
and the problem is solved.
@override
  Widget build(BuildContext context) {
    return const your_page();
  }

**Comment by eopeter** [comment]
this should be resolved
