### ISSUE TITLE
Auto navigation 

### ISSUE THREAD

**Issue by shehzadraheem** [eopeter/flutter_mapbox_navigation#176]
- As I click the start button for navigation, the cursor begins to move on route, even I didn't move from my position. 
- I want the cursor moves when I start to move from my position, like in google map navigation.

**Comment by eopeter** [comment]
Maybe you are in simulation mode?

**Comment by shehzadraheem** [comment]
I change `simulateRoute` to `false`. Now it's working. Thanks
