### ISSUE TITLE
MapBoxNavigation directions returning null for remaining duration and distance

### ISSUE THREAD

**Issue by vpalcar** [eopeter/flutter_mapbox_navigation#178]
On iOS MapBoxNavigation directions are returning null for the remaining duration and distance for embedded turn by turn navigation.

When I print the value of progress.distanceRemaining in the NavigationFactory.swift it returns correct values but I can’t find the way to access it on the dart side.

**Comment by lasd14** [comment]
Me too, in my OnRoutEvent I receive that my distanceRemaining and durationRemaining is null, I´m working with Android, after this I get an exception in the console
![image](https://user-images.githubusercontent.com/51976094/172412127-7449027a-8e16-4499-ab36-75a9bb650248.png)

**Comment by lasd14** [comment]
Thank you for your answer @vpalcar, I´ll check my code and try to fix the error

**Comment by anilguleria1988** [comment]
Flutter embeded mapbox navigation view widget MapBoxNavigationView() is not working. Even i have paste the example (https://pub.dev/packages/flutter_mapbox_navigation/example) code given in the package and also got the same error. I don't think that the example is also working. Please give some solution i am stuck here from last 2 months.
E/flutter ( 7987): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'FutureOr<double>'
E/flutter ( 7987): #0      MapBoxNavigationViewController.distanceRemaining.<anonymous closure>
package:flutter_mapbox_navigation/embedded/controller.dart:30
E/flutter ( 7987): #1      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter ( 7987): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 7987): <asynchronous suspension>
E/flutter ( 7987):
E/flutter ( 7987): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'FutureOr<double>'
E/flutter ( 7987): #0      MapBoxNavigationViewController.durationRemaining.<anonymous closure>
package:flutter_mapbox_navigation/embedded/controller.dart:35
E/flutter ( 7987): #1      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter ( 7987): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)

**Comment by eopeter** [comment]
This issue is resolved
