### ISSUE TITLE
Embedding Navigation View

### ISSUE THREAD

**Issue by gunreddyvishnu** [eopeter/flutter_mapbox_navigation#179]
after building route with _controller.buildRoute(wayPoints: wayPoints);
when i calling  _controller.startNavigation();
this is the problem iam  facing

I/nav-native(14514): Waypoints were not passed to setRoute. Trying to restore it from route itself.
W/nav-native(14514): Cannot find via_waypoints in passed route. On-board waypoints matching will be used.

**Comment by eopeter** [comment]
This issue is resolved
