### ISSUE TITLE
Change street name language to english

### ISSUE THREAD

**Issue by omkarkhalipe** [eopeter/flutter_mapbox_navigation#18]
Hi! The plugin works perfectly fine but in Gulf countries the city names are shown English but the street names are shown in Arabic, I need to show all the street names in English. Please help

**Comment by eopeter** [comment]
I can provide a way to set the language in the next release.

**Comment by omkarkhalipe** [comment]
That would be a awesome feature to have! Will be waiting for the next release. :)

**Comment by eopeter** [comment]
By default, the map inside displays road labels in the local language, while points of interest and places are displayed in the system’s preferred language, if that language is one of the eight supported by the Mapbox Streets source. The user can set the system’s preferred language in Settings, General Settings, Language & Region. Can you try setting your preferred language. does that make any difference?

**Comment by omkarkhalipe** [comment]
I just tried on my iPhone but still it shows arabic even when my language is English.

**Comment by eopeter** [comment]
Have you tried setting the language property for startNavigation()?

**Comment by omkarkhalipe** [comment]
> Have you tried setting the language property for startNavigation()?

I couldn't find a property "language" in `startNavigation()`.
I see these values in constructor
```
Future startNavigation(
      {Location origin,
      Location destination,
      NavigationMode mode = NavigationMode.drivingWithTraffic,
      bool simulateRoute = false}) async {
    assert(origin != null);
    assert(origin.name != null);
    assert(origin.latitude != null);
    assert(origin.longitude != null);
    assert(destination != null);
    assert(destination.name != null);
    assert(destination.latitude != null);
    assert(destination.longitude != null);
    final Map<String, Object> args = <String, dynamic>{
      "originName": origin.name,
      "originLatitude": origin.latitude,
      "originLongitude": origin.longitude,
      "destinationName": destination.name,
      "destinationLatitude": destination.latitude,
      "destinationLongitude": destination.longitude,
      "mode": mode.toString().split('.').last,
      "simulateRoute": simulateRoute
    };
    await _methodChannel.invokeMethod('startNavigation', args);
    _routeProgressSubscription = _streamRouteProgress.listen(_onProgressData);
  }

```

**Comment by eZoomOK** [comment]
I just updated the plugin and seems to be working. Thanks!

**Comment by omkarkhalipe** [comment]
I just updated the plugin and seems to be working. Thanks!
