### ISSUE TITLE
Doesnt work for sdk version 31+

### ISSUE THREAD

**Issue by Nedimko123** [eopeter/flutter_mapbox_navigation#180]
I get this error when I try to load it up, it builds successfully, but doesn't work. I used the code from the example

Using the latest Flutter version 3.0.3 Android, Dart 2.17.5 stable, maybe its this line- ```
that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/Mbgl-Mapbox( 5031): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

```
D/CompatibilityChangeReporter( 5031): Compat change id reported: 160794467; UID 10462; state: ENABLED
W/CrashReporter( 5031): Root directory doesn't exist
E/Mbgl-Mapbox( 5031): Error occurred while initializing telemetry
E/Mbgl-Mapbox( 5031): java.lang.IllegalArgumentException: com.example.fitness_app: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/Mbgl-Mapbox( 5031): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/Mbgl-Mapbox( 5031):   at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
E/Mbgl-Mapbox( 5031):   at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
E/Mbgl-Mapbox( 5031):   at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
E/Mbgl-Mapbox( 5031):   at com.mapbox.android.telemetry.AlarmSchedulerFlusher.register(AlarmSchedulerFlusher.java:31)
E/Mbgl-Mapbox( 5031):   at com.mapbox.android.telemetry.MapboxTelemetry.startAlarm(MapboxTelemetry.java:380)
E/Mbgl-Mapbox( 5031):   at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetry(MapboxTelemetry.java:374)
E/Mbgl-Mapbox( 5031):   at com.mapbox.android.telemetry.MapboxTelemetry.enable(MapboxTelemetry.java:114)
E/Mbgl-Mapbox( 5031):   at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.<init>(TelemetryImpl.java:33)
E/Mbgl-Mapbox( 5031):   at com.mapbox.mapboxsdk.ModuleProviderImpl.obtainTelemetry(ModuleProviderImpl.java:22)
E/Mbgl-Mapbox( 5031):   at com.mapbox.mapboxsdk.Mapbox.initializeTelemetry(Mapbox.java:167)
E/Mbgl-Mapbox( 5031):   at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:64)
E/Mbgl-Mapbox( 5031):   at com.dormmom.flutter_mapbox_navigation.factory.MapViewFactory.create(MapViewFactory.kt:16)
E/Mbgl-Mapbox( 5031):   at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)
E/Mbgl-Mapbox( 5031):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/Mbgl-Mapbox( 5031):   at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/Mbgl-Mapbox( 5031):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/Mbgl-Mapbox( 5031):   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/Mbgl-Mapbox( 5031):   at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/Mbgl-Mapbox( 5031):   at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/Mbgl-Mapbox( 5031):   at android.os.Handler.handleCallback(Handler.java:938)
E/Mbgl-Mapbox( 5031):   at android.os.Handler.dispatchMessage(Handler.java:99)
E/Mbgl-Mapbox( 5031):   at android.os.Looper.loopOnce(Looper.java:226)
E/Mbgl-Mapbox( 5031):   at android.os.Looper.loop(Looper.java:313)
E/Mbgl-Mapbox( 5031):   at android.app.ActivityThread.main(ActivityThread.java:8663)
E/Mbgl-Mapbox( 5031):   at java.lang.reflect.Method.invoke(Native Method)
E/Mbgl-Mapbox( 5031):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/Mbgl-Mapbox( 5031):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/Gralloc4( 5031): mapper 4.x is not supported
W/Gralloc3( 5031): mapper 3.x is not supported
I/gralloc ( 5031): Arm Module v1.0
W/Gralloc4( 5031): allocator 4.x is not supported
W/Gralloc3( 5031): allocator 3.x is not supported
W/ple.fitness_ap( 5031): Accessing hidden field Landroid/graphics/Typeface;->sSystemFontMap:Ljava/util/Map; (unsupported, reflection, allowed)
The Flutter DevTools debugger and profiler on SM A515F is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:37781/YvxH88iCxlo=/
I/Mbgl    ( 5031): {ple.fitness_app}[General]: Loaded Mapbox Common 9.1.0, built using 9.0.2.
I/OnboardRouterFiles( 5031): Initial size is 3488 bytes
I/ple.fitness_ap( 5031): Thread[1,tid=5031,Native,Thread*=0x7d27f20c00,peer=0x71d75ad8,"main"] recursive attempt to load library "/data/app/~~vijwqKtJRflPhoeAX6es6g==/com.example.fitness_app-k1pOgNCNMPf8Cug6ip7rTA==/lib/arm64/libmapbox-common.so"
E/MapboxNavNative( 5031): User defined HTTP service instance not provided from the module implementation.
E/MapboxNavNative( 5031): Module: com.mapbox.common.module.okhttp.MapboxOkHttpService@78bde23
E/MapboxNavNative( 5031): but present is: com.mapbox.common.module.okhttp.MapboxOkHttpService@78bde23
E/MapboxNavNative( 5031): Are you calling HttpServiceFactory.setUserDefined() correctly?
D/ConnectivityManager( 5031): StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3937)] [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3979)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4361)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4331)] [com.mapbox.navigation.utils.internal.NetworkStatusService.<init>(NetworkStatusService.kt:47)] [com.mapbox.navigation.core.MapboxNavigation.paramsProvider(MapboxNavigation.kt:789)] [com.mapbox.navigation.core.MapboxNavigation.access$paramsProvider(MapboxNavigation.kt:130)] [com.mapbox.navigation.core.MapboxNavigation$2.invoke(MapboxNavigation.kt:175)] [com.mapbox.navigation.core.MapboxNavigation$2.invoke(MapboxNavigation.kt:130)] [com.mapbox.common.module.provider.MapboxModuleProvider$defaultMapboxModuleCreator$1.getInstance(MapboxModuleProvider.kt:135)] [com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:69)] [com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:175)] [com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)] [com.dormmom.flutter_mapbox_navigation.factory.FlutterMapViewFactory.<init>(FlutterMapViewFactory.kt:174)] [com.dormmom.flutter_mapbox_navigation.factory.MapViewFactory.create(MapViewFactory.kt:17)] [io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)] [io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)] [io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)] [io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)] [io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)] [io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)] [io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)]
E/MapboxModuleProvider( 5031): Module loading failed
E/MapboxModuleProvider( 5031): java.lang.NoSuchMethodException: com.mapbox.navigation.trip.notification.internal.MapboxTripNotification.<init> []
E/MapboxModuleProvider( 5031):  at java.lang.Class.getConstructor0(Class.java:2363)
E/MapboxModuleProvider( 5031):  at java.lang.Class.getConstructor(Class.java:1759)
E/MapboxModuleProvider( 5031):  at com.mapbox.common.module.provider.MapboxModuleProvider$noArgConstructorCreator$1.getInstance(MapboxModuleProvider.kt:107)
E/MapboxModuleProvider( 5031):  at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:69)
E/MapboxModuleProvider( 5031):  at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:179)
E/MapboxModuleProvider( 5031):  at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
E/MapboxModuleProvider( 5031):  at com.dormmom.flutter_mapbox_navigation.factory.FlutterMapViewFactory.<init>(FlutterMapViewFactory.kt:174)
E/MapboxModuleProvider( 5031):  at com.dormmom.flutter_mapbox_navigation.factory.MapViewFactory.create(MapViewFactory.kt:17)
E/MapboxModuleProvider( 5031):  at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MapboxModuleProvider( 5031):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MapboxModuleProvider( 5031):  at android.os.Handler.handleCallback(Handler.java:938)
E/MapboxModuleProvider( 5031):  at android.os.Handler.dispatchMessage(Handler.java:99)
E/MapboxModuleProvider( 5031):  at android.os.Looper.loopOnce(Looper.java:226)
E/MapboxModuleProvider( 5031):  at android.os.Looper.loop(Looper.java:313)
E/MapboxModuleProvider( 5031):  at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MapboxModuleProvider( 5031):  at java.lang.reflect.Method.invoke(Native Method)
E/MapboxModuleProvider( 5031):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/MapboxModuleProvider( 5031):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/MapboxModuleProvider( 5031): Module loading failed
E/MapboxModuleProvider( 5031): java.lang.NoSuchFieldException: INSTANCE
E/MapboxModuleProvider( 5031):  at java.lang.Class.getField(Class.java:1635)
E/MapboxModuleProvider( 5031):  at com.mapbox.common.module.provider.MapboxModuleProvider$kotlinObjectReferenceProvider$1.getInstance(MapboxModuleProvider.kt:117)
E/MapboxModuleProvider( 5031):  at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:69)
E/MapboxModuleProvider( 5031):  at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:179)
E/MapboxModuleProvider( 5031):  at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
E/MapboxModuleProvider( 5031):  at com.dormmom.flutter_mapbox_navigation.factory.FlutterMapViewFactory.<init>(FlutterMapViewFactory.kt:174)
E/MapboxModuleProvider( 5031):  at com.dormmom.flutter_mapbox_navigation.factory.MapViewFactory.create(MapViewFactory.kt:17)
E/MapboxModuleProvider( 5031):  at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MapboxModuleProvider( 5031):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MapboxModuleProvider( 5031):  at android.os.Handler.handleCallback(Handler.java:938)
E/MapboxModuleProvider( 5031):  at android.os.Handler.dispatchMessage(Handler.java:99)
E/MapboxModuleProvider( 5031):  at android.os.Looper.loopOnce(Looper.java:226)
E/MapboxModuleProvider( 5031):  at android.os.Looper.loop(Looper.java:313)
E/MapboxModuleProvider( 5031):  at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MapboxModuleProvider( 5031):  at java.lang.reflect.Method.invoke(Native Method)
E/MapboxModuleProvider( 5031):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/MapboxModuleProvider( 5031):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/MapboxModuleProvider( 5031): Module loading failed
E/MapboxModuleProvider( 5031): java.lang.NoSuchMethodException: com.mapbox.navigation.trip.notification.internal.MapboxTripNotification.getInstance []
E/MapboxModuleProvider( 5031):  at java.lang.Class.getMethod(Class.java:2103)
E/MapboxModuleProvider( 5031):  at java.lang.Class.getMethod(Class.java:1724)
E/MapboxModuleProvider( 5031):  at com.mapbox.common.module.provider.MapboxModuleProvider$singletonReferenceProvider$1.getInstance(MapboxModuleProvider.kt:126)
E/MapboxModuleProvider( 5031):  at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:69)
E/MapboxModuleProvider( 5031):  at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:179)
E/MapboxModuleProvider( 5031):  at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
E/MapboxModuleProvider( 5031):  at com.dormmom.flutter_mapbox_navigation.factory.FlutterMapViewFactory.<init>(FlutterMapViewFactory.kt:174)
E/MapboxModuleProvider( 5031):  at com.dormmom.flutter_mapbox_navigation.factory.MapViewFactory.create(MapViewFactory.kt:17)
E/MapboxModuleProvider( 5031):  at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MapboxModuleProvider( 5031):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MapboxModuleProvider( 5031):  at android.os.Handler.handleCallback(Handler.java:938)
E/MapboxModuleProvider( 5031):  at android.os.Handler.dispatchMessage(Handler.java:99)
E/MapboxModuleProvider( 5031):  at android.os.Looper.loopOnce(Looper.java:226)
E/MapboxModuleProvider( 5031):  at android.os.Looper.loop(Looper.java:313)
E/MapboxModuleProvider( 5031):  at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MapboxModuleProvider( 5031):  at java.lang.reflect.Method.invoke(Native Method)
E/MapboxModuleProvider( 5031):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/MapboxModuleProvider( 5031):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/MapboxModuleProvider( 5031): Module loading failed
E/MapboxModuleProvider( 5031): java.lang.reflect.InvocationTargetException
E/MapboxModuleProvider( 5031):  at java.lang.reflect.Constructor.newInstance0(Native Method)
E/MapboxModuleProvider( 5031):  at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/MapboxModuleProvider( 5031):  at com.mapbox.common.module.provider.MapboxModuleProvider$defaultMapboxModuleCreator$1.getInstance(MapboxModuleProvider.kt:138)
E/MapboxModuleProvider( 5031):  at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:69)
E/MapboxModuleProvider( 5031):  at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:179)
E/MapboxModuleProvider( 5031):  at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
E/MapboxModuleProvider( 5031):  at com.dormmom.flutter_mapbox_navigation.factory.FlutterMapViewFactory.<init>(FlutterMapViewFactory.kt:174)
E/MapboxModuleProvider( 5031):  at com.dormmom.flutter_mapbox_navigation.factory.MapViewFactory.create(MapViewFactory.kt:17)
E/MapboxModuleProvider( 5031):  at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MapboxModuleProvider( 5031):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MapboxModuleProvider( 5031):  at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MapboxModuleProvider( 5031):  at android.os.Handler.handleCallback(Handler.java:938)
E/MapboxModuleProvider( 5031):  at android.os.Handler.dispatchMessage(Handler.java:99)
E/MapboxModuleProvider( 5031):  at android.os.Looper.loopOnce(Looper.java:226)
E/MapboxModuleProvider( 5031):  at android.os.Looper.loop(Looper.java:313)
E/MapboxModuleProvider( 5031):  at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MapboxModuleProvider( 5031):  at java.lang.reflect.Method.invoke(Native Method)
E/MapboxModuleProvider( 5031):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/MapboxModuleProvider( 5031):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/MapboxModuleProvider( 5031): Caused by: java.lang.IllegalArgumentException: com.example.fitness_app: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/MapboxModuleProvider( 5031): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/MapboxModuleProvider( 5031):  at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
E/MapboxModuleProvider( 5031):  at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:465)
E/MapboxModuleProvider( 5031):  at android.app.PendingIntent.getActivity(PendingIntent.java:451)
E/MapboxModuleProvider( 5031):  at android.app.PendingIntent.getActivity(PendingIntent.java:415)
E/MapboxModuleProvider( 5031):  at com.mapbox.navigation.trip.notification.internal.MapboxTripNotification.createPendingOpenIntent(MapboxTripNotification.kt:275)
E/MapboxModuleProvider( 5031):  at com.mapbox.navigation.trip.notification.internal.MapboxTripNotification.<init>(MapboxTripNotification.kt:112)
E/MapboxModuleProvider( 5031):  ... 23 more
E/MethodChannel#flutter/platform_views( 5031): Failed to handle method call
E/MethodChannel#flutter/platform_views( 5031): MapboxInvalidModuleException(type=NavigationTripNotification)
E/MethodChannel#flutter/platform_views( 5031):  at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:88)
E/MethodChannel#flutter/platform_views( 5031):  at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:179)
E/MethodChannel#flutter/platform_views( 5031):  at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
E/MethodChannel#flutter/platform_views( 5031):  at com.dormmom.flutter_mapbox_navigation.factory.FlutterMapViewFactory.<init>(FlutterMapViewFactory.kt:174)
E/MethodChannel#flutter/platform_views( 5031):  at com.dormmom.flutter_mapbox_navigation.factory.MapViewFactory.create(MapViewFactory.kt:17)
E/MethodChannel#flutter/platform_views( 5031):  at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)
E/MethodChannel#flutter/platform_views( 5031):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/MethodChannel#flutter/platform_views( 5031):  at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views( 5031):  at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter/platform_views( 5031):  at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter/platform_views( 5031):  at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter/platform_views( 5031):  at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter/platform_views( 5031):  at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter/platform_views( 5031):  at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter/platform_views( 5031):  at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#flutter/platform_views( 5031):  at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#flutter/platform_views( 5031):  at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MethodChannel#flutter/platform_views( 5031):  at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 5031):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/MethodChannel#flutter/platform_views( 5031):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/SurfaceView@cdff81f( 5031): uSP: rtp = Rect(0, 0 - 1080, 2256) rtsw = 1080 rtsh = 2256
I/SurfaceView@cdff81f( 5031): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
I/SurfaceView@cdff81f( 5031): aOrMT: uB = true t = android.view.SurfaceControl$Transaction@3edc6b0 fN = 1 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:319 
I/SurfaceView@cdff81f( 5031): aOrMT: vR.mWNT, vR = ViewRootImpl@e92b070[MainActivity]
I/ViewRootImpl@e92b070[MainActivity]( 5031): mWNT: t = android.view.SurfaceControl$Transaction@3edc6b0 fN = 1 android.view.SurfaceView.applyOrMergeTransaction:1628 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 
E/flutter ( 5031): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, NavigationTripNotification has been excluded from build but a correct alternative was not provided.
E/flutter ( 5031): Make sure that:
E/flutter ( 5031): - Your custom module implements com.mapbox.navigation.base.trip.notification.TripNotification.
E/flutter ( 5031): - Your custom module class is annotated with @MapboxModule(MapboxModuleType.NavigationTripNotification).
E/flutter ( 5031): - You've provided a `ModuleProvider` instance to Mapbox_TripNotificationModuleConfiguration#setModuleProvider before initializing the library,
E/flutter ( 5031):   unless `enableConfiguration` flag is set to false and your implementation has a public, non-arg constructor or is a Kotlin object., null, MapboxInvalidModuleException(type=NavigationTripNotification)
E/flutter ( 5031):      at com.mapbox.common.module.provider.MapboxModuleProvider.createModule(MapboxModuleProvider.kt:88)
E/flutter ( 5031):      at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:179)
E/flutter ( 5031):      at com.mapbox.navigation.core.MapboxNavigationProvider.create(MapboxNavigationProvider.kt:23)
E/flutter ( 5031):      at com.dormmom.flutter_mapbox_navigation.factory.FlutterMapViewFactory.<init>(FlutterMapViewFactory.kt:174)
E/flutter ( 5031):      at com.dormmom.flutter_mapbox_navigation.factory.MapViewFactory.create(MapViewFactory.kt:17)
E/flutter ( 5031):      at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:197)
E/flutter ( 5031):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/flutter ( 5031):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter ( 5031):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 5031):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter ( 5031):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/flutter ( 5031):      at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 5031):      at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 5031):      at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 5031):      at android.os.Looper.loopOnce(Looper.java:226)
E/flutter ( 5031):      at android.os.Looper.loop(Looper.java:313)
E/flutter ( 5031):      at android.app.ActivityThread.main(ActivityThread.java:8663)
E/flutter ( 5031):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 5031):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/flutter ( 5031):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/flutter ( 5031): )
E/flutter ( 5031): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 5031): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 5031): <asynchronous suspension>
E/flutter ( 5031): #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1134:18)
E/flutter ( 5031): <asynchronous suspension>
E/flutter ( 5031): #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:762:5)
E/flutter ( 5031): <asynchronous suspension>
E/flutter ( 5031): #4      TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1062:7)
E/flutter ( 5031): <asynchronous suspension>
E/flutter ( 5031): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:179:29)
E/flutter ( 5031): <asynchronous suspension>
E/flutter ( 5031): 
I/ViewRootImpl@e92b070[MainActivity]( 5031): mWNT: merge t to BBQ
I/ViewRootImpl@e92b070[MainActivity]( 5031): [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
I/ViewRootImpl@e92b070[MainActivity]( 5031): [DP] rdf()
D/ViewRootImpl@e92b070[MainActivity]( 5031): reportDrawFinished (fn: -1) 
I/ViewRootImpl@e92b070[MainActivity]( 5031): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager( 5031): startInputInner - Id : 0
I/InputMethodManager( 5031): startInputInner - mService.startInputOrWindowGainedFocus
D/InputMethodManager( 5031): startInputInner - Id : 0
V/MapboxHttpCallback( 5031): [HTTP] Request was successful (code = 200).
```

**Comment by iKlsR** [comment]
Same, works in the emulator but not on device.

**Comment by amitappening** [comment]
Facing the same issue, did anyone resolved this?

**Comment by santosh81066** [comment]
I had face this issue I had solved this by keeping simulateRoute: false,

**Comment by iKlsR** [comment]
Been experimenting with mapbox_gl and this for a few weeks, forked them, fixed a few misc issues where it randomly crashes and leaks memory and made a basic mvp using both. A great effort from the community but we ultimately decided to just go native. Mapbox needs to make Flutter a first class citizen for their sdks, the community or the packages in their current state can't deliver the functionality needed for a production ready app.

That being said, if the main author is willing to spend more time refining this, my company would be more than willing to sponsor a significant amount and revisit it later, we enjoy working with flutter but this is going to be a core component of our app and we don't have the capacity to do the channel ourselves atm.

**Comment by eopeter** [comment]
This issue is resolved
