### ISSUE TITLE
zoom is not working in fullscreen navigation

### ISSUE THREAD

**Issue by santosh81066** [eopeter/flutter_mapbox_navigation#181]
I am not Abel to zoom at start at full screen navigation on moving it is zooming but not at start
![WhatsApp Image 2022-07-16 at 5 47 01 PM](https://user-images.githubusercontent.com/34810098/179419172-27b6687f-1f19-4647-9472-627acac1e8c7.jpeg)

**Comment by kabira070797** [comment]
i face same issue . any solution for this

**Comment by santosh81066** [comment]
not yet waiting for an update

**Comment by kabira070797** [comment]
when you fix this issue ?

**Comment by santosh81066** [comment]
lets hope in next update eopeter solve the issues

**Comment by santosh81066** [comment]
sry I an not the author of this package to release an update

**Comment by Igormikheev** [comment]
I have the same problem

**Comment by a-ahmed116** [comment]
when will this be solved ?

**Comment by eopeter** [comment]
Stale issue message

**Comment by eopeter** [comment]
Stale issue message
