### ISSUE TITLE
Embedded navigation no working on Android

### ISSUE THREAD

**Issue by SkilyFrance** [eopeter/flutter_mapbox_navigation#182]
Hello Guys,
@eopeter thanks for this package.

I'm working on project with embedded navigation : Works fine on iOS but no route is drawn in android.
It is same code but result is different.

**Additional information** 
I use these packages level :
- mapbox_gl: ^0.16.0
- flutter_mapbox_navigation: ^0.0.26

To avoid a duplicate **telemetry**( conflict), I had to add this line on my build.gradle :
`    configurations {
        all*.exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-telemetry'
   }`
   
   
Can I do something ?

Thanks for help.

**Comment by santosh81066** [comment]
we are also facing the same we are waiting for an update

**Comment by fpollakowsky** [comment]
Same here. Seems like it's going into free driving mode.

**Comment by mostafaac30** [comment]
hi @SkilyFrance @santosh81066 @fpollakowsky  

I have a deadline and need this package to work well for me
if you have updated it with Android to work with navigation, please share the Repo link with me.
I'll appreciate that too much.

**Comment by eopeter** [comment]
This issue is resolved
