### ISSUE TITLE
Migration to V2 Navigation SDK

### ISSUE THREAD

**Issue by SkilyFrance** [eopeter/flutter_mapbox_navigation#183]
Hi @eopeter ,
Once again : Thanks for this package.

Did you plan to upgrade to V2 Navigation SDK ?
Severals optimizations, new features and would allow us to migrate to Metered trips (Less expensive than normal pack).

Please, give us answers cause we are in trouble at this moment.

Thanks  for help.
Guillaume

**Comment by eopeter** [comment]
The code has been migrated and I am back testing and will update the plug-in.

**Comment by SkilyFrance** [comment]
> The code has been migrated and I am back testing and will update the plug-in.
> […](#)
> On Jul 22, 2022, at 4:20 AM, Skily ***@***.***> wrote: ﻿ Hi @eopeter , Once again : Thanks for this package. Did you plan to upgrade to V2 navigation ? Severals optimizations, new features and would allow us to migrate to Metered trips (Less expensive than normal pack). Please, give us answers cause we are in trouble at this moment. Thanks for help. Guillaume — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

Hi Emmanuel :)

Thanks for your answer.
It would be amazing : Can't wait to see this new version.


Have a nice day,
Guillaume

**Comment by SkilyFrance** [comment]
Hello @eopeter ,
Hope you are fine.

Do you have any news about this migration and plug-in update ?
We have a project in production and it becomes critical.

Thanks for help,
Guillaume
