### ISSUE TITLE
Multiple markers inside navigation view

### ISSUE THREAD

**Issue by vmwsree** [eopeter/flutter_mapbox_navigation#186]
I am trying to build an app that shows other friends location while in the navigation view.Thus zooming out shows different markers indicating their location. Is it possible to implement this inside navigation view or any other sdk support this in flutter or android.

**Comment by kabira070797** [comment]
try with heremap sdk

**Comment by kabira070797** [comment]
> I am trying to build an app that shows other friends location while in the navigation view.Thus zooming out shows different markers indicating their location. Is it possible to implement this inside navigation view or any other sdk support this in flutter or android.

try with heremap sdk

**Comment by eopeter** [comment]
Stale issue message

**Comment by neildunlop** [comment]
This is actually something I need, so I'm happy to take a look.  I won't get to it for around 4 weeks tho because I'm off to Europe testing my navigation app in the Alps  (hence my vote for offline navigation!) :)

**Comment by eopeter** [comment]
Stale issue message

**Comment by vsnikhilvs** [comment]
So, its 2025 and support for Multiple markers is not implemented yet?
