### ISSUE TITLE
Ability to embed navigation and change to metric units

### ISSUE THREAD

**Issue by jeanres** [eopeter/flutter_mapbox_navigation#19]
Hi, good work on the plugin! 

Can you add the ability to use kilometres and not miles? also it would be great to embed the map in my own views.

**Comment by eopeter** [comment]
You can now change the voiceUnits in v0.0.10. Changing units work fine in Android but in iOS, the units seems to match the Locale that is set using "language" property on startNavigation or the default device language.

Embedding is coming soon in a later version
