### ISSUE TITLE
embedded view height

### ISSUE THREAD

**Issue by mostafaac30** [eopeter/flutter_mapbox_navigation#191]
How can I resize the navigation view to take just two-thirds of the height in ios?
instead of full-view.

**Comment by eopeter** [comment]
See the embedded example.

**Comment by mostafaac30** [comment]
> 

Thanks, @eopeter I have tried it But I'm facing an issue with it
route building It did also hear sound instructions without a Navigation view (just remains on map view)

Help with that, please

**Comment by mostafaac30** [comment]
Also sometimes I got 

MapBoxEvent.route_build_failed

**Comment by mostafaac30** [comment]
Hi @eopeter can you help me, please

**Comment by eopeter** [comment]
This issue is resolved
