### ISSUE TITLE
polyline not compatible error only with ios

### ISSUE THREAD

**Issue by tegaologe** [eopeter/flutter_mapbox_navigation#193]
Anyone having issues with polyline not compatible on ios. 

Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code

Uncategorized (Xcode): Command EmitSwiftModule failed with a nonzero exit code

Swift Compiler Error (Xcode): Compiling for iOS 10.0, but module 'Polyline' has a minimum deployment target of iOS 12.0:

**Comment by eopeter** [comment]
Stale issue message
