### ISSUE TITLE
Embedded navigation is not working on Android while working perfectly on IOS

### ISSUE THREAD

**Issue by kirill0012** [eopeter/flutter_mapbox_navigation#194]
Mapbox's embedded navigation seems to be broken on Android specifically as it is working perfectly fine on iOS devices. I've tried running navigation on multiple Android OS versions and here's what I've found:

- Android 9 and below: the map view shows up but navigation does not start
- Android 10 and above: the app crashes on map view

Is this a known issue? Is any work being done to fix this at all? I have a project that I'm working on and I've missed my deadline because of this issue. Any help or opinion would be greatly appreciated.

**Comment by mostafaac30** [comment]
same issue

**Comment by mostafaac30** [comment]
@kirill0012 got a solution for it?

**Comment by mostafaac30** [comment]
hi @eopeter  

I have a deadline and need this package to work well for me
if you have updated it with Android to work with navigation, please share the Repo link with me.
I'll appreciate that too much.

**Comment by Developmenteam30** [comment]
i am facing problem in normal navigation it only start free drive session. can anyone help me to do normal navigation?

**Comment by studiozocaro** [comment]
same problem

**Comment by aososam** [comment]
same problem

**Comment by eopeter** [comment]
This issue is resolved
