### ISSUE TITLE
Silent waypoints

### ISSUE THREAD

**Issue by blkcelebration** [eopeter/flutter_mapbox_navigation#195]
Hi,
I need to implement silent waypoints on my navigation. This option exists in Mapbox SDK, but not added to this package. Is there any workaround with which I can implement it? Or a possibility to add it to the package.

Thanks!

**Comment by eopeter** [comment]
Do you want to send a PR? Can add it to the backlog but it’s very long now.

**Comment by neildunlop** [comment]
PR #214 submitted that should implement silent/named waypoint functionality for Android in the same way as iOS.

**Comment by eopeter** [comment]
Thank you @neildunlop
