### ISSUE TITLE
Custom routing account not found

### ISSUE THREAD

**Issue by studiozocaro** [eopeter/flutter_mapbox_navigation#200]
I/nav-native(11444): Directions Service: Get route request: https://api.mapbox.com/directions/v5/331c7fd3-48ac-4cea-a743-960894fc22e7/cycling/-77.0401239,38.9111117;-77.0384717,38.9111368;-77.0384824,38.9104021;-77.0385039,38.9096508?access_token=****4J9A&geometries=polyline6&alternatives=true&overview=full&steps=true&layers=;&continue_straight=true&annotations=distance&language=it&roundabout_exits=true&voice_instructions=true&banner_instructions=true&voice_units=metric&enable_refresh=true
E/        (11444): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0102]
I/nav-native(11444): Directions Service: Get route response: {"message":"Custom routing account not found"} with code 404

**Comment by eopeter** [comment]
Stale issue message
