### ISSUE TITLE
Version V1, it costs $5 per month for each device. A huge scam. Beware!!!!

### ISSUE THREAD

**Issue by studiozocaro** [eopeter/flutter_mapbox_navigation#201]
The official version pub.dev 0.26 is the sdk version V1, it costs $5 per month for each device. A huge scam.
This on GithHub is the v2 version, but on android it doesn't work.
Beware!!!!

**Comment by eopeter** [comment]
How is it a a huge scam? You don’t have to use it. On Dec 31, 2022, at 3:58 PM, studiozocaro ***@***.***> wrote:﻿
The official version pub.dev 0.26 is the sdk version V1, it costs $5 per month for each device. A huge scam.
This on GithHub is the v2 version, but on android it doesn't work.
Beware!!!!

**Comment by studiozocaro** [comment]
My billing
Navigation SDKs: 28 monthly active users
A user of Mapbox services within your app during your month-long billing period including Directions API, Vector Tiles API, and Raster Tiles API requests.
$90.00
Hide details
up to 10 monthly active users — free
$0.00
11 to 500 — **$5.00 / 1**
$90.00

**Comment by studiozocaro** [comment]
https://www.mapbox.com/pricing/#session-user-pricing

Navigation SDK. --> select V1 (in accord version on  pub.dev 0.26)

Monthly active users. 
**Cost per user:**
Up to 10.   Free
11 - 500   **$5.00**
501 - 1,000. $4.50
1,001 - 2,500  $4.00
2,500+.....
