### ISSUE TITLE
Duplicate classes issue with mapbox_gl and flutter_mapbox_navigation package

### ISSUE THREAD

**Issue by alpeshshiyal** [eopeter/flutter_mapbox_navigation#208]
i have updated flutter_mapbox_navigation package with latest version after that i have also updated android gradle version. 

also i have added following configration in android/app/build.gradle:
configurations {      all*.exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-telemetry' }

using following versions:
 flutter_mapbox_navigation: ^0.1.0
 mapbox_gl: ^0.16.0

getting following issue:

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.mapbox.android.core.location.LocationEngine found in modules jetified-common-23.2.2-runtime (com.mapbox.common:common:23.2.2) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineCallback found in modules jetified-common-23.2.2-runtime (com.mapbox.common:common:23.2.2) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineProvider found in modules jetified-common-23.2.2-runtime (com.mapbox.common:common:23.2.2) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineRequest found in modules jetified-common-23.2.2-runtime (com.mapbox.common:common:23.2.2) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineRequest$1 found in modules jetified-common-23.2.2-runtime (com.mapbox.common:common:23.2.2) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineRequest$Builder found in modules jetified-common-23.2.2-runtime (com.mapbox.common:common:23.2.2) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineResult found in modules jetified-common-23.2.2-runtime (com.mapbox.common:common:23.2.2) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.permissions.PermissionsListener found in modules jetified-common-23.2.2-runtime (com.mapbox.common:common:23.2.2) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.permissions.PermissionsManager found in modules jetified-common-23.2.2-runtime (com.mapbox.common:common:23.2.2) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.permissions.PermissionsManager$AccuracyAuthorization found in modules jetified-common-23.2.2-runtime (com.mapbox.common:common:23.2.2) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 7s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ellexaD** [comment]
I have the same problem...
Have you found a solution?

**Comment by alpeshshiyal** [comment]
> I have the same problem... Have you found a solution?
I have solved this error but Runtime behavior is not working

-->you need to add following configuration in your app level build.gradle file inside android { } tags

configurations {
        all*.exclude group: 'com.mapbox.common', module: 'common'
}

-->And also need to add following  provider inside application tag in manifest file

<provider
           android:name="androidx.startup.InitializationProvider"
           android:authorities="${applicationId}.androidx-startup"
           tools:node="remove" />

do flutter clean after this and try to run project.

Using above solution app will run perfectly but start navigation feature is not working

**Comment by Kashif-Asghar60** [comment]
@alpeshshiyal  what do you mean by
 "-->And also need to add following provider inside application tag in manifest file"??
 Which thing you are referring to add in manifest file?.
and  Are you able to run the project for ios and android using latest version of mapbox-gl and mapbox navigation?

**Comment by eopeter** [comment]
Please review the reps between this plugin and other favs and sync the versions

**Comment by Hi99simon** [comment]
Please review the reps between this plugin and other favs and sync the versions

what does this mean?

using mapbox_gl 0.16 and mapbox navigation 0.1.6

duplicate class error:
Duplicate class com.mapbox.android.core.location.LocationEngine found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineCallback found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineProvider found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineRequest found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineRequest$1 found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineRequest$Builder found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineResult found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.permissions.PermissionsListener found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.permissions.PermissionsManager found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.permissions.PermissionsManager$AccuracyAuthorization found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)

**Comment by alpeshshiyal** [comment]
> @alpeshshiyal what do you mean by "-->And also need to add following provider inside application tag in manifest file"?? Which thing you are referring to add in manifest file?. and Are you able to run the project for ios and android using latest version of mapbox-gl and mapbox navigation?

@Kashif-Asghar60  actually i have added code but it is not showing after posting 

you have see that code in below image

<img width="569" alt="image" src="https://github.com/eopeter/flutter_mapbox_navigation/assets/40767883/a329a76e-0ff4-42ec-85c6-c59abe2fe5ec">

**Comment by eopeter** [comment]
Does this help you? https://stackoverflow.com/questions/67277228/android-build-gradle-exclude-duplicate-classes

**Comment by alpeshshiyal** [comment]
> 

i haven't use this 

but i'm getting this error after upgrading with latest version flutter_mapbox_navigation: ^0.1.7


* What went wrong:
A problem occurred configuring project ':flutter_mapbox_navigation'.
> Could not resolve all files for configuration ':flutter_mapbox_navigation:classpath'.
   > Could not download access-token-0.4.0.jar (com.mapbox.gradle.plugins:access-token:0.4.0)
      > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/access-token/0.4.0/access-token-0.4.0.jar'.
         > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/gradle/plugins/access-token/0.4.0/access-token-0.4.0.jar'. Received status code 401 from server: Unauthorized
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':flutter_mapbox_navigation' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':flutter_mapbox_navigation' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Retrying Gradle Build: #3, wait time: 400ms
[!] Gradle threw an error while downloading artifacts from the network.
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.


@eopeter can you please advice to resolve this issue?

**Comment by eopeter** [comment]
Please follow the directions on the ReadMe on how to setup your Mapbox credentials
