### ISSUE TITLE
Linux support possible?

### ISSUE THREAD

**Issue by christianfl** [eopeter/flutter_mapbox_navigation#215]
Hey! Thanks for this nice plugin. As linux phones are emerging and Flutter apps work really well on them, what do you think about Linux support? Could you point to what would have to be done to support the Linux platform?

Getting a GPS fix with flutter-geolocator seems to be possible.

**Comment by neildunlop** [comment]
The majority of the necessary functionality comes from the Mapbox SDK.
There are versions for iOS and Andriod. If either of those works on a Linux
phone then there's a chance.

**Comment by eopeter** [comment]
Yes there is no reason why support for Linuxcannot be addedOn May 1, 2023, at 3:30 AM, Neil Dunlop ***@***.***> wrote:﻿
The majority of the necessary functionality comes from the Mapbox SDK.
There are versions for iOS and Andriod. If either of those works on a Linux
phone then there's a chance.

**Comment by eopeter** [comment]
Stale issue message
