### ISSUE TITLE
Change in LeakCanary dependencies reduced my app us 20MB 

### ISSUE THREAD

**Issue by orlandev** [eopeter/flutter_mapbox_navigation#216]
Changing the dependency of leakcanary from implementation to debugImplementation, my application had a reduction in the final weight of about 20Mb

before
           implementation "com.squareup.leakcanary:leakcanary-android:2.9.1"
 after
         debugImplementation "com.squareup.leakcanary:leakcanary-android:2.9.1"

**Comment by eopeter** [comment]
Thank you! Added this
