### ISSUE TITLE
Android embedded view not working

### ISSUE THREAD

**Issue by marcotrumpet** [eopeter/flutter_mapbox_navigation#228]
Hi I'm having issue with Android embedded view

> D/EGL_emulation(22643): app_time_stats: avg=1792.45ms min=1.57ms max=28042.78ms count=16
> E/MethodChannel#flutter/platform_views(22643): Failed to handle method call
> E/MethodChannel#flutter/platform_views(22643): android.view.InflateException: Binary XML file line #6 in com.example.motoz:layout/navigation_activity: Binary XML file line #6 in com.example.motoz:layout/navigation_activity: Error inflating class com.mapbox.navigation.dropin.NavigationView
> E/MethodChannel#flutter/platform_views(22643): Caused by: android.view.InflateException: Binary XML file line #6 in com.example.motoz:layout/navigation_activity: Error inflating class com.mapbox.navigation.dropin.NavigationView
> E/MethodChannel#flutter/platform_views(22643): Caused by: java.lang.reflect.InvocationTargetException
> E/MethodChannel#flutter/platform_views(22643): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
> E/MethodChannel#flutter/platform_views(22643): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
> E/MethodChannel#flutter/platform_views(22643): 	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
> E/MethodChannel#flutter/platform_views(22643): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
> E/MethodChannel#flutter/platform_views(22643): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
> E/MethodChannel#flutter/platform_views(22643): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
> E/MethodChannel#flutter/platform_views(22643): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
> E/MethodChannel#flutter/platform_views(22643): 	at eopeter.flutter_mapbox_navigation.databinding.NavigationActivityBinding.inflate(NavigationActivityBinding.java:42)
> E/MethodChannel#flutter/platform_views(22643): 	at eopeter.flutter_mapbox_navigation.databinding.NavigationActivityBinding.inflate(NavigationActivityBinding.java:36)
> E/MethodChannel#flutter/platform_views(22643): 	at com.eopeter.flutter_mapbox_navigation.factory.EmbeddedNavigationViewFactory.create(EmbeddedNavigationViewFactory.kt:26)
> E/MethodChannel#flutter/platform_views(22643): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:503)
> E/MethodChannel#flutter/platform_views(22643): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:163)
> E/MethodChannel#flutter/platform_views(22643): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
> E/MethodChannel#flutter/platform_views(22643): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
> E/MethodChannel#flutter/platform_views(22643): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
> E/MethodChannel#flutter/platform_views(22643): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
> E/MethodChannel#flutter/platform_views(22643): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
> E/MethodChannel#flutter/platform_views(22643): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
> E/MethodChannel#flutter/platform_views(22643): 	at android.os.Handler.handleCallback(Handler.java:942)
> E/MethodChannel#flutter/platform_views(22643): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> E/MethodChannel#flutter/platform_views(22643): 	at android.os.Looper.loopOnce(Looper.java:201)
> E/MethodChannel#flutter/platform_views(22643): 	at android.os.Looper.loop(Looper.java:288)
> E/MethodChannel#flutter/platform_views(22643): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
> E/MethodChannel#flutter/platform_views(22643): 	at java.lang.reflect.Method.invoke(Native Method)
> E/MethodChannel#flutter/platform_views(22643): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> E/MethodChannel#flutter/platform_views(22643): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
> E/MethodChannel#flutter/platform_views(22643): Caused by: java.lang.IllegalStateException: Please ensure that the hosting Context is a valid ViewModelStoreOwner
> E/MethodChannel#flutter/platform_views(22643): 	at com.mapbox.navigation.dropin.internal.extensions.ContextEx.toViewModelStoreOwner(ContextEx.kt:19)
> E/MethodChannel#flutter/platform_views(22643): 	at com.mapbox.navigation.dropin.NavigationView.<init>(NavigationView.kt:87)
> E/MethodChannel#flutter/platform_views(22643): 	at com.mapbox.navigation.dropin.NavigationView.<init>(Unknown Source:13)
> E/MethodChannel#flutter/platform_views(22643): 	... 26 more
> E/flutter (22643): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, Binary XML file line #6 in com.example.motoz:layout/navigation_activity: Binary XML file line #6 in com.example.motoz:layout/navigation_activity: Error inflating class com.mapbox.navigation.dropin.NavigationView, null, android.view.InflateException: Binary XML file line #6 in com.example.motoz:layout/navigation_activity: Binary XML file line #6 in com.example.motoz:layout/navigation_activity: Error inflating class com.mapbox.navigation.dropin.NavigationView
> E/flutter (22643): Caused by: android.view.InflateException: Binary XML file line #6 in com.example.motoz:layout/navigation_activity: Error inflating class com.mapbox.navigation.dropin.NavigationView
> E/flutter (22643): Caused by: java.lang.reflect.InvocationTargetException
> E/flutter (22643): 	at java.lang.reflect.Constructor.newInstance0(Native Method)
> E/flutter (22643): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
> E/flutter (22643): 	at android.view.LayoutInflater.createView(LayoutInflater.java:858)
> E/flutter (22643): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
> E/flutter (22643): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
> E/flutter (22643): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
> E/flutter (22643): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
> E/flutter (22643): 	at eopeter.flutter_mapbox_navigation.databinding.NavigationActivityBinding.inflate(NavigationActivityBinding.java:42)
> E/flutter (22643): 	at eopeter.flutter_mapbox_navigation.databinding.NavigationActivityBinding.inflate(NavigationActivityBinding.java:36)
> E/flutter (22643): 	at com.eopeter.flutter_mapbox_navigation.factory.EmbeddedNavigationViewFactory.create(EmbeddedNavigationViewFactory.kt:26)
> E/flutter (22643): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:503)
> E/flutter (22643): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:163)
> E/flutter (22643): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
> E/flutter (22643): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
> E/flutter (22643): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
> E/flutter (22643): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
> E/flutter (22643): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
> E/flutter (22643): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
> E/flutter (22643): 	at android.os.Handler.handleCallback(Handler.java:942)
> E/flutter (22643): 	at android.os.Handler.dispatchMessage(Handler.java:99)
> E/flutter (22643): 	at android.os.Looper.loopOnce(Looper.java:201)
> E/flutter (22643): 	at android.os.Looper.loop(Looper.java:288)
> E/flutter (22643): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
> E/flutter (22643): 	at java.lang.reflect.Method.invoke(Native Method)
> E/flutter (22643): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
> E/flutter (22643): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
> E/flutter (22643): Caused by: java.lang.IllegalStateException: Please ensure that the hosting Context is a valid ViewModelStoreOwner
> E/flutter (22643): 	at com.mapbox.navigation.dropin.internal.extensions.ContextEx.toViewModelStoreOwner(ContextEx.kt:19)
> E/flutter (22643): 	at com.mapbox.navigation.dropin.NavigationView.<init>(NavigationView.kt:87)
> E/flutter (22643): 	at com.mapbox.navigation.dropin.NavigationView.<init>(Unknown Source:13)
> E/flutter (22643): 	... 26 more
> E/flutter (22643): )
> E/flutter (22643): #0      StandardMethodCodec.decodeEnvelope
> message_codecs.dart:652
> E/flutter (22643): #1      MethodChannel._invokeMethod
> platform_channel.dart:310
> E/flutter (22643): <asynchronous suspension>
> E/flutter (22643): #2      ExpensiveAndroidViewController._sendCreateMessage
> platform_views.dart:1040
> E/flutter (22643): <asynchronous suspension>
> E/flutter (22643): #3      AndroidViewController.create
> platform_views.dart:763
> E/flutter (22643): <asynchronous suspension>
> E/flutter (22643):
> D/EGL_emulation(22643): app_time_stats: avg=9604.58ms min=120.16ms max=19088.99ms count=2

I tried the latest version from pub 0.1.1 (at this time updated 8 days ago) and also directly master.

Nothing seems to work, do you guys have an idea?

**Comment by neildunlop** [comment]
I think there is a fix in the repo but it's not been published yet. I
checked out the latest commit from github and the embedded android view
works.

**Comment by eopeter** [comment]
Yes, that PR resolves the Android Embedding. I just pushed version `0.1.2` to pub spec that has that working.
