### ISSUE TITLE
Mapbox Token 

### ISSUE THREAD

**Issue by vincent-caron** [eopeter/flutter_mapbox_navigation#23]
Hello,

I've a valid token to use mapbox services.
I want to test navigation with flutter, so i've downloaded the example program. 
I've created a values directory with a strings.xml inside.
I've put all the necessary informations in the file.

When I click on start navigation, it tells we that i need a valid access token.

What am i doing wrong ?

Thanks

Vincent

**Comment by Augustpi** [comment]
Hi, 
Are you sure @vincent-caron,
you should put your Mapbox default access token into a tag with name attribute "mapbox_access_token" on string.xml
example it's working for me.

**Comment by Shubham-Narkhede** [comment]
@eopeter bro I have the same issue. My code is running well on debug mode as I added all the keys in strings.xml and gradle files. But when I'm going to build release apk it not works

**Comment by NicolasVermi** [comment]
I've the same issue https://stackoverflow.com/questions/76006482/flutter-mapbox-navigation-aapterrorresource-string-mapbox-access-token-aka-eo
