### ISSUE TITLE
Version 0.1.2 - After click the navigation close button, it will redirect to the another  Map View in Android Side and but iOS side, it will be redirected previous screen

### ISSUE THREAD

**Issue by dschandrasekara** [eopeter/flutter_mapbox_navigation#230]
I'm using version 0.1.2 for flutter project
Once i launch the navigation view in ios application and close it by clicking the close button, it is redirected my previous UI to automatically. that's correct behaviour and i'm expecting it. 
But in android side, it has different behaviour, once i click the navigation close button, even though navigation view is closed, it is redirected another MapView instead of my previous UI. so then i can't go to my UI, because that map is in the whole screen. it is not my expected behaviour. i want to redirect to my previous UI screen, once i click close button of navigation view. 
Please, help me to resolve this issue. 

I called this method from my UI. 
```
Future<bool?> initNavigationMap({required ValueSetter<RouteEvent> onRouteEvent}) async {
    MapBoxOptions defaultOptions = MapBoxOptions(
          zoom: 15.0,
          tilt: 0.0,
          bearing: 0.0,
          enableRefresh: false,
          alternatives: false,
          voiceInstructionsEnabled: true,
          bannerInstructionsEnabled: true,
          allowsUTurnAtWayPoints: true,
          mode: MapBoxNavigationMode.drivingWithTraffic,
          units: VoiceUnits.imperial,
          simulateRoute: false,
          animateBuildRoute: true,
          longPressDestinationEnabled: true,
          enableFreeDriveMode: false,
          language: "en");
    MapBoxNavigation.instance.setDefaultOptions(defaultOptions);
    MapBoxNavigation.instance.registerRouteEventListener(onRouteEvent);
    return await MapBoxNavigation.instance.startNavigation(wayPoints: wayPoints);
  }
```

**Comment by eopeter** [comment]
Fixed in #236 and deployed to pub with v0.1.3
