### ISSUE TITLE
iOS: navigation_cancelled event never sent back to Flutter

### ISSUE THREAD

**Issue by marcotrumpet** [eopeter/flutter_mapbox_navigation#233]
Just to keep track of it, navigation_cancelled is never sent back to flutter.

That's because here https://github.com/eopeter/flutter_mapbox_navigation/blob/130f20b0fcca03eafa04a820e027305b3ceef153/ios/Classes/NavigationFactory.swift#LL383C25-L383C25 eventSink is set to nil so there is no way other delegates can act on it. I'm working on a PR for it. Main idea is that if the user sets `showEndOfRouteFeedback=false` as per https://github.com/eopeter/flutter_mapbox_navigation/pull/231 , delegate will assign nil to event sink as now, if not (so the end of route feedback page is shown) it will let other delegates set it to nil

**Comment by marcotrumpet** [comment]
Also, having [this](https://github.com/eopeter/flutter_mapbox_navigation/blob/130f20b0fcca03eafa04a820e027305b3ceef153/lib/src/models/route_event.dart#LL14C57-L14C57)
```dart
eventType = MapBoxEvent.values[json['eventType']];
``` 
assumes enum have the same index for both Swift and Dart side.. and it's not the case, so values like `navigation_finished` are always interpreted as `navigation_running`

**Comment by usamaKabir07** [comment]
Hi @marcotrumpet any solutions for this?

**Comment by marcotrumpet** [comment]
> Hi @marcotrumpet any solutions for this?

working on android side

**Comment by eopeter** [comment]
This HACK PR #236 will send the cancel event from Android when the cancel button is pressed.

**Comment by marcotrumpet** [comment]
> This HACK PR #236 will send the cancel event from Android when the cancel button is pressed.

This issue is about iOS and you close it with a PR about Android?
Also the way to catch the close navigation button in Android is to provide your own implementation of the button as mapbox itself said.

My pr solves also this but you don't want to use it
