### ISSUE TITLE
Lint rules adoption

### ISSUE THREAD

**Issue by marcotrumpet** [eopeter/flutter_mapbox_navigation#241]
based on [this](https://github.com/eopeter/flutter_mapbox_navigation/discussions/239) start implementing and following lint rules package https://pub.dev/packages/very_good_analysis

**Comment by eopeter** [comment]
@marcotrumpet will just using this do? [PR 243](https://github.com/eopeter/flutter_mapbox_navigation/pull/243)

**Comment by eopeter** [comment]
from Github and supports Dart: https://github.com/github/super-linter

**Comment by marcotrumpet** [comment]
> @marcotrumpet will just using this do? [PR 243](https://github.com/eopeter/flutter_mapbox_navigation/pull/243)

probably yes, if you want to test it, I've solved all the issue (there was a TODO that I cannot solve so it's still there) but I need to test everything.. So I can create the PR but I'll ask you help testing all the features

**Comment by eopeter** [comment]
Linting worked well. The good thing about this is it does all languages, so Swift, Dart, Java, Kotlin. This is the result of last PR: https://github.com/eopeter/flutter_mapbox_navigation/actions/runs/5083104351/jobs/9133687606?pr=245

I think we should just close this work item unless you think there is more to be had with the pub package

**Comment by marcotrumpet** [comment]
> Linting worked well. The good thing about this is it does all languages, so Swift, Dart, Java, Kotlin. This is the result of last PR: https://github.com/eopeter/flutter_mapbox_navigation/actions/runs/5083104351/jobs/9133687606?pr=245
> 
> 
> 
> I think we should just close this work item unless you think there is more to be had with the pub package

The good thing about that package is that "force" everyone to follow the same rules to write consistent code. I'm not at my pc now, tomorrow I'll do a PR so you can check the code your self.. It's just a prettier way to write Dart code following dart convention, if you like it we can keep it if it's too much I'll delete the PR, what do you think?

**Comment by eopeter** [comment]
Sounds good; send PR when ready
