### ISSUE TITLE
iOS bug FreeDriveViewController

### ISSUE THREAD

**Issue by marcotrumpet** [eopeter/flutter_mapbox_navigation#244]
<img width="779" alt="Screenshot 2023-05-25 alle 17 36 57" src="https://github.com/eopeter/flutter_mapbox_navigation/assets/35219231/93cb28bf-5501-4c44-a438-fca05c380e57">
 I have this on iOS.. the viewcontroller file is under example/ios not ios/Classes like other view controller.. could it be the problem?

**Comment by marcotrumpet** [comment]
<img width="438" alt="Screenshot 2023-05-25 alle 17 38 59" src="https://github.com/eopeter/flutter_mapbox_navigation/assets/35219231/de67cca1-c85f-4d9a-85ec-bf668268370e">
Check the structure here @eopeter should be about https://github.com/eopeter/flutter_mapbox_navigation/pull/240

**Comment by eopeter** [comment]
It should be under Classes folder

**Comment by eopeter** [comment]
it compiles fine for me because Xcode knows to find it and the Xcode schema is gitignored but we should move it. I can move it and do a push

**Comment by eopeter** [comment]
Fixed with #245
