### ISSUE TITLE
Master doesn't work anymore

### ISSUE THREAD

**Issue by marcotrumpet** [eopeter/flutter_mapbox_navigation#246]
@eopeter Try to build on iOS and then do 'Start A to B' ... it will crash with `MapboxDirections/Directions.swift:561: Fatal error: waypoints array requires at least 2 waypoints`.

Do you have any hint why?

I think this package needs also tests to run on every PR

**Comment by marcotrumpet** [comment]
I think this is the issue @eopeter https://github.com/marcotrumpet/flutter_mapbox_navigation/commit/77b4b979e0d9d44f77f33ee5a9fd253484acd058#diff-4ab32d19b3ce4f8a531e8e6aab590444aa1606650cf2c90243998f1cc1980e6eR205

**Comment by eopeter** [comment]
Looking into this now. I see what you mean and nice catch. Yes, the library needs more unit tests and tests should run on every commit

**Comment by eopeter** [comment]
#248 fixes it; please take a look and approve

**Comment by marcotrumpet** [comment]
> #248 fixes it; please take a look and approve

done thanks
