### ISSUE TITLE
No Callback if user cancel the navigation.

### ISSUE THREAD

**Issue by Malik056** [eopeter/flutter_mapbox_navigation#25]
After starting the navigation, according to documentation, through startNavigation Function, there is no way or call back to check if user has canceled the navigation. Please provide a callback,

Thanks,
Muhammad Taha

**Comment by eopeter** [comment]
this is possible in the current version

**Comment by Malik056** [comment]
Okay great! But I am using version 0.0.10 which is the current version and it is working fine on IOS but not on Android.

**Comment by Reprevise** [comment]
How do you do the callback?
