### ISSUE TITLE
please make this plugin compatible with mapbox_gl in android

### ISSUE THREAD

**Issue by Hi99simon** [eopeter/flutter_mapbox_navigation#254]
I know that mapbox_gl is not updated for long time, but we need to use it for map feature.
however, when mapbox_gl and this flutter_mapbox_navigation plugin used together, in android, always crash, duplicate class, unable to work.

**Comment by eopeter** [comment]
@Hi99simon  Does this help you? https://stackoverflow.com/questions/67277228/android-build-gradle-exclude-duplicate-classes
