### ISSUE TITLE
iOS Embedded Clear Route Issue

### ISSUE THREAD

**Issue by neildunlop** [eopeter/flutter_mapbox_navigation#256]
I'm not 100% sure the clear route method is working correctly on iOS.

Basic steps to reproduce:

1. Build a route (we'll call this route A) - The route is previewed on the map.
2. Clear the route  (the route line is removed but stop markers persist).
3. Build a different route (we'll call this route B) - The route for route A and route B are shown on the map.

It doesn't seem to be an issue with Android.  

Has anyone seen anything similar?  I'm still investigating.

**Comment by mckeny3** [comment]
yeah i notice it too

**Comment by marcotrumpet** [comment]
looks like an issue that I solved here https://github.com/eopeter/flutter_mapbox_navigation/pull/284 .. basically also the clearRoute method miss the same _waypoints.removeAll() @eopeter
