### ISSUE TITLE
MapBoxNavigationMode.cycling does not work

### ISSUE THREAD

**Issue by bravo202305** [eopeter/flutter_mapbox_navigation#257]
Hi, We are testing your plugin and set the mode to cycling or walking. It is always taking as drivingwithtraffic. Upon reviewing the android code, it seems the option passed from Flutter widget is not being set. After updating the Utility.kt file as below, we are able to get it working. Can you take a quick look and see if you can update the code in the next release? 

Other than this, it is working great. We will provide feedback if anything additional we observe. 

private fun getRoute(context: Context) {
        MapboxNavigationApp.current()!!.requestRoutes(
                routeOptions = RouteOptions
                        .builder()
                        **.applyDefaultNavigationOptions(navigationMode)**
                        .applyLanguageAndVoiceUnitOptions(context)
                        .coordinatesList(addedWaypoints.coordinatesList())
                        .waypointIndicesList(addedWaypoints.waypointsIndices())
                        .waypointNamesList(addedWaypoints.waypointsNames())
                        .alternatives(true)
                        .build(),

**Comment by eopeter** [comment]
fixed with #261
