### ISSUE TITLE
Issues regarding MapBoxEvent.bannerInstruction never be called and Current Leg Value is Always null we get.

### ISSUE THREAD

**Issue by Akiitp** [eopeter/flutter_mapbox_navigation#258]
Hello, I am new in flutter, I want just Implements Turn by turn Navigation,  and get Value of Manuever and banner_instructions.
but in case we MapBoxEvent.banner_instructions this method never triggred.
Plz, Help,
Thank you in advance for your help!
this is Code.
Future<void> _onEmbeddedRouteEvent(e) async {
    _distanceRemaining = await MapBoxNavigation.instance.getDistanceRemaining();
    _durationRemaining = await MapBoxNavigation.instance.getDurationRemaining();
    double? nextTurnDistance;

    switch (e.eventType) {
      case MapBoxEvent.progress_change:
        var progressEvent = e.data as RouteProgressEvent;
        if (progressEvent.currentStepInstruction != null) {
          _instruction = progressEvent.currentStepInstruction;
          print("check Here: ${_previousPosition}");
          int index = findManeuverIndex(_previousPosition!.latitude, _previousPosition!.longitude, maneuver);
          print("check Here:111 ${maneuver.length}");
          String? modifires;
          if (index > 0) {
            modifires = maneuver[index].modifier;
          }
          if (!isArrived) {
            _sendMapData(_instruction, _distanceRemaining, nextTurnDistance, modifires);
          }
          else {
            if (_controller != null) {
              maneuver.clear();
              await _controller?.finishNavigation();
            }
          }
        }
        break;

      case MapBoxEvent.route_building:
      case MapBoxEvent.route_built:
        setState(() {
          _routeBuilt = true;
        });
        break;

      case MapBoxEvent.route_build_failed:
        setState(() {
          _routeBuilt = false;
        });
        break;

      case MapBoxEvent.navigation_running:
        setState(() {
          _isNavigating = true;
        });
        break;

      case MapBoxEvent.on_arrival:
        setState(() {
          isArrived = true;
          maneuver.clear();
        });
        if (_controller != null) {
          await _controller?.finishNavigation();
        }
        break;

      case MapBoxEvent.navigation_finished:
      case MapBoxEvent.navigation_cancelled:
        setState(() {
          _routeBuilt = false;
          _isNavigating = false;
          isArrived = false;
        });
        break;
      case MapBoxEvent.banner_instruction:
        bannerEvent = e.data;
        setState(() {});
        break;
      default:
        break;
    }

    setState(() {});
  }

**Comment by eopeter** [comment]
same as #254

**Comment by architp1112** [comment]
> Many of the events are returning null for me also. I am trying to listen to the user_off_route event, but the code isn't called when the user is off track, whereas the progress_change is still being logged.

any update on this issue? @eopeter @jonars99

**Comment by architp1112** [comment]
please give answer regarding this @eopeter

**Comment by eopeter** [comment]
Stale issue message

**Comment by jonars99** [comment]
are you looking into this @eopeter ?

**Comment by jonars99** [comment]
Was this ever resolved @eopeter ?

**Comment by eopeter** [comment]
if it is not resolved, please reopen
