### ISSUE TITLE
Show Waypoints Without Navigation

### ISSUE THREAD

**Issue by nnadir35** [eopeter/flutter_mapbox_navigation#263]
I have a waypoint list. I want to show it on the map without starting the navigation. I haven't seen this business code in the sample code or documentation. If possible, how can I do this?

**Comment by nnadir35** [comment]
I work on Android right now

**Comment by nnadir35** [comment]
If it is not possible can we contribute to repo ?

**Comment by eopeter** [comment]
Yes. Please send PR

**Comment by eopeter** [comment]
The embedded Nav view shows the route preview on Build Route but does not return the waypoints. Will be ideal for the Build Route function to return the waypoints if that route that was built

**Comment by nnadir35** [comment]
I also need waypoint when I don't define any route (other packages and official doc say it's an annotation). In this way, the user can select a specific place by long pressing, also the user can see certain places that I have defined beforehand and define a rotational navigation to these markers. As far as I understand, in order to do this job, I need to create a new branch from this repo and write the code to provide this job, is it true?

**Comment by eopeter** [comment]
You will fork the repo and create a branch on the fork for the change. Then do a PR when done. The current design has long press to select location.

**Comment by nnadir35** [comment]
> The embedded Nav view shows the route preview on Build Route but does not return the waypoints. Will be ideal for the Build Route function to return the waypoints if that route that was built

Thanks for your feedback, sorry for one last question. I want insert all waypoints dynamically (these are called from API) when page initialized and these waypoints seem on map without any defined route. Is this feature suitable for current design ?

**Comment by eopeter** [comment]
Stale issue message
