### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by marciotisouza** [eopeter/flutter_mapbox_navigation#265]
when running the pod install is giving this error:

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "MapboxMaps":
  In Podfile:
    flutter_mapbox_navigation (from `.symlinks/plugins/flutter_mapbox_navigation/ios`) was resolved to 0.1.0, which depends on
      MapboxNavigation (~> 2.11) was resolved to 2.11.0, which depends on
        MapboxMaps (~> 10.11.1)

    mapbox_maps_flutter (from `.symlinks/plugins/mapbox_maps_flutter/ios`) was resolved to 0.4.3, which depends on
      MapboxMaps (~> 10.10.0)

flutter_mapbox_navigation: ^0.1.8
mac os monterey 12.6
flutter 3.10.2
Dart 3.0.2

**Comment by eopeter** [comment]
Try pods update

**Comment by marciotisouza** [comment]
the problem persists!

Update all pods
Updating local specs repositories

CocoaPods 1.12.1 is available.
To update use: `sudo gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.12.1

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "MapboxMaps":
  In Podfile:
    flutter_mapbox_navigation (from `.symlinks/plugins/flutter_mapbox_navigation/ios`) was resolved to 0.1.0, which depends on
      MapboxNavigation (~> 2.11) was resolved to 2.11.0, which depends on
        MapboxMaps (~> 10.11.1)

    mapbox_maps_flutter (from `.symlinks/plugins/mapbox_maps_flutter/ios`) was resolved to 0.4.3, which depends on
      MapboxMaps (~> 10.10.0)

**Comment by eopeter** [comment]
You are using mapbox_maps_flutter, seems there is a dependency conflict between that and the navigation plugin

**Comment by marciotisouza** [comment]
I updated to
flutter 3.10.5
mapbox_maps_flutter: ^0.4.4

is passing in the update pod, but sending a warning:

Updating spec repo `trunk`
Analyzing dependencies
Downloading dependencies
Installing DKImagePickerController (4.3.4)
Installing DKPhotoGallery (0.0.17)
Installing FMDB (2.7.5)
Installing Flutter (1.0.0)
Installing Mantle (2.2.0)
Installing MapboxCommon (23.5.0)
Installing MapboxCoreMaps (10.13.1)
Installing MapboxCoreNavigation (2.13.0)
Installing MapboxDirections (2.10.0)
Installing MapboxMaps (10.13.1)
Installing MapboxMobileEvents (1.0.10)
Installing MapboxNavigation (2.13.0)
Installing MapboxNavigationNative (132.2.0)
Installing MapboxSpeech (2.1.1)
Installing Polyline (5.1.0)
Installing ReachabilitySwift (5.0.0)
Installing SDWebImage (5.16.0)
Installing SDWebImageWebPCoder (0.12.0)
Installing Solar-dev (3.0.1)
Installing SwiftyGif (5.4.4)
Installing Turf (2.6.1)
Installing app_tracking_transparency (0.0.1)
Installing audioplayers_darwin (0.0.1)
Installing background_location (0.0.1)
Installing camera_avfoundation (0.0.1)
Installing connectivity_plus (0.0.1)
Installing device_info_plus (0.0.1)
Installing file_picker (0.0.1)
Installing flutter_app_minimizer (0.0.1)
Installing flutter_image_compress_common (1.0.0)
Installing flutter_isolate (0.0.1)
Installing flutter_local_notifications (0.0.1)
Installing flutter_mapbox_navigation (0.1.0)
Installing geolocator_apple (1.2.0)
Installing image_picker_ios (0.0.1)
Installing libwebp (1.2.4)
Installing mapbox_maps_flutter (0.4.4)
Installing open_settings (0.0.1)
Installing package_info_plus (0.4.5)
Installing path_provider_foundation (0.0.1)
Installing permission_handler_apple (9.0.4)
Installing shared_preferences_foundation (0.0.1)
Installing sqlite (0.0.3)
Installing url_launcher_ios (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 23 dependencies from the Podfile and 44 total pods installed.

[!] The `Runner [Debug]` target overrides the `EXCLUDED_ARCHS[sdk=iphonesimulator*]` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig'. This can lead to problems with the CocoaPods installation
     - Use the `$(inherited)` flag, or
     - Remove the build settings from the target.

[!] The `Runner [Release]` target overrides the `EXCLUDED_ARCHS[sdk=iphonesimulator*]` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig'. This can lead to problems with the CocoaPods installation
     - Use the `$(inherited)` flag, or
     - Remove the build settings from the target.

[!] The `Runner [Profile]` target overrides the `EXCLUDED_ARCHS[sdk=iphonesimulator*]` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig'. This can lead to problems with the CocoaPods installation
     - Use the `$(inherited)` flag, or
     - Remove the build settings from the target.

**Comment by marciotisouza** [comment]
Generated the file for the Apple Store, any idea how to eliminate this alerts?

**Comment by eopeter** [comment]
Not off the top of my head
