### ISSUE TITLE
Map Widget Customization

### ISSUE THREAD

**Issue by jeremiahseun** [eopeter/flutter_mapbox_navigation#270]
So I want to ask if it is possible to add and remove custom widgets, depending on your use case and app preference.

**Comment by jeremiahseun** [comment]
![Screenshot_1687427908](https://github.com/eopeter/flutter_mapbox_navigation/assets/53568423/998bb728-df9a-4b81-b0f0-6ba662b83071)
The bottom side that shows the duration and the start trip button
![Screenshot_1687427932](https://github.com/eopeter/flutter_mapbox_navigation/assets/53568423/b9c2925f-fa5b-4833-82d3-c56ee913c920)

**Comment by eopeter** [comment]
Not at the moment but this is a popular request that could get worked on soon when there is bandwidth.

**Comment by jeremiahseun** [comment]
I need to understand what you mean by bandwidth. You mean a lot of requests? 🥲

**Comment by eopeter** [comment]
Yes, I meant the time to work on it. We all have full time jobs and doing this in free time. You can send a PR if you can enable the feature quickly

**Comment by jeremiahseun** [comment]
Alright.

Thank you for your quick response

**Comment by jeremiahseun** [comment]
Yeah! So I have a question about the location. Because I noticed that it only takes in the initialLocation of the user. Does it mean it doesn't change when the user changes location?

Like, when I open the map and I set my initial location, will it change as I move or it will remain in that location that has been set initially?

Thank you

**Comment by neildunlop** [comment]
It updates as you move.  Give the example a try. Update your phone location
in the emulator and things will update.

**Comment by mckeny3** [comment]
you can just use a a container to hide that area of the map...and add your own stuff there...use like a river pod state management to control the map base on the differnt event

**Comment by jeremiahseun** [comment]
Awesome.

I will be willing to work on the customization together with others. I am interested in learning how to go about it.

**Comment by mckeny3** [comment]
`class HomePage extends HookConsumerWidget {
  const HomePage({super.key});
  static const String routeName = "homepage";
  static const String routePath = "/";

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return ref.watch(userDataProvider).when(
          data: (DriverModel? currentUser) {
            if (currentUser != null) {
              return ref.watch(driverLocationProvider(context)).when(
                    data: (Position? driverLocation) {
                      return ref.watch(RidesStreamProvider).when(
                            data: (List<RideModel> rides) {
                              return ref
                                  .watch(currentRideStreamProvider(
                                      currentUser.uid!))
                                  .when(
                                    data: (RideModel? currentRide) {
                                      final navigationState =
                                          ref.watch(navigationProvider);
                                      final rideNotifier = ref.watch(
                                          RidesControllerProvider.notifier);
                                      final navigationNotifier = ref
                                          .watch(navigationProvider.notifier);
                                      log(currentRide?.status ??
                                          "no current ride");

                                      ///USE EFFECT
                                      useEffect(() {
                                        if (currentRide != null) {
                                          Future.delayed(
                                              const Duration(seconds: 1),
                                              () async {
                                            final origin = WayPoint(
                                                name: "origin",
                                                latitude: currentRide
                                                    .origin.coords.latitude,
                                                longitude: currentRide
                                                    .origin.coords.longitude,
                                                isSilent: false);
                                            final destination = WayPoint(
                                                name: "destination",
                                                latitude: currentRide
                                                    .destination
                                                    .coords
                                                    .latitude,
                                                longitude: currentRide
                                                    .destination
                                                    .coords
                                                    .longitude,
                                                isSilent: false);
                                            final driverLoca = WayPoint(
                                                name: "driver",
                                                latitude:
                                                    driverLocation!.latitude,
                                                longitude:
                                                    driverLocation.longitude,
                                                isSilent: false);

                                            if (currentRide.status ==
                                                RideStatus.accepted) {
                                              //=======>accepted
                                              if (navigationState.routeBuilt ==
                                                  false) {
                                                log("building route from home page");
                                                List<WayPoint> wayPoints = [];
                                                wayPoints.add(driverLoca);
                                                wayPoints.add(origin);

                                                navigationNotifier
                                                    .buildRoute(wayPoints);
                                              }
                                            } else if (currentRide.status ==
                                                RideStatus.toPickup) {
                                              //=======>to pickup
                                              ///if not navigating to pickup then navigate to pickup

                                              ////first check if there is a route built
                                              if (navigationState.routeBuilt ==
                                                  false) {
                                                //no route built..so build route
                                                List<WayPoint> wayPoints = [];
                                                wayPoints.add(driverLoca);
                                                wayPoints.add(origin);

                                                navigationNotifier
                                                    .buildRoute(wayPoints);
                                              }
                                            } else if (currentRide.status ==
                                                RideStatus.atPickup) {
                                              //=======>at pickup
                                              ///clear route then build new route

                                              navigationState.controller
                                                  ?.finishNavigation();
                                            } else if (currentRide.status ==
                                                RideStatus.cancelled) {
                                              log("cancelled ...so lets end navigation");

                                              navigationState.controller
                                                  ?.finishNavigation();
                                            } else if (currentRide.status ==
                                                RideStatus.completed) {
                                              log("completed ...so lets end navigation");
                                              navigationState.controller
                                                  ?.finishNavigation();
                                            } else if (currentRide.status ==
                                                RideStatus.toDestination) {
                                              //=======>to destination
                                              ///first check if there is a route built
                                              if (navigationState.routeBuilt ==
                                                  false) {
                                                //no route built..so build route
                                                List<WayPoint> wayPoints = [];
                                                wayPoints.add(driverLoca);
                                                wayPoints.add(destination);

                                                navigationNotifier
                                                    .buildRoute(wayPoints);
                                              }
                                            } else if (currentRide.status ==
                                                RideStatus.atDestination) {
                                              //=======>at destination
                                              ///clear route then build new route

                                              navigationState.controller
                                                  ?.finishNavigation();
                                            }
                                          });
                                        }
                                      }, [currentRide?.status]);
                                      return Scaffold(
                                          backgroundColor: Colors.transparent,
                                          extendBodyBehindAppBar: true,
                                          appBar: currentRide == null
                                              ? const HomePageAppBar()
                                              : null,
                                          drawer: const HomePageDrawer(),
                                          body: Stack(
                                            children: [
                       
                                              SizedBox(
                                                height: AppConst.kHieght * 0.80,
                                                width: AppConst.kwidth,
                                                child: const Navigation(),
                                              ),
                                              DraggableScrollableSheet(
                                                  snapSizes: const [
                                                    0.20,
                                                    0.50,
                                                    0.80
                                                  ],
                                                  expand: true,
                                                  snap: true,
                                                  initialChildSize:
                                                      0.20, //set this as you want
                                                  maxChildSize: 0.80,
                                                  minChildSize: 0.20,
                                                  builder: (BuildContext
                                                          context,
                                                      ScrollController
                                                          scrollController) {
                                                    return Container(
                                                      color: context
                                                          .colors.background,
                                                      child: ListView.builder(
                                                        padding:
                                                            EdgeInsets.zero,
                                                        controller:
                                                            scrollController,
                                                        itemCount: 1,
                                                        itemBuilder:
                                                            (BuildContext
                                                                    context,
                                                                int index) {
                                                          return Container(
                                                            height: AppConst
                                                                .kHieght,
                                                            child: Column(
                                                                children: [
                                                                  if (currentRide !=
                                                                      null)
                                                                    PreviewAcceptRide(
                                                                        currentRide)
                                                                  else if (rides
                                                                          .isNotEmpty &&
                                                                      currentRide ==
                                                                          null)
                                                                    RideInfoCard(
                                                                        ride: rides
                                                                            .first,
                                                                        driverLocation:
                                                                            driverLocation!,
                                                                        currentUser:
                                                                            currentUser)
                                                                  else
                                                                    PreviewNoRide(
                                                                        currentUser)
                                                                ]),
                                                          );
                                                        },
                                                      ),
                                                    );
                                                  }),
                                            ],
                                          ));

                                      ///////////
                                    },
                                    loading: () => const LoadingScreen(
                                      title: "...checking for rides",
                                    ),
                                    error: (e, st) =>
                                        ErrorPage(error: e.toString()),
                                  );
                            },
                            loading: () => const LoadingScreen(
                              title: "...checking for rides",
                            ),
                            error: (e, st) => ErrorPage(error: st.toString()),
                          );
                    },
                    loading: () => const LoadingScreen(
                      title: "Getting location...",
                    ),
                    error: (e, st) => ErrorPage(error: e.toString()),
                  );
            } else {
              throw Exception(
                  'User data is not available or not a DriverModel');
            }
          },
          loading: () => const LoadingScreen(
            title: "Getting user data...",
          ),
          error: (e, st) => ErrorPage(error: e.toString()),
        );
  }
}`

**Comment by jeremiahseun** [comment]
Thank you
