### ISSUE TITLE
El método startNavigation no encontrado por el sistema

### ISSUE THREAD

**Issue by emanuel-cc** [eopeter/flutter_mapbox_navigation#28]
Buenas tardes, hay un problema en el plugin, cuando compila la aplicación, e inicias la navegación con el plugin, cuando invocas el método startNavigation, flutter dice que no encuentra dicho método en el canal de plataforma

**Comment by eopeter** [comment]
What version of Flutter are you using? If not latest, try upgrading your project.

**Comment by emanuel-cc** [comment]
Es Flutter 1.12.13+hotfix.8

**Comment by eopeter** [comment]
Should be resolved in the latest version
