### ISSUE TITLE
java.lang.NullPointerException: Missing required view with ID: com.mckenytech.swyfio_driver:id/maneuverView

### ISSUE THREAD

**Issue by mckeny3** [eopeter/flutter_mapbox_navigation#280]
sometime the navigation runs smooth...then the second or third time as soon as you hit navigate ,it crashes...this is in embedded view...here is more logs `E/Mapbox  (17061): Using an empty fallback padding instead: [top: 586.0, left: 175.0, bottom: 669.0, right: 175.0]
E/Mapbox  (17061): [maps-core]: {h.swyfio_driver}[General]: Unable to calculate accurate zoom level for camera: the principal point is outside of the framing box.
E/Mapbox  (17061): [maps-core]: {h.swyfio_driver}[General]: Unable to calculate appropriate zoom level for bounds. Vertical or horizontal padding is greater than map's height or width.
E/Mapbox  (17061): [maps-core]: {h.swyfio_driver}[General]: Unable to calculate accurate zoom level for camera: the principal point is outside of the framing box.
E/Mapbox  (17061): [maps-core]: {h.swyfio_driver}[General]: Unable to calculate appropriate zoom level for bounds. Vertical or horizontal padding is greater than map's height or width.
E/AndroidRuntime(17061): FATAL EXCEPTION: main
E/AndroidRuntime(17061): Process: com.mckenytech.swyfio_driver, PID: 17061
E/AndroidRuntime(17061): java.lang.NullPointerException: Missing required view with ID: com.mckenytech.swyfio_driver:id/maneuverView
E/AndroidRuntime(17061): 	at com.mapbox.navigation.dropin.databinding.MapboxManeuverGuidanceLayoutBinding.bind(MapboxManeuverGuidanceLayoutBinding.java:60)
E/AndroidRuntime(17061): 	at com.mapbox.navigation.dropin.maneuver.ManeuverViewBinder.bind(ManeuverViewBinder.kt:27)
E/AndroidRuntime(17061): 	at com.mapbox.navigation.dropin.maneuver.ManeuverViewBinder.bind(ManeuverViewBinder.kt:16)
E/AndroidRuntime(17061): 	at com.mapbox.navigation.ui.base.lifecycle.UICoordinator$onAttached$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:136)
E/AndroidRuntime(17061): 	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invokeSuspend(Zip.kt:333)
E/AndroidRuntime(17061): 	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invoke(Unknown Source:13)
E/AndroidRuntime(17061): 	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invoke(Unknown Source:6)
E/AndroidRuntime(17061): 	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:79)
E/AndroidRuntime(17061): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(17061): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(17061): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(17061): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(17061): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(17061): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(17061): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(17061): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17061): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(17061): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(17061): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@938b30a, Dispatchers.Main]
I/Process (17061): Sending signal. PID: 17061 SIG: 9
Lost connection to device.

Exited.`

**Comment by rkreager** [comment]
Same issue here. 2nd or 3rd routing will cause the crash every time.

How to reproduce:

1. Build route and start navigation. 
2. Stop navigation.
3. Unload Widget that includes map.
4. Load widget.
5. Build route and start navigation. 
6. May need to do 3-5 again for crash.

`E/AndroidRuntime(28909): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(28909): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(28909): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(28909): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/AndroidRuntime(28909): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28909): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(28909): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/AndroidRuntime(28909): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@41982b8, Dispatchers.Main]`

**Comment by mckeny3** [comment]
Yeah...i have to be using map launcher now....I end up switching from react native,because I thought mapbox navigation was working with no prob....at this point am willing to pay someone to solve it,because I don't like the idea of driver  exiting the app

**Comment by mckeny3** [comment]
so...i went back and try something new....by clearing the route...ending the navigation manually....also, because am testing ,i used like a mock location...so i notice if your starting point/mock/device location  doest change when your about to start a second trip thats when it crash......`
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        ElevatedButton(
                          onPressed: _isNavigating
                              ? null
                              : () {
                                  if (_routeBuilt) {
                                    _controller?.clearRoute();
                                  } else {
                                    var wayPoints = <WayPoint>[];
                                    // wayPoints.add(_home);
                                    // wayPoints.add(_store);

                                    if (widget.currentRideStatus.status ==
                                        RideStatus.toPickup) {
                                      //clear route and finish navigation just to be sure
                                      _controller?.clearRoute();
                                      _controller?.finishNavigation();
                                      final ori = WayPoint(
                                          name: "origin",
                                          latitude: widget
                                              .driverLocationStream.latitude,
                                          longitude: widget
                                              .driverLocationStream.longitude,
                                          isSilent: false);
                                      wayPoints.add(ori);

                                      wayPoints.add(widget.origin);
                                    } else if (widget
                                            .currentRideStatus.status ==
                                        RideStatus.toDestination) {
                                      _controller?.clearRoute();
                                      _controller?.finishNavigation();
                                      final ori = WayPoint(
                                          name: "origin",
                                          latitude: widget
                                              .driverLocationStream.latitude,
                                          longitude: widget
                                              .driverLocationStream.longitude,
                                          isSilent: false);
                                      wayPoints.add(ori);
                                      wayPoints.add(widget.destination);
                                    }

                                    //build route

                                    _isMultipleStop = wayPoints.length > 2;
                                    _controller?.buildRoute(
                                        wayPoints: wayPoints,
                                        options: _navigationOption);
                                  }
                                },
                          child: Text(_routeBuilt && !_isNavigating
                              ? "Clear Route"
                              : widget.buildTitle),
                        ),
                        const SizedBox(
                          width: 10,
                        ),
                        ElevatedButton(
                          onPressed: _routeBuilt && !_isNavigating
                              ? () {
                                  _controller?.startNavigation();
                                }
                              : null,
                          child: const Text('Start '),
                        ),`

**Comment by josephcrowell** [comment]
I eneded up making my own plugin, rewriting everything from scratch: https://github.com/ComputerlinkAU/flutter_mapbox_turn_by_turn because of issues in this one. One thing I haven't been able to solve though is that there's a memory leak, something isn't destroyed properly in Mapbox when you don't use a standard Android lifecycle. Haven't been able to track down what exactly. The issue is buried somewhere in the private classes of Mapbox's code.

**Comment by mckeny3** [comment]
Did you find out what's causes the second to 3rd navigation to crash on this plug-in?

**Comment by mckeny3** [comment]
i just realized  i forked your repo like an hour ago...i did notice that it  causes error if i hot reload it...if i stop and rebuild, its ok...`
W/Mapbox  (20166): [maps-android\Mbgl-MapboxMap]: MapboxMap object (accessing setUserAnimationInProgress) should not be stored and used after MapView is destroyed.
W/Mapbox  (20166): [maps-android\Mbgl-MapboxMap]: MapboxMap object (accessing setCamera) should not be stored and used after MapView is destroyed.
W/Mapbox  (20166): [maps-android\Mbgl-MapboxMap]: MapboxMap object (accessing cameraState) should not be stored and used after MapView is destroyed.
2
W/Mapbox  (20166): [maps-android\Mbgl-MapboxMap]: MapboxMap object (accessing setUserAnimationInProgress) should not be stored and used after MapView is destroyed.
59
W/Mapbox  (20166): [maps-android\Mbgl-MapboxMap]: MapboxMap object (accessing setCamera) should not be stored and used after MapView is destroyed.
W/Mapbox  (20166): [maps-android\Mbgl-MapboxMap]: MapboxMap object (accessing setUserAnimationInProgress) should not be stored and used after MapView is destroyed.
W/Mapbox  (20166): [maps-android\Mbgl-MapboxMap]: MapboxMap object (accessing setCamera) should not be stored and used after MapView is destroyed.
D/TrafficStats(20166): tagSocket(130) with statsTag=0xffffffff, statsUid=-1
E/flutter (20166): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: MapboxNavigation cannot be null. Ensure that MapboxNavigationApp is setup and an attached lifecycle is at least CREATED.
E/flutter (20166): 	at com.mapbox.navigation.core.lifecycle.RequireMapboxNavigationDelegate.getValue(RequireMapboxNavigation.kt:132)
E/flutter (20166): 	at com.mapbox.navigation.core.lifecycle.RequireMapboxNavigationDelegate.getValue(RequireMapboxNavigation.kt:83)
E/flutter (20166): 	at au.com.annon.flutter_mapbox_turn_by_turn.ui.TurnByTurnNative.getMapboxNavigation(TurnByTurnNative.kt:224)
E/flutter (20166): 	at au.com.annon.flutter_mapbox_turn_by_turn.ui.TurnByTurnNative.registerObservers(TurnByTurnNative.kt:871)
E/flutter (20166): 	at au.com.annon.flutter_mapbox_turn_by_turn.ui.TurnByTurnNative.initializeMapbox(TurnByTurnNative.kt:848)
E/flutter (20166): 	at au.com.annon.flutter_mapbox_turn_by_turn.ui.TurnByTurnView.<init>(TurnByTurnView.kt:28)
E/flutter (20166): 	at au.com.annon.flutter_mapbox_turn_by_turn.ui.TurnByTurnViewFactory.create(TurnByTurnViewFactory.kt:22)
E/flutter (20166): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:503)
E/flutter (20166): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:163)
E/flutter (20166): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:105)
E/flutter (20166): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
E/flutter (20166): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (20166): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (20166): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (20166): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (20166): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (20166): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (20166): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (20166): 	at android.os.Looper.loop(Looper.java:288)
`

**Comment by josephcrowell** [comment]
That's due to the memory leak. Something isn't deinitialized and everything breaks when init is run on that already initted thing. No trace log as to what exactly though.

**Comment by mckeny3** [comment]
did you manage to fix it?

**Comment by josephcrowell** [comment]
No. Feel free to try youself if you want. You'll Need to fork the Mapbox Navigation Android repos (and probably the other Mapbox dependencies).

**Comment by maicojay16** [comment]
did you manage to fix it ? @mckeny3 

I also got the same problem when using the navigation. Mine works fine in the first run, But after that when i try to navigate again the app crash.

I already tried to clear the route and dispose the screen but same problem exist.

![image](https://github.com/eopeter/flutter_mapbox_navigation/assets/23121374/cfee3022-63f7-4feb-9d4d-44775481d597)

**Comment by maicojay16** [comment]
Hello @eopeter is there any updates for this kind of errors ? Thanks.

**Comment by eopeter** [comment]
is this issue still happening with the current version 0.2.0?

**Comment by maicojay16** [comment]
@eopeter  i will try the new version 0.2.0 and will give a feedback thanks for the response.

**Comment by ChunYunWong-edag-my** [comment]
problem still exist with version 0.2.2
