### ISSUE TITLE
longPressDestinationEnabled flag does not work

### ISSUE THREAD

**Issue by bravo202305** [eopeter/flutter_mapbox_navigation#281]
Hi, When we set longPressDestinationEnabled to false in the navigationOptions, it is not recognized in the EmbeddedNavigationMapView. After adding the following code locally, it works. 

Can you please take a look at the following code update when you get a chance, add it to the plugin code if you feel appropriate?

### android/src/main/kotlin/com/eopeter/fluttermapboxnavigation/models/views/EmbeddedNavigationMapView.kt

    open fun initialize() {
        initFlutterChannelHandlers()
        initNavigation()

        // **************** if long press is disabled START **************************//
        if(!(this.args["longPressDestinationEnabled"] as Boolean)) {
            this.binding.navigationView.customizeViewOptions {
                enableMapLongClickIntercept = false;
            }
        }
        // **************** if long press is START disabled **************************//
    }

**Comment by eopeter** [comment]
Thanks for this, Applied to latest code
