### ISSUE TITLE
Conflict Between Mapbox Navigation and Mapbox GL

### ISSUE THREAD

**Issue by Yaziidbsr** [eopeter/flutter_mapbox_navigation#286]
Hi,

I am developing a Flutter application where I intend to use both the Mapbox Navigation and Mapbox GL plugins. However, I am encountering a conflict between the two.

Could you provide any guidance or potential solutions to address this issue?

Thanks in advance for your help.

### This is the Error:

[!] CocoaPods could not find compatible versions for pod "Mapbox-iOS-SDK":
  In Podfile:
    mapbox_gl (from `.symlinks/plugins/mapbox_gl/ios`) was resolved to 0.0.1, which depends on
      Mapbox-iOS-SDK (~> 6.4.0)

    mapbox_gl (from `.symlinks/plugins/mapbox_gl/ios`) was resolved to 0.0.1, which depends on
      MapboxAnnotationExtension (~> 0.0.1-beta.1) was resolved to 0.0.1-beta.2, which depends on
        Mapbox-iOS-SDK (~> 6.0)

CocoaPods could not find compatible versions for pod "MapboxMobileEvents":
  In Podfile:
    flutter_mapbox_navigation (from `.symlinks/plugins/flutter_mapbox_navigation/ios`) was resolved to 0.1.0, which depends on
      MapboxCoreNavigation (~> 2.11) was resolved to 2.14.0, which depends on
        MapboxMobileEvents (~> 1.0)

    mapbox_gl (from `.symlinks/plugins/mapbox_gl/ios`) was resolved to 0.0.1, which depends on
      Mapbox-iOS-SDK (~> 6.4.0) was resolved to 6.4.0, which depends on
        MapboxMobileEvents (~> 0.10.11)

**Comment by samderlust** [comment]
How did you solve this?
