### ISSUE TITLE
Route Events not arriving anymore

### ISSUE THREAD

**Issue by marcotrumpet** [eopeter/flutter_mapbox_navigation#287]
following this https://github.com/eopeter/flutter_mapbox_navigation/blob/master/lib/src/embedded/controller.dart#L141C7-L141C7 the package calls '_routeEventSubscription.cancel()' when an 'on_arrival' event is forwarded from native. The problem is that native sends 'on_arrival' when the user reaches a waypoint, not only the end of the navigation. 

PROBLEM:
Every other event is lost because of that.

SOLUTION
@eopeter my suggestion is to expose the subscription deletion to the app so we can call it when disposing of the specific page.

**Comment by marcotrumpet** [comment]
I propose a fix

**Comment by eopeter** [comment]
This is resolved with the PR and published in v0.1.9
