### ISSUE TITLE
Is it possible to pass json instructions from 3d party service instead of waypoints

### ISSUE THREAD

**Issue by artemsorochan** [eopeter/flutter_mapbox_navigation#293]
Is it possible to pass json instructions from 3d party service instead of waypoints(compatible with mapbox)

Earlier it was possible via mapboxNavigation.setRoutes(DirectionsRoute.fromJson(json))

Now FlutterMapboxNavigationPlugin.kt doesn't have mapboxNavigation

Thanks in advance!

**Comment by eopeter** [comment]
We had a PR for this feature that never merged in. Will need to look into why

**Comment by eopeter** [comment]
Stale issue message
