### ISSUE TITLE
Navigation Screen not closing after cancelled on Android

### ISSUE THREAD

**Issue by AlanGood113** [eopeter/flutter_mapbox_navigation#294]
When I press the cancel button on Android Navigation, it stops the navigation but it stays on the navigation screen. How do i fix this? Everything works fine on iOS.

**Comment by eopeter** [comment]
@AlanGood113 I see this is the issue you are referring to in #299 . Lets merge to track under one ticket

**Comment by AlanGood113** [comment]
Okay. I’d like to go back to the previous page after navigation has been cancelled. When I press the cancel button on iOS, it goes back to the previous page. However, when I press it on android, it goes into a free drive mode where I have to press the back button on the android phone to get back to the previous screen. This causes leaks within the android app.

**Comment by AlanGood113** [comment]
I am following up on the above issue.

**Comment by eopeter** [comment]
this issue is resolved in the current version 0.2.0 of the plugin
