### ISSUE TITLE
Android marker missing

### ISSUE THREAD

**Issue by marcotrumpet** [eopeter/flutter_mapbox_navigation#295]
When build routes with EmbeddedView in android I'm not able to see markers for waypoints. I see circles with numbers in iOS.

**Comment by eopeter** [comment]
Did you have a PR for this? #292 does not sound like it resolves this issue

**Comment by eopeter** [comment]
Stale issue message

**Comment by InesRodAlo** [comment]
I'm having the same issue. When build routes with EmbeddedView in android I'm not able to see markers for waypoints. It doesn't matter if the waypoints _isSilent = true_ or not.
