### ISSUE TITLE
Icon color merges with button color

### ISSUE THREAD

**Issue by artemsorochan** [eopeter/flutter_mapbox_navigation#296]
Is there a way to set a custom color for icon button? on iOS the icon is not visible

![image](https://github.com/eopeter/flutter_mapbox_navigation/assets/116367489/e9b8e20e-cd96-4c8f-ab54-2138083dfb8b)
Thanks in advance!

**Comment by eopeter** [comment]
is this in dark mode?

**Comment by eopeter** [comment]
For the embedded view you could use your own icons

**Comment by artemsorochan** [comment]
It happens on both light/dark mode. Excuse me, I didn't find how to user my own icons, could you please give a reference?

**Comment by eopeter** [comment]
Stale issue message
