### ISSUE TITLE
startNavigation() MissingPluginException 

### ISSUE THREAD

**Issue by mohammed-habeb** [eopeter/flutter_mapbox_navigation#30]
I tried starting the navigation after following all the steps mentioned and I keep getting a missing plugin exception when I press "Start Navigation".  I am on Flutter 1.12.13+hotfix.8 and Dart 2.7.0.

This is my flutter doctor:

 [√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale
    en-GB)
    • Flutter version 1.12.13+hotfix.8 at C:\Users\moham\Documents\Flutter SDK\flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\moham\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Users\moham\Documents\Android Studio\Android SDK\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup      for detailed instructions.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\moham\Documents\Android Studio\Android SDK
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\moham\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • ONEPLUS A6013 • 55da0e0f • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.

**Comment by AnasSafi** [comment]
I faced same problem,

> E/flutter (31412): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method startNavigation on channel flutter_mapbox_navigation)
> E/flutter (31412): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)

The output of **flutter doctor -v output** command is:

> 
> [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
>     • Flutter version 1.12.13+hotfix.8 at /home/fahed/development/flutter
>     • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
>     • Engine revision e1e6ced81d
>     • Dart version 2.7.0
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at /home/fahed/Android/Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.3
>     • Java binary at: /snap/android-studio/84/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
>     • All Android licenses accepted.
> 
> [✓] Android Studio (version 3.6)
>     • Android Studio at /snap/android-studio/84/android-studio
>     • Flutter plugin version 44.0.2
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
> 
> [✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
>     • IntelliJ at /snap/intellij-idea-ultimate/204
>     • Flutter plugin version 41.1.5
>     • Dart plugin version 193.5233.116
> 
> [✓] Connected device (1 available)
>     • Mi 9T • fff367b4 • android-arm64 • Android 10 (API 29)
> 
> • No issues found!

**Note: No problems when test it on Iphone and XCode..**

**Comment by Malik056** [comment]
This issue is already open here #$13
