### ISSUE TITLE
Custom theming not working

### ISSUE THREAD

**Issue by jeremiahseun** [eopeter/flutter_mapbox_navigation#302]
I tried to make a change in the mapStyleUrl but it is not changing for Android:

``` 
mapStyleUrlDay: "mapbox://styles/jeremiahseun/cljydksei006e01pf6cqmc8qh",
mapStyleUrlNight: "mapbox://styles/jeremiahseun/cljydksei006e01pf6cqmc8qh",
```

Basically, I want to remove the dark mode since we are not implementing it yet in our app, but it is not changing.

**Comment by alexeileyvamora** [comment]
@jeremiahseun you can try making use of mapbox://styles/mapbox/streets-v12 or another style because I have tried with the style you provided and it doesn't load for me. Check the style in your mapbox account.

if mapStyleUrl Day or Night is null the corresponding style is loaded by default.

**Comment by jeremiahseun** [comment]
I just tested this URL you dropped and it is still bringing the dark mode map @alexeileyvamora.

The funny thing is that the map style loads well in iOS (both light and dark mode). Here is a screenshot

![simulator_screenshot_FB5B6871-ED2E-44C0-B5FC-D03B2368187A](https://github.com/eopeter/flutter_mapbox_navigation/assets/53568423/a12671c5-1c81-4d50-8236-54602e360132)

**Comment by alexeileyvamora** [comment]
@jeremiahseun check the package version if it is lower than the latest version then upgrade to the latest version.
