### ISSUE TITLE
Change Voice Gender

### ISSUE THREAD

**Issue by Muhammad-Dev720** [eopeter/flutter_mapbox_navigation#303]
How to change the gender of the voice instructions in navigation?

**Comment by eopeter** [comment]
we will need to add the option to change the gender.

**Comment by eopeter** [comment]
You can also turn off voice instructions using the option and the. Use the voice instructions listener to play the voice using your own speech engine.

**Comment by Aburafik** [comment]
Please how can i update a waypoint as user continue to move to the destination?. Your documentation is very helpful , but am still struggling to implement that feature.

**Comment by eopeter** [comment]
Stale issue message
