### ISSUE TITLE
How to auto start the guidance after startNavigation

### ISSUE THREAD

**Issue by rickylaw-dh** [eopeter/flutter_mapbox_navigation#309]
I am using v0.1.7 version

And I am using embedded view in my app.
However, the project scope needs to auto-start instead of clicking the "Button"

I have checked MapBox document
There is a function called "startTripSession"
https://docs.mapbox.com/android/navigation/api/2.10.4/libnavigation-core/com.mapbox.navigation.core/-mapbox-navigation/#-2077543249%2FFunctions%2F119003296

Do you know how I can use this plugin to invoke it? 

Thanks

**Comment by eopeter** [comment]
Are you experiencing the issue on Android or iOS or both?

**Comment by rickylaw-dh** [comment]
I do not test it on iOS since my project is mainly focusing on Android

**Comment by rickylaw-dh** [comment]
@eopeter, it is my mistake.
I checked my code and compared it with your example
The `startNavigation()` trigger point was wrong in my code ...
Sorry 🙏🏻
