### ISSUE TITLE
Error when starting Android project since v0.2.0 release

### ISSUE THREAD

**Issue by AlanGood113** [eopeter/flutter_mapbox_navigation#311]
FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':app:checkDebugAarMetadata'.

> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.

   > Failed to transform copilot-2.16.0.aar (com.mapbox.navigation:copilot:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download copilot-2.16.0.aar (com.mapbox.navigation:copilot:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/copilot/2.16.0/copilot-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/copilot/2.16.0/copilot-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform ui-dropin-2.16.0.aar (com.mapbox.navigation:ui-dropin:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download ui-dropin-2.16.0.aar (com.mapbox.navigation:ui-dropin:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-dropin/2.16.0/ui-dropin-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-dropin/2.16.0/ui-dropin-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform ui-app-2.16.0.aar (com.mapbox.navigation:ui-app:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download ui-app-2.16.0.aar (com.mapbox.navigation:ui-app:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-app/2.16.0/ui-app-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-app/2.16.0/ui-app-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform ui-voice-2.16.0.aar (com.mapbox.navigation:ui-voice:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download ui-voice-2.16.0.aar (com.mapbox.navigation:ui-voice:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-voice/2.16.0/ui-voice-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-voice/2.16.0/ui-voice-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform ui-maps-2.16.0.aar (com.mapbox.navigation:ui-maps:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download ui-maps-2.16.0.aar (com.mapbox.navigation:ui-maps:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-maps/2.16.0/ui-maps-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-maps/2.16.0/ui-maps-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform ui-speedlimit-2.16.0.aar (com.mapbox.navigation:ui-speedlimit:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download ui-speedlimit-2.16.0.aar (com.mapbox.navigation:ui-speedlimit:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-speedlimit/2.16.0/ui-speedlimit-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-speedlimit/2.16.0/ui-speedlimit-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform ui-tripprogress-2.16.0.aar (com.mapbox.navigation:ui-tripprogress:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download ui-tripprogress-2.16.0.aar (com.mapbox.navigation:ui-tripprogress:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-tripprogress/2.16.0/ui-tripprogress-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-tripprogress/2.16.0/ui-tripprogress-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform ui-maneuver-2.16.0.aar (com.mapbox.navigation:ui-maneuver:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download ui-speedlimit-2.16.0.aar (com.mapbox.navigation:ui-speedlimit:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-speedlimit/2.16.0/ui-speedlimit-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-speedlimit/2.16.0/ui-speedlimit-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform ui-tripprogress-2.16.0.aar (com.mapbox.navigation:ui-tripprogress:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download ui-tripprogress-2.16.0.aar (com.mapbox.navigation:ui-tripprogress:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-tripprogress/2.16.0/ui-tripprogress-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-tripprogress/2.16.0/ui-tripprogress-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform ui-maneuver-2.16.0.aar (com.mapbox.navigation:ui-maneuver:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download ui-maneuver-2.16.0.aar (com.mapbox.navigation:ui-maneuver:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-maneuver/2.16.0/ui-maneuver-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-maneuver/2.16.0/ui-maneuver-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform ui-shields-2.16.0.aar (com.mapbox.navigation:ui-shields:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download ui-shields-2.16.0.aar (com.mapbox.navigation:ui-shields:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-shields/2.16.0/ui-shields-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-shields/2.16.0/ui-shields-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform ui-base-2.16.0.aar (com.mapbox.navigation:ui-base:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download ui-base-2.16.0.aar (com.mapbox.navigation:ui-base:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-base/2.16.0/ui-base-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-base/2.16.0/ui-base-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform core-2.16.0.aar (com.mapbox.navigation:core:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download core-2.16.0.aar (com.mapbox.navigation:core:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/core/2.16.0/core-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/core/2.16.0/core-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform ui-utils-2.16.0.aar (com.mapbox.navigation:ui-utils:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download ui-utils-2.16.0.aar (com.mapbox.navigation:ui-utils:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-utils/2.16.0/ui-utils-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-utils/2.16.0/ui-utils-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform router-2.16.0.aar (com.mapbox.navigation:router:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download router-2.16.0.aar (com.mapbox.navigation:router:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/router/2.16.0/router-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/router/2.16.0/router-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform notification-2.16.0.aar (com.mapbox.navigation:notification:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download notification-2.16.0.aar (com.mapbox.navigation:notification:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/notification/2.16.0/notification-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/notification/2.16.0/notification-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform navigator-2.16.0.aar (com.mapbox.navigation:navigator:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download navigator-2.16.0.aar (com.mapbox.navigation:navigator:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/navigator/2.16.0/navigator-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/navigator/2.16.0/navigator-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform metrics-2.16.0.aar (com.mapbox.navigation:metrics:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download metrics-2.16.0.aar (com.mapbox.navigation:metrics:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/metrics/2.16.0/metrics-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/metrics/2.16.0/metrics-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform base-2.16.0.aar (com.mapbox.navigation:base:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download base-2.16.0.aar (com.mapbox.navigation:base:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/base/2.16.0/base-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/base/2.16.0/base-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform utils-2.16.0.aar (com.mapbox.navigation:utils:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download utils-2.16.0.aar (com.mapbox.navigation:utils:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/utils/2.16.0/utils-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/utils/2.16.0/utils-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform ui-resources-2.16.0.aar (com.mapbox.navigation:ui-resources:2.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download ui-resources-2.16.0.aar (com.mapbox.navigation:ui-resources:2.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-resources/2.16.0/ui-resources-2.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigation/ui-resources/2.16.0/ui-resources-2.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform android-10.16.0.aar (com.mapbox.maps:android:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download android-10.16.0.aar (com.mapbox.maps:android:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.16.0/android-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.16.0/android-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform maps-annotation-10.16.0.aar (com.mapbox.plugin:maps-annotation:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download maps-annotation-10.16.0.aar (com.mapbox.plugin:maps-annotation:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-annotation/10.16.0/maps-annotation-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-annotation/10.16.0/maps-annotation-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform maps-localization-10.16.0.aar (com.mapbox.extension:maps-localization:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download maps-localization-10.16.0.aar (com.mapbox.extension:maps-localization:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/extension/maps-localization/10.16.0/maps-localization-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/extension/maps-localization/10.16.0/maps-localization-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform maps-style-10.16.0.aar (com.mapbox.extension:maps-style:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download maps-style-10.16.0.aar (com.mapbox.extension:maps-style:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/extension/maps-style/10.16.0/maps-style-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/extension/maps-style/10.16.0/maps-style-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform maps-logo-10.16.0.aar (com.mapbox.plugin:maps-logo:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download maps-logo-10.16.0.aar (com.mapbox.plugin:maps-logo:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-logo/10.16.0/maps-logo-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-logo/10.16.0/maps-logo-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform maps-compass-10.16.0.aar (com.mapbox.plugin:maps-compass:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download maps-compass-10.16.0.aar (com.mapbox.plugin:maps-compass:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-compass/10.16.0/maps-compass-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-compass/10.16.0/maps-compass-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform maps-gestures-10.16.0.aar (com.mapbox.plugin:maps-gestures:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download maps-gestures-10.16.0.aar (com.mapbox.plugin:maps-gestures:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-gestures/10.16.0/maps-gestures-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-gestures/10.16.0/maps-gestures-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform maps-attribution-10.16.0.aar (com.mapbox.plugin:maps-attribution:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download maps-attribution-10.16.0.aar (com.mapbox.plugin:maps-attribution:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-attribution/10.16.0/maps-attribution-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-attribution/10.16.0/maps-attribution-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform maps-viewport-10.16.0.aar (com.mapbox.plugin:maps-viewport:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download maps-viewport-10.16.0.aar (com.mapbox.plugin:maps-viewport:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-viewport/10.16.0/maps-viewport-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-viewport/10.16.0/maps-viewport-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform maps-locationcomponent-10.16.0.aar (com.mapbox.plugin:maps-locationcomponent:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download maps-locationcomponent-10.16.0.aar (com.mapbox.plugin:maps-locationcomponent:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-locationcomponent/10.16.0/maps-locationcomponent-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-locationcomponent/10.16.0/maps-locationcomponent-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform maps-scalebar-10.16.0.aar (com.mapbox.plugin:maps-scalebar:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download maps-scalebar-10.16.0.aar (com.mapbox.plugin:maps-scalebar:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-scalebar/10.16.0/maps-scalebar-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-scalebar/10.16.0/maps-scalebar-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform maps-overlay-10.16.0.aar (com.mapbox.plugin:maps-overlay:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download maps-overlay-10.16.0.aar (com.mapbox.plugin:maps-overlay:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-overlay/10.16.0/maps-overlay-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-overlay/10.16.0/maps-overlay-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform mapbox-navigation-native-157.0.0.aar (com.mapbox.navigator:mapbox-navigation-native:157.0.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download mapbox-navigation-native-157.0.0.aar (com.mapbox.navigator:mapbox-navigation-native:157.0.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigator/mapbox-navigation-native/157.0.0/mapbox-navigation-native-157.0.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/navigator/mapbox-navigation-native/157.0.0/mapbox-navigation-native-157.0.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform okhttp-23.8.0.aar (com.mapbox.common:okhttp:23.8.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download okhttp-23.8.0.aar (com.mapbox.common:okhttp:23.8.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/common/okhttp/23.8.0/okhttp-23.8.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/common/okhttp/23.8.0/okhttp-23.8.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform maps-animation-10.16.0.aar (com.mapbox.plugin:maps-animation:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download maps-animation-10.16.0.aar (com.mapbox.plugin:maps-animation:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-animation/10.16.0/maps-animation-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-animation/10.16.0/maps-animation-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform maps-lifecycle-10.16.0.aar (com.mapbox.plugin:maps-lifecycle:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download maps-lifecycle-10.16.0.aar (com.mapbox.plugin:maps-lifecycle:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-lifecycle/10.16.0/maps-lifecycle-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/plugin/maps-lifecycle/10.16.0/maps-lifecycle-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform maps-telemetry-10.16.0.aar (com.mapbox.module:maps-telemetry:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download maps-telemetry-10.16.0.aar (com.mapbox.module:maps-telemetry:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/module/maps-telemetry/10.16.0/maps-telemetry-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/module/maps-telemetry/10.16.0/maps-telemetry-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform base-10.16.0.aar (com.mapbox.maps:base:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download base-10.16.0.aar (com.mapbox.maps:base:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/base/10.16.0/base-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/base/10.16.0/base-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform android-core-10.16.0.aar (com.mapbox.maps:android-core:10.16.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download android-core-10.16.0.aar (com.mapbox.maps:android-core:10.16.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android-core/10.16.0/android-core-10.16.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android-core/10.16.0/android-core-10.16.0.aar'. Received status code 401 from server: Unauthorized

   > Failed to transform common-23.8.0.aar (com.mapbox.common:common:23.8.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

      > Could not download common-23.8.0.aar (com.mapbox.common:common:23.8.0)

         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/common/common/23.8.0/common-23.8.0.aar'.

            > Could not HEAD 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/common/common/23.8.0/common-23.8.0.aar'. Received status code 401 from server: Unauthorized

* Try:

> Run with --stacktrace option to get the stack trace.

> Run with --info or --debug option to get more log output.

> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

[!] Gradle threw an error while downloading artifacts from the network.

Exception: Gradle task assembleDebug failed with exit code 1

**Comment by eopeter** [comment]
Please follow the README on how to setup your download token

**Comment by AlanGood113** [comment]
The android version works with the previous version: 0.1.9. However, when i update to 0.2.0 it gives those errors. I did not change anything for the token setups. I looked at the update changes for 0.2.0 and saw that you changed the version of the above packages from 2.10.4 to 2.16.0. I'm not sure if that is the reason for the error.

**Comment by eopeter** [comment]
Yes it's trying to download the updated MapBox sdk. Checking your download token on mapbox.com to make sure it is still valid.

**Comment by AlanGood113** [comment]
I just created a new secret token with the downloads:read property and it still gives the same error. The secret key for android is only added in the gradle.properties right?

**Comment by eopeter** [comment]
Based on the README:

Add the MapBox Downloads token with the downloads:read scope to your gradle.properties file in Android folder to enable downloading the MapBox binaries from the repository. To secure this token from getting checked into source control, you can add it to the gradle.properties of your GRADLE_HOME which is usually at $USER_HOME/.gradle for Mac. This token can be retrieved from your MapBox Dashboard. You can review the Token Guide to learn more about download tokens
MAPBOX_DOWNLOADS_TOKEN=sk.XXXXXXXXXXXXXXX

**Comment by AlanGood113** [comment]
Yes, I have done that. Using version 0.1.9, the project starts up perfectly, however using version 0.2.0 generates all those errors with a working Mapbox token and setup

**Comment by eopeter** [comment]
Are you still having this issue?

**Comment by AlanGood113** [comment]
No, I just tested it today and all is well. I didnt change anything to the code, perhaps it was a mapbox issue.
