### ISSUE TITLE
Library changes waypoints routes only on android for some reason

### ISSUE THREAD

**Issue by gonciuu** [eopeter/flutter_mapbox_navigation#319]
Hello,

I am using the `flutter_mapbox_navigation` package in my project and I've encountered an issue related to waypoint routing. Specifically, on iOS everything works as expected and the route is generated correctly. However, on Android, the route seems to be modified in an unexpected manner, even though the waypoints (dots on the map) appear correctly.

Additionally, when this problem occurs on Android, I see the following error in the console: `Failed to find address for point`.

It would be great if the behavior on Android could match that of iOS. Any help on this would be appreciated.

If you need a list of waypoints for testing, I'd be happy to provide them.

![Problem](https://i.imgur.com/3gIUjaS.png "A Problem")

Thank you!

**Comment by eopeter** [comment]
Stale issue message
