### ISSUE TITLE
 FATAL EXCEPTION: IncompatibleClassChangeError

### ISSUE THREAD

**Issue by tegaologe** [eopeter/flutter_mapbox_navigation#321]
Any help will be greatly appreciated.  Using latest version

E/AndroidRuntime(21762): FATAL EXCEPTION: main
E/AndroidRuntime(21762): Process: com.laprairie.lmsApp, PID: 21762
E/AndroidRuntime(21762): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.ActivityRecognitionClient, but class was expected (declaration of 'com.google.android.gms.location.ActivityRecognitionClient' appears in /data/app/~~8LIxSmLgDpCNUTY-v5rW9w==/com.laprairie.lmsApp-H_sLodmZA5gZ1eVAe4aNJw==/base.apk!classes20.dex)
E/AndroidRuntime(21762): 	at com.mapbox.common.movement.GoogleActivityRecognition.start(GoogleActivityRecognition.kt:115)
E/AndroidRuntime(21762): 	at com.mapbox.common.movement.AndroidMovementMonitor.registerObserver(AndroidMovementMonitor.kt:60)
E/AndroidRuntime(21842): FATAL EXCEPTION: main
E/AndroidRuntime(21842): Process: com.laprairie.lmsApp, PID: 21842
E/AndroidRuntime(21842): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.ActivityRecognitionClient, but class was expected (declaration of 'com.google.android.gms.location.ActivityRecognitionClient' appears in /data/app/~~8LIxSmLgDpCNUTY-v5rW9w==/com.laprairie.lmsApp-H_sLodmZA5gZ1eVAe4aNJw==/base.apk!classes20.dex)
E/AndroidRuntime(21842): 	at com.mapbox.common.movement.GoogleActivityRecognition.start(GoogleActivityRecognition.kt:115)
E/AndroidRuntime(21842): 	at com.mapbox.common.movement.AndroidMovementMonitor.registerObserver(AndroidMovementMonitor.kt:60)

**Comment by codenomaddev** [comment]
I have the same problem.. did I find out what it could be?

**Comment by eopeter** [comment]
Stale issue message
