### ISSUE TITLE
in navigation bar the remaining distance always show in metric.

### ISSUE THREAD

**Issue by fabioqueiros** [eopeter/flutter_mapbox_navigation#322]
even instantiating the units Navigation Options  as metric, the navigation panel always show the distance in imperial units.

**Comment by fabioqueiros** [comment]
The navigation are getting the android systems locale. 
So if you set the locale to US, the navigation will be in imperial (no care if you select metric).

Do you know if the sdk has a way to override android system units and use the user configured ones?

**Comment by eopeter** [comment]
It uses the device settings in some scenarios. Adjust your device to see if it picks it up. I have a PR coming that fixes this issue

**Comment by fabioqueiros** [comment]
Yes, if i set my device to english UK  (instead of US) it works in metric systems.
do you have some idea when you will push the PR?

**Comment by samderlust** [comment]
@fabioqueiros  i set `  language: "en-uk",`  do the job for me.

**Comment by eopeter** [comment]
Stale issue message
