### ISSUE TITLE
black screen on ios simulator

### ISSUE THREAD

**Issue by samderlust** [eopeter/flutter_mapbox_navigation#323]
I got black screen while try to use the mapbox navigation 

```
 MapBoxNavigationView(
            options: MapBoxOptions(
              initialLatitude: 36.1175275,
              initialLongitude: -115.1839524,
              zoom: 13.0,
              tilt: 0.0,
              bearing: 0.0,
              enableRefresh: false,
              alternatives: true,
              voiceInstructionsEnabled: true,
              bannerInstructionsEnabled: true,
              allowsUTurnAtWayPoints: true,
              mode: MapBoxNavigationMode.drivingWithTraffic,
              mapStyleUrlDay: "mapbox://styles/mapbox/light-v11",
              // mapStyleUrlNight: "mapbox://styles/mapbox/dark-v11",
              units: VoiceUnits.imperial,
              simulateRoute: true,
              language: "en",
            ),
            onRouteEvent: (event) {
              debugPrint("EVENT ${event.eventType}");
            },
            onCreated: (controller) async {
              mapCtrl.value = controller;
              await mapCtrl.value?.initialize();
              // controller.buildRoute(wayPoints: wayPoints);
            },
          ),


```
![simulator_screenshot_A25DBC62-65B4-4BBC-8A51-356F18C9E770](https://github.com/eopeter/flutter_mapbox_navigation/assets/29016919/8bcb3e74-548c-46d4-989f-ab1a5b74b3ba)

**Comment by eopeter** [comment]
Need to follow instruction on how to supply your access tokensOn Nov 1, 2023, at 5:15 PM, Sáng Nguyen ***@***.***> wrote:﻿
I got black screen while try to use the mapbox navigation
 MapBoxNavigationView(
            options: MapBoxOptions(
              initialLatitude: 36.1175275,
              initialLongitude: -115.1839524,
              zoom: 13.0,
              tilt: 0.0,
              bearing: 0.0,
              enableRefresh: false,
              alternatives: true,
              voiceInstructionsEnabled: true,
              bannerInstructionsEnabled: true,
              allowsUTurnAtWayPoints: true,
              mode: MapBoxNavigationMode.drivingWithTraffic,
              mapStyleUrlDay: "mapbox://styles/mapbox/light-v11",
              // mapStyleUrlNight: "mapbox://styles/mapbox/dark-v11",
              units: VoiceUnits.imperial,
              simulateRoute: true,
              language: "en",
            ),
            onRouteEvent: (event) {
              debugPrint("EVENT ${event.eventType}");
            },
            onCreated: (controller) async {
              mapCtrl.value = controller;
              await mapCtrl.value?.initialize();
              // controller.buildRoute(wayPoints: wayPoints);
            },
          ),

**Comment by samderlust** [comment]
@eopeter I've already set up the access key.

**Comment by eopeter** [comment]
Where did you put the Mapbox  access token?
Do you have the console output when the page loads? Does it work without the MapStyleUrl?

**Comment by samderlust** [comment]
@eopeter i put it in a `.netrc` file. and don't have any log to console

**Comment by samderlust** [comment]
it doesn't work without MapStyleUrl too

**Comment by samderlust** [comment]
I've also use `mapbox_maps_flutter` in my app

**Comment by samderlust** [comment]
This is what I got in xcode console. not display in flutter console
```
[Error, maps-core]: {}[Setup]: Failed to load style: HTTP status code 401
[Error, events_service]: Events sending aborted
[Error, events_service]: Events sending aborted
```

**Comment by eopeter** [comment]
The access token needs to be in your info.plist

**Comment by samderlust** [comment]
yes I put it under `<key>MBXAccessToken</key>`

**Comment by samderlust** [comment]
@eopeter  Do I need a different token for Navigation SDK or can be used same one with Maps SDK

**Comment by WaseekSenju** [comment]
@samderlust did you find any solution to this problem? well it happens when we add the url explicitly. I have placed the token with correct scope but still couldn't figure this out.
