### ISSUE TITLE
Navigation Example flutter_mapbox_navigation.dart gives error

### ISSUE THREAD

**Issue by rhyadav** [eopeter/flutter_mapbox_navigation#324]
While following the example, i'm getting an error for the import below

`import 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart';`

The error is "flutter_mapbox_navigation-0.0.26/lib/flutter_mapbox_navigation.dart:1:1: Error: This part doesn't have a containing library."

**Comment by eopeter** [comment]
Stale issue message
