### ISSUE TITLE
Waypoint markers (multistop) not shown in map when using embedded navigation.

### ISSUE THREAD

**Issue by fabioqueiros** [eopeter/flutter_mapbox_navigation#326]
Example:

_isMultipleStop = true;
var wayPoints = <WayPoint>[];
//wayPoints.add(_origin);
wayPoints.add(_stop1);
wayPoints.add(_stop2);
wayPoints.add(_stop3);

_controller!.buildRoute(wayPoints: wayPoints, options: _defaultOptions);
_controller!.startNavigation(options: _defaultOptions);

using this code, the navigations never show the waypoints marker in the map. the navigation are draw like "from A to B" route.

**Comment by fabioqueiros** [comment]
this issue are solved in this  #[commit](https://github.com/eopeter/flutter_mapbox_navigation/pull/292/commits/4d91c8b8e2f65baabb3884807429b57b047c6871)

**Comment by fabioqueiros** [comment]
@eopeter  can you please accept the merge in pull request in order to solve this issue?

**Comment by eopeter** [comment]
I approved but the author did not merge.

**Comment by marciotisouza** [comment]
I have the same problem, how can I use this tweak?

I tried putting it in the project: 

flutter_mapbox_navigation:
    git:
      url: https://github.com/eopeter/flutter_mapbox_navigation.git
      ref: master

**Comment by marcotrumpet** [comment]
Sorry guys I think it's not valid anymore.. In the end I did some tweak to this package for specific needs I had in an app I worked on so I'm not following this anymore.

**Comment by fabioqueiros** [comment]
@marciotisouza 
to fix that you need to do:
![image](https://github.com/eopeter/flutter_mapbox_navigation/assets/3912186/94a74e8e-6ac6-4677-81f7-ca67fd40b9e7)

**Comment by marciotisouza** [comment]
It worked, I downloaded the package to the plugins folder and made the adjustments you explained above.

In the pubspec.yaml file I left it like this:

   flutter_mapbox_navigation:
     path: plugins/flutter_mapbox_navigation

**Comment by marciotisouza** [comment]
I noticed that you are not saying the name of the destination when you arrive at the point, is there any way to adjust this too?

**Comment by marciotisouza** [comment]
I managed to do this adjustment:

  for (item in points) {
             val point = item.value as HashMap<*, *>
             val name = point["Name"] as String
             val latitude = point["Latitude"] as Double
             val longitude = point["Longitude"] as Double
             val isSilent = point["IsSilent"] as Boolean
             this.addedWaypoints.add(Waypoint(name, Point.fromLngLat(longitude, latitude),isSilent))
         }

**Comment by fabioqueiros** [comment]
yes, this looks like it will work!

**Comment by marciotisouza** [comment]
grateful for the support

**Comment by eopeter** [comment]
Stale issue message
