### ISSUE TITLE
Unable to get the embedded navigation version running in Dart SDK V3.13.9

### ISSUE THREAD

**Issue by DohanResponse24** [eopeter/flutter_mapbox_navigation#327]
**Unable to get the embedded navigation version running in Dart SDK V3.13.9**
 I was testing the embedded version on Android.

Exception has occurred.
PlatformException (PlatformException(error, Binary XML file line #11 in co.za.response24.responderApp:layout/navigation_activity: Binary XML file line #11 in co.za.response24.responderApp:layout/navigation_activity: Error inflating class <unknown>, null, android.view.InflateException: Binary XML file line #11 in co.za.response24.responderApp:layout/navigation_activity: Binary XML file line #11 in co.za.response24.responderApp:layout/navigation_activity: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #11 in co.za.response24.responderApp:layout/navigation_activity: Error inflating class <unknown> 

NOTE: I am able to get the full navigation working, so i believe the configs is fine.
```
   var wayPoints = <WayPoint>[];
    wayPoints.add(origin);
    wayPoints.add(destination);
    await MapBoxNavigation.instance.startNavigation(wayPoints: wayPoints);
```

I tried to add the embedded version but not able to run it with my current version.
`
  flutter_mapbox_navigation: 0.1.9
`

Also note when i upgrade to the latest version. It complies the first time but the second run it fails. I have attached the crash logs it from firebase.

![Screenshot 2023-11-07 at 14 16 20](https://github.com/eopeter/flutter_mapbox_navigation/assets/150141670/592bba49-2d01-41dc-836b-fbfe036a0ae8)

**Comment by eopeter** [comment]
Stale issue message
