### ISSUE TITLE
LateInitializationError: Field '_onRouteEvent@1568038182' has not been initialized.

### ISSUE THREAD

**Issue by neetable-chollarasan** [eopeter/flutter_mapbox_navigation#332]
This issue I am seeing in the sentry with 41k issue. I have removed the late in the file. Will this solve the error ?

LateInitializationError: Field '_onRouteEvent@1568038182' has not been initialized.

 Late ValueSetter<RouteEvent>? _onRouteEvent; to ValueSetter<RouteEvent>? _onRouteEvent

**Comment by eopeter** [comment]
Stale issue message
