### ISSUE TITLE
java.lang.NullPointerException: Missing required view with ID:  maneuverView  

### ISSUE THREAD

**Issue by mfagri** [eopeter/flutter_mapbox_navigation#334]
when i use embedded navigation i got this error in android in iOS worked fine 

E/AndroidRuntime( 6901): FATAL EXCEPTION: main
E/AndroidRuntime( 6901): Process: com.example.nav_mobile, PID: 6901
E/AndroidRuntime( 6901): java.lang.NullPointerException: Missing required view with ID: com.example.nav_mobile:id/maneuverView
E/AndroidRuntime( 6901): 	at com.mapbox.navigation.dropin.databinding.MapboxManeuverGuidanceLayoutBinding.bind(MapboxManeuverGuidanceLayoutBinding.java:60)
E/AndroidRuntime( 6901): 	at com.mapbox.navigation.dropin.maneuver.ManeuverViewBinder.bind(ManeuverViewBinder.kt:27)
E/AndroidRuntime( 6901): 	at com.mapbox.navigation.dropin.maneuver.ManeuverViewBinder.bind(ManeuverViewBinder.kt:16)
E/AndroidRuntime( 6901): 	at com.mapbox.navigation.ui.base.lifecycle.UICoordinator$onAttached$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:136)
E/AndroidRuntime( 6901): 	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invokeSuspend(Zip.kt:333)
E/AndroidRuntime( 6901): 	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invoke(Unknown Source:13)
E/AndroidRuntime( 6901): 	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invoke(Unknown Source:6)
E/AndroidRuntime( 6901): 	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:79)
E/AndroidRuntime( 6901): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime( 6901): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime( 6901): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 6901): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6901): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 6901): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 6901): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6901): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 6901): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 6901): 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@a70853e, Dispatchers.Main]
I/chatty  ( 6901): uid=10173(com.example.kubicfleet_mobile) FinalizerDaemon identical 6 lines
W/System  ( 6901): A resource failed to call close. 
I/Process ( 6901): Sending signal. PID: 6901 SIG: 9
Lost connection to device.

**Comment by reubendeekay** [comment]
@mfagri 
I have the same problem... were you able to solve it?

**Comment by marcoberetta96** [comment]
same issue here

is there any solution?

**Comment by eopeter** [comment]
Stale issue message

**Comment by mfagri** [comment]
> Stale issue message

yees
