### ISSUE TITLE
mi to km

### ISSUE THREAD

**Issue by behjat-amir** [eopeter/flutter_mapbox_navigation#337]
HI
    How to change mi to km ?

**Comment by KamalDesignOWeb** [comment]
late MapBoxOptions _navigationOption;
 _navigationOption = MapBoxNavigation.instance.getDefaultOptions();
 _navigationOption.language = "en_EN"; 
_navigationOption.language =  'en';
@amir-noroozi  on giving en to language will give you unit in km and on changeing it it will give unit in mi

**Comment by eopeter** [comment]
Stale issue message
