### ISSUE TITLE
Route Navigation Crashes

### ISSUE THREAD

**Issue by Kashif-Asghar60** [eopeter/flutter_mapbox_navigation#340]
The Navigation Crashes when the route is long like 1000km, Also it crashes when clicked on X button the app will crash.

Mapbox_gl and flutter_mapbox_navigation cant be used together lots of issues, duplicate classes

**Comment by ngeyen** [comment]
Can you use `mapbox_maps_flutter` (official mapbox package) instead of `mapbox_gl`, the latter has not been updated in a while

**Comment by eopeter** [comment]
Stale issue message
