### ISSUE TITLE
How to add custom route to navigation SDK that i created from direction api response.

### ISSUE THREAD

**Issue by KamalDesignOWeb** [eopeter/flutter_mapbox_navigation#341]
I created the custom route from direction api i want to navigate on that route. Any way to fulfill required functionality.

**Comment by Kashif-Asghar60** [comment]
check this out: 
https://github.com/eopeter/flutter_mapbox_navigation/issues/343#issuecomment-1938105673

**Comment by KamalDesignOWeb** [comment]
@Kashif-Asghar60 thank you for your response. However, I would like to clarify that I intend to pass the complete route obtained from the Direction API response, rather than just the start and end points.

**Comment by KamalDesignOWeb** [comment]
Any Update

**Comment by eopeter** [comment]
Stale issue message

**Comment by AlbertoNoris** [comment]
Hi @KamalDesignOWeb did you manage to solve this? I'm interested in the same subject: is it possibile to pass a custom route to the navigation? #343 only talks about customizing the request to the directions api playground but what if I want to build the route on my own with for example a different routing API and then pass it to this package for directions?
