### ISSUE TITLE
onRouteProgress - NOT WORKING!

### ISSUE THREAD

**Issue by marcelo-bottoni** [eopeter/flutter_mapbox_navigation#36]
I'm running the example available in this project and noticed that the onRouteProgress does not execute at all!

The code of the onRouteProgress never executes for me.
This way, I can't get distance and duration updates.

`
    _directions = MapboxNavigation(onRouteProgress: (arrived) async
    {
      print('THIS NEVER EXECUTES!!');

      _distanceRemaining = await _directions.distanceRemaining;
      _durationRemaining = await _directions.durationRemaining;

      setState(() {
        _arrived = arrived;
      });
      if (arrived)
        {
          await Future.delayed(Duration(seconds: 3));
          await _directions.finishNavigation();
        }
    });
`

Does anybody else have this issue?
Is there something I could do to make this work?

Thanks!

**Comment by marcelo-bottoni** [comment]
Having this issue on **Android**, running on real device (Moto G 5S Plus). Not on emulator.

**Comment by marcelo-bottoni** [comment]
Something else that I noticed.
I'm never getting a return on the **startNavigation** call.

Codes after this never gets executed as well.
The print **print('NAVIGATION STARTED');** never gets executed.

`print('STARTING NAVIGATION');

    await _navigator.startNavigation
    (
      origin: origin,
      destination: destination,
      mode: NavigationMode.drivingWithTraffic,
      language: "pt-BR",
      units: VoiceUnits.metric,

      simulateRoute: false
    );

    print('NAVIGATION STARTED');
`

Is this expected?

**Comment by eopeter** [comment]
onRouteProgress is not implemented in Android. This was indicated in the ReadMe and Change log
