### ISSUE TITLE
Android simulator crashes

### ISSUE THREAD

**Issue by larrylisky** [eopeter/flutter_mapbox_navigation#37]
Thanks creating this project.  I was able to run latest (v0.0.10) on github on both iOS simulator and device, but I am having trouble with the Android version.  It built without error, but the app crashes after the "Start Navigation" button is pressed.  I was able to step up to the below line in 'flutter_mapbox_navigation.dart' without crashing, but it will crash right after that.

    await _methodChannel.invokeMethod('startNavigation', args);

The crash log is attached.  It is complaining about 'libmapbox-gl.so' with 'expected e_machine: 40 (EM_ARM).  Any help would be greatly appreciated. 

I have checked that I added the same Mapbox access token used in successful iOS app to 'strings.xml'.  My 'flutter doctor' output is below:

==== begin =====
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

• No issues found!
=== end ====

Any insight on what I may be missing would be greatly appreciated.

[flutter_mapbox_navigation_android_crash_dump.txt](https://github.com/eopeter/flutter_mapbox_navigation/files/4429505/flutter_mapbox_navigation_android_crash_dump.txt)

**Comment by larrylisky** [comment]
I found my problem.  I was running on a default Pixel 2 ARM based emulator.  After I created a new emulator with X86_64 image and run the Demo app on it, everything worked fine.

**Comment by eliezerbasubi** [comment]
I also get the same error in my emulators. I am using Bluestacks and MemuPlay emulators and they both crash when I click on startNavigation button. 
Any idea how to fix this ???

**Comment by eopeter** [comment]
What does the error stack trace look like?

**Comment by eliezerbasubi** [comment]
Let me reproduce it again then I will send it to you

**Comment by eliezerbasubi** [comment]
Here is the file with the stack trace error message
[stacktrace.txt](https://github.com/eopeter/flutter_mapbox_navigation/files/4622046/stacktrace.txt)

**Comment by eliezerbasubi** [comment]
Finally, I made it work on my emulator android-x86 - Android 7.1.2 (API 25) by adding below lines in app level `build.gradle` file in depencies block.
```
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.2.0'
    implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:9.2.0') {
        exclude group: 'group_name', module: 'module_name'
    }
```

And adding these lines too in `android/build.gradle` file
```
mavenCentral()
maven { url 'https://mapbox.bintray.com/mapbox' }
```

**Comment by eliezerbasubi** [comment]
The only issue that I still have is to make it work in Android 5.4.1 (API 22).
The app crashes at runtime without any error message.
