### ISSUE TITLE
Feature request: Custom map styles

### ISSUE THREAD

**Issue by OSonntag** [eopeter/flutter_mapbox_navigation#39]
## Great plugin so far

You can customize maps at mapbox online via the studio editor and generate a map style url.

It would be nice if you can add this url into the MapboxNavigation.startNavigation call.

**Comment by eopeter** [comment]
this feature will be in v0.0.12

**Comment by eopeter** [comment]
set the `mapStyleURL` to the MapBox Style in version 0.0.16
