### ISSUE TITLE
Update location in firebase

### ISSUE THREAD

**Issue by rodrigocanepa** [eopeter/flutter_mapbox_navigation#42]
Are there anyway to update the current location to firebase while the user is seeing the navigation?

**Comment by Karlculations** [comment]
May I suggest starting an Isolate when the user starts the navigation? Within this Isolate, so can basically send the user's location to firebase.

**Comment by Malik056** [comment]
I have implemented this by make a location subscription using [https://pub.dev/packages/location](location) package, before starting navigation and it will keep running in background.
```
Location location = Location();
await location.changeSettings(distanceFilter: 50); //after give you call back after 50 meters
var locationSubscription = location.onLocationChanged().listen((locationData) {
                  _currentTimestamp =
                      DateTime.now().millisecondsSinceEpoch.toDouble();

                  Map<String, dynamic> dataToUpload = {
                    'currentTimestamp': _currentTimestamp,
                    'latlng': '${locationData.latitude},${locationData.longitude}',
                  };
});
```

You can use `locationSubscription.cancel();` to cancel subscription whenever you want anytime.
