### ISSUE TITLE
[Question] How many requests per minute to the Directions API are made?

### ISSUE THREAD

**Issue by ecerroni** [eopeter/flutter_mapbox_navigation#43]
I am looking to gain some knowledge about how many requests are made to the Mapbox APIs.

I set up [Flipper](https://pub.dev/packages/flutter_flipperkit) to intercepts the requests sent by the package. I can catch the logs, but unfortunately, it seems I cannot intercept the network for some reason.

Running the simulated route for 10 minutes while the simulated time was around 45 min, I logged around:
- [200]: 790 requests
- [404]: 284 requests
- [Failed]: 304 requests

![Screenshot from 2020-05-14 13-56-11](https://user-images.githubusercontent.com/11174327/81931621-b16fc700-95ea-11ea-8d80-bae21abe0a28.png)

The issue is that from the logs only I cannot identify calls made to the Directions API, and calls using the Maps SDKs for Mobile only (where unlimited Vector Tiles API and Raster Tiles API requests).

I am basically trying to understand how many calls to the Directions API are made, on average, during 1h navigation. I'd like to forecast Mapbox's costs for the navigation feature.

**Comment by eopeter** [comment]
Your MapBox Dashboard should be able to provide that information if you time your benchmark test accurately. I have not looked into it.
