### ISSUE TITLE
How can I show another page on the screen while flutter_mapbox_navigation working 

### ISSUE THREAD

**Issue by hbakarsu** [eopeter/flutter_mapbox_navigation#44]
I just want flutter_mapbox_navigation to work as notification service and while flutter_mapbox_navigation giving turn by turn navigation, I want to open another page on the screen. How can I do that?

**This is the current result.**
![current result](https://user-images.githubusercontent.com/32145047/82145267-44f70100-9852-11ea-937c-391ed339758e.PNG)

**This is what I want.**
![expected result](https://user-images.githubusercontent.com/32145047/82145260-39a3d580-9852-11ea-8363-4c71c80dad16.png)

**Comment by eopeter** [comment]
I will add the ability to minimize the navigationViewController. Probably in v0.13

**Comment by eopeter** [comment]
embedding added in version 0.0.16
