### ISSUE TITLE
startNavigation don't change the language

### ISSUE THREAD

**Issue by jogave77** [eopeter/flutter_mapbox_navigation#46]
Hi,
I changed the language to spanish
`await _directions.startNavigation(
                    origin: _origin,
                    destination: _destination,
                    mode: NavigationMode.drivingWithTraffic, 
                    language: 'Spanish',
                    simulateRoute: true, 
                    units: VoiceUnits.metric);`

but It continues speaking in English.

**Comment by eopeter** [comment]
Are you still having this issue with the latest version?

**Comment by eopeter** [comment]
instead of "Spanish" try "es". The ISO689-2 code for Spanish
