### ISSUE TITLE
No implementation found for method getPlatformVersion on channel flutter_mapbox_navigation

### ISSUE THREAD

**Issue by jtpdev** [eopeter/flutter_mapbox_navigation#49]
I followed the instructions to use the lib in my project, but I have this problem:

![image](https://user-images.githubusercontent.com/28665598/86371724-a1be4780-bc57-11ea-90ab-2585a34c5858.png)

I noticed that another problem occurs when the method **startNavigation** is called, ass well:

![image](https://user-images.githubusercontent.com/28665598/86372357-6bcd9300-bc58-11ea-9e14-d2dd16db70e2.png)

I already tried a lot of solutions but still not solves the problem.

**Comment by eopeter** [comment]
Should be resolved in the latest version
