### ISSUE TITLE
FlutterMapBox.startNavigation(); show blank page 

### ISSUE THREAD

**Issue by GurvinderParas** [eopeter/flutter_mapbox_navigation#5]
FlutterMapboxNavigation.startNavigation(origin, destination); show blank page and gives error of  PlatformException(error, Trying to create a platform view of unregistered type: com.mapbox/mapboxgl,null);

**Comment by eopeter** [comment]
Did you setup the access token?

**Comment by RamanParas** [comment]
yes  i set the mapbox access token in android manifest

**Comment by eopeter** [comment]
update to the latest version and try again

**Comment by RamanParas** [comment]
yes it works thank you

**Comment by RamanParas** [comment]
i have a question,can we get the route finish status or detail ,because i want to start again a navigation after first one finish

**Comment by eopeter** [comment]
version 0.0.5 supports route progress and ending route
