### ISSUE TITLE
Change Spoken Voice

### ISSUE THREAD

**Issue by jtpdev** [eopeter/flutter_mapbox_navigation#50]
I'm trying to use the spoken voice in Portuguese, but it isn't works in my device.

So I read that is possible change spoken voice in mapbox manualy (https://docs.mapbox.com/ios/api/navigation/0.14.0/localization-and-internationalization.html).

Any idea of implementation?

**Comment by eopeter** [comment]
Look at list of supported languages in the documentation:

https://pub.dev/documentation/flutter_mapbox_navigation/latest/navigation/MapboxNavigation/startNavigation.html

Then pass the language to startNavigation as a full string like "French"

**Comment by jtpdev** [comment]
I did this. 

```dart
onPressed: () async {
       await _directions.startNavigation(
       origin: _origin,
       destination: _destination,
       mode: NavigationMode.drivingWithTraffic,
        simulateRoute: true, language: "Portuguese", units: VoiceUnits.metric);
},
```

The words was translateds but the spoken voice not.

And *Portuguese* are a supported language.

**Comment by eopeter** [comment]
I tried on an iPhone and it works for me. I hear Portuguese. Are you having issues on both Android and iOS?

**Comment by jtpdev** [comment]
Only in Android...

Running **flutter doctor -v**:

> [✓] Flutter (Channel stable, v1.17.5, on Linux, locale pt_BR.UTF-8)
>     • Flutter version 1.17.5 at /home/jtpdev/Documentos/tools/flutter
>     • Framework revision 8af6b2f038 (3 days ago), 2020-06-30 12:53:55 -0700
>     • Engine revision ee76268252
>     • Dart version 2.8.4
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
>     • Android SDK at /home/jtpdev/Android/Sdk
>     • Platform android-30, build-tools 30.0.0
>     • Java binary at: /snap/android-studio/90/android-studio/jre/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [!] Android Studio (version 4.0)
>     • Android Studio at /snap/android-studio/90/android-studio
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6222593)
> 
> [✓] Connected device (1 available)
>     • SM J500M • f504007d • android-arm • Android 6.0.1 (API 23)

But in Galaxy J7 Android 5 it happens as well.

**Comment by jtpdev** [comment]
In **SM A205G • RX8M911AWKF • android-arm64 • Android 10 (API 29)** as well.

I just created a new project, I copied the example **main.dart** of the plugin project and import the plugin. So I change German to Portuguese and nothing happens. I only hear it in English.

**Comment by eopeter** [comment]
What happens when you pass in the ISO 639-1 2-letter Code for Portuguese, pt instead of the full string?

**Comment by jtpdev** [comment]
With version 0.0.11 and 'pt' instead of 'Portuguese' it works. \o/

Thanks a lot.
