### ISSUE TITLE
Duplicate class com.mapbox.mapboxsdk.plugins.annotation.SymbolOptions found in modules classes.jar

### ISSUE THREAD

**Issue by jorgemndoza** [eopeter/flutter_mapbox_navigation#51]
Hi,

Thanks for creating this package.

I am having the following error> 
`Duplicate class com.mapbox.mapboxsdk.plugins.annotation.SymbolOptions found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0)`

I also have this package installed.
https://pub.dev/packages/mapbox_gl

**Comment by eopeter** [comment]
Will check to make sure mapbox_gl and this library mapbox libraries are using same versions.

**Comment by SirLink** [comment]
I had this issue too, the latest mapbox_gl version uses 9.0.8.0 and mapbox-navigation uses 8.0.7.0, you can use my forked version in the meantime while they fix the issue. https://github.com/SirLink/flutter-mapbox-gl

**Comment by chinmayc14** [comment]
@SirLink  your version will not cause this error?

**Comment by SirLink** [comment]
> @SirLink your version will not cause this error?
Yes, just change your current flutter-mapbox-gl to my forked version and it should run fine
