### ISSUE TITLE
 flutter_mapbox_navigation errors

### ISSUE THREAD

**Issue by Aymen-Brahim** [eopeter/flutter_mapbox_navigation#52]
Hi,

Thanks for creating this package.
I'm beginner with Flutter

this is a part of the errors.

/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart:149:11: Error: Superclass has no method named 'initState'.
    super.initState();
          ^^^^^^^^^
/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart:139:21: Error: The getter 'widget' isn't defined for the class '_NavigationViewState'.
 - '_NavigationViewState' is from 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart' ('/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'widget'.
      "originName": widget.origin.name,
                    ^^^^^^
/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart:140:25: Error: The getter 'widget' isn't defined for the class '_NavigationViewState'.
 - '_NavigationViewState' is from 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart' ('/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'widget'.
      "originLatitude": widget.origin.latitude,
                        ^^^^^^
/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart:141:26: Error: The getter 'widget' isn't defined for the class '_NavigationViewState'.
 - '_NavigationViewState' is from 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart' ('/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'widget'.
      "originLongitude": widget.origin.longitude,
                         ^^^^^^
/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart:142:26: Error: The getter 'widget' isn't defined for the class '_NavigationViewState'.
 - '_NavigationViewState' is from 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart' ('/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'widget'.
      "destinationName": widget.destination.name,
                         ^^^^^^
/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart:143:30: Error: The getter 'widget' isn't defined for the class '_NavigationViewState'.
 - '_NavigationViewState' is from 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart' ('/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'widget'.
      "destinationLatitude": widget.destination.latitude,
                             ^^^^^^
/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart:144:31: Error: The getter 'widget' isn't defined for the class '_NavigationViewState'.
 - '_NavigationViewState' is from 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart' ('/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'widget'.
      "destinationLongitude": widget.destination.longitude,
                              ^^^^^^
/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart:145:24: Error: The getter 'widget' isn't defined for the class '_NavigationViewState'.
 - '_NavigationViewState' is from 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart' ('/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'widget'.
      "simulateRoute": widget.simulateRoute,
                       ^^^^^^
/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart:146:20: Error: The getter 'widget' isn't defined for the class '_NavigationViewState'.
 - '_NavigationViewState' is from 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart' ('/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'widget'.
      "language" : widget.language,
                   ^^^^^^
/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart:147:17: Error: The getter 'widget' isn't defined for the class '_NavigationViewState'.
 - '_NavigationViewState' is from 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart' ('/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'widget'.
      "units" : widget.units
                ^^^^^^
/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart:153:16: Error: 'BuildContext' isn't a type.
  Widget build(BuildContext context) {
               ^^^^^^^^^^^^
/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart:155:12: Error: The method 'SizedBox' isn't defined for the class '_NavigationViewState'.
 - '_NavigationViewState' is from 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart' ('/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SizedBox'.
    return SizedBox(
           ^^^^^^^^
/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart:158:14: Error: The method 'UiKitView' isn't defined for the class '_NavigationViewState'.
 - '_NavigationViewState' is from 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart' ('/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart').
Try correcting the name to the name of an existing method, or defining a method named 'UiKitView'.
      child: UiKitView(
             ^^^^^^^^^
/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart:161:32: Error: The method 'StandardMessageCodec' isn't defined for the class '_NavigationViewState'.
 - '_NavigationViewState' is from 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart' ('/C:/Users/Brahim-Mohsen/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_mapbox_navigation-0.0.11/lib/flutter_mapbox_navigation.dart').
Try correcting the name to the name of an existing method, or defining a method named 'StandardMessageCodec'.
          creationParamsCodec: StandardMessageCodec()),

**Comment by eopeter** [comment]
It seems flutter and dart not properly setup. Can you run a starter flutter project with no code?

**Comment by Aymen-Brahim** [comment]
I have a project and flutter and dart work very well , but the problem began when i put " import 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart';"

**Comment by eopeter** [comment]
Can you add the result of your flutter doctor?

**Comment by Aymen-Brahim** [comment]
C:\src\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [version 10.0.18363.900], locale fr-FR)
    • Flutter version 1.17.1 at C:\src\flutter
    • Framework revision f7a6a7906b (8 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Brahim-Mohsen\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Brahim-Mohsen\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
Process finished with exit code 0

**Comment by eopeter** [comment]
try again with latest version
