### ISSUE TITLE
After setting simulateRoute to False how to track live location and update marker?

### ISSUE THREAD

**Issue by KushalPathak** [eopeter/flutter_mapbox_navigation#53]
I want to track the live location of my device and show it on the map by default marker. 
I switched simulateRoute:false to stop automatic routing but even if I change my location the marker won't change course.
Help me out here.!!!
Thank You.!!

**Comment by eopeter** [comment]
It should show your location on the map if you have the right permissions in place. Check in settings and make sure the app has location services. Are you using the latest version? Do you have location permissions enabled in info.plist and android manifest?

**Comment by KushalPathak** [comment]
Yes Thank you for the response. I checked and it was fault from my side.
