### ISSUE TITLE
onRouteProgress function never called

### ISSUE THREAD

**Issue by schauersbergern** [eopeter/flutter_mapbox_navigation#58]
When I implement the Code example, and then install the app on an iPhone 6S or a Google Pixel 3 the onRouteProgress
function is never called.

I would need this function to automatically close navigation view, when the user arrives.

**Comment by eopeter** [comment]
Does it work on iOS?

**Comment by ulrichbjerre** [comment]
It works on my iPhone 8 with resent update to iOS 13...

Haven't tested on Android though. 

Whenever I arrive at my destination the navigation window closes after the 3 seconds as I believe is set in the example.

**Comment by schauersbergern** [comment]
I will test tomorrow with an iPhone 7 and Android Pixel 3 again.
On yesterdays test I had no internet so I got no results...

**Comment by schauersbergern** [comment]
I have tested again and it works on iOS. Tested with an iPhone 7.
On Android it is not working. Tested on a Pixel 3

**Comment by eopeter** [comment]
try again with latest version
