### ISSUE TITLE
How do I listen to navigation text instructions?

### ISSUE THREAD

**Issue by GarvMaggu** [eopeter/flutter_mapbox_navigation#59]
While navigating, instructions like "Turn left", "Turn right after 50m" appear on top, how can I listen to these instructions?
I want to access those instructions as a string.

**Comment by ulrichbjerre** [comment]
Works in iOS - just tested today. UNLESS you mean explicitly "50 meter"?
I get voiced turn-by-turn instructions whenever the MapBox engine finds it appropriate.

**Comment by eopeter** [comment]
try again with latest version
