### ISSUE TITLE
Feature request: Allow uturn

### ISSUE THREAD

**Issue by ulrichbjerre** [eopeter/flutter_mapbox_navigation#60]
I know the iOS version offers an "allowsUturnAtWaypoint" route option (I guess Android does too?): https://docs.mapbox.com/ios/api/directions/0.10.6/Classes/RouteOptions.html#/s:vC16MapboxDirections12RouteOptions21allowsUTurnAtWaypointSb

It would be really great to see that implemented as well.

**Comment by eopeter** [comment]
This feature is now enabled with Multi Stop WayPoint Navigation
