### ISSUE TITLE
Changing colors of some mapbox navigation's widgets

### ISSUE THREAD

**Issue by gadishimwe** [eopeter/flutter_mapbox_navigation#61]
Hi. Is it possible to change the colors of widgets? like this one of appbar? or is it possible to style this map? I'm also having an issue on my navigation icon(marker) as you can see, it's black and it was supposed to be blueish within a white circle. Any help will be much appreciated. And thanks for making this awesome package👏.
<img width="330" alt="Screen Shot 2020-08-30 at 23 22 07" src="https://user-images.githubusercontent.com/52411901/91669850-8f0da500-eb18-11ea-9817-faa702d3ef0f.png">

**Comment by eopeter** [comment]
with enable changing the style in next update

**Comment by eopeter** [comment]
set the `mapStyleURL` to the MapBox Style in version 0.0.16
