### ISSUE TITLE
java.lang.RuntimeException: Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Annotation found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0)

### ISSUE THREAD

**Issue by gadishimwe** [eopeter/flutter_mapbox_navigation#62]
Hello. I'm getting this error when I try to use both mapbox_gl and  flutter_mapbox_navigation in the same app. Individually, they’re working properly. 

packages versions:
- mapbox_gl: ^0.8.0
- flutter_mapbox_navigation: ^0.0.11

Any help will be highly appreciated. Thanks :)
<img width="1440" alt="Screen Shot 2020-08-31 at 22 12 36" src="https://user-images.githubusercontent.com/52411901/91764194-29342280-ebd7-11ea-8048-4a22ee7f068e.png">

**Comment by jtpdev** [comment]
Can you remove the lib mapbox_gl? In my case, I removed that lib and it worked fine.

**Comment by gadishimwe** [comment]
@jtpdev, I just need it for other functionalities of maps. I was only using flutter_mapbox_navigation for navigation. Do you think there is another better way of integrating Mapbox map into flutter app? I'm new to flutter and I'm developing an app that heavily relies on maps and directions. I switched the options to Mapbox because I wasn’t able to integrate inline Google maps Navigation into flutter and I found this package that uses Mapbox to fill that need of turn-to-turn navigation which is similar to Navigation from Google maps(Android). And I wanted to use one service for maps(either Google maps or Mapbox) if possible. Thanks.

**Comment by ulrichbjerre** [comment]
I'm using the flutter_map library with leaflet integration. 
I used these two videos to get started (can't remember which one I used first 😆):

https://youtu.be/oc1mktx0Zn8

https://youtu.be/qme30VC1yqk

**Comment by jtpdev** [comment]
@gadishimwe I understood, in my case I'm using google maps for another features. Try the @ulrichbjerre's suggestion.

**Comment by gadishimwe** [comment]
Thank you @ulrichbjerre for the response. I've watched those ones too😁, but I didn't like leaflet. I just want something like [this](https://pub.dev/packages/google_maps_flutter) for Mapbox and I just found that [mapbox_gl](https://pub.dev/packages/mapbox_gl) package can be somehow similar to that.

**Comment by gadishimwe** [comment]
@jtpdev I'm gonna reconsider going back to google maps for other features as you're saying if I continue to struggle with flutter mapbox packages and stick with only flutter_mapbox_navigation for Navigating purpose.

**Comment by ulrichbjerre** [comment]
Well, I'm uncertain what you want to accomplish - other than "just to implement a map" (in this case google maps). 
Is it the seamless refresh/loading of the GL map you're going for?

Anyway, in my case I use the MapBox directions web service to calculate and draw the route on the leaflet map. Then, whenever this plugin is ready, I'll be able to plan and navigate along a route with up to 25 waypoints.

**Comment by amucunguzi** [comment]
```
1. +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50 -> 1.3.72
2. |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.72
3. |         +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.72
4. |         \--- org.jetbrains:annotations:13.0 -> 16.0.1
5. +--- project :mapbox_gl
6. |    +--- com.mapbox.mapboxsdk:mapbox-android-sdk:9.2.0
7. |    |    +--- com.mapbox.mapboxsdk:mapbox-android-telemetry:5.0.1
8. |    |    |    +--- com.squareup.okhttp3:okhttp:3.12.0 -> 3.12.3
9. |    |    |    |    \--- com.squareup.okio:okio:1.15.0
10. |    |    |    +--- com.google.code.gson:gson:2.8.5 -> 2.8.6
11. |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
12. |    |    |    +--- com.mapbox.mapboxsdk:mapbox-android-core:2.0.1
13. |    |    |    \--- androidx.legacy:legacy-support-core-utils:1.0.0
14. |    |    |         +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
15. |    |    |         +--- androidx.core:core:1.0.0 -> 1.1.0
16. |    |    |         |    +--- androidx.annotation:annotation:1.1.0
17. |    |    |         |    +--- androidx.lifecycle:lifecycle-runtime:2.0.0 -> 2.2.0
18. |    |    |         |    |    +--- androidx.lifecycle:lifecycle-common:2.2.0
19. |    |    |         |    |    |    \--- androidx.annotation:annotation:1.1.0
20. |    |    |         |    |    +--- androidx.arch.core:core-common:2.1.0
21. |    |    |         |    |    |    \--- androidx.annotation:annotation:1.1.0
22. |    |    |         |    |    \--- androidx.annotation:annotation:1.1.0
23. |    |    |         |    +--- androidx.versionedparcelable:versionedparcelable:1.1.0
24. |    |    |         |    |    +--- androidx.annotation:annotation:1.1.0
25. |    |    |         |    |    \--- androidx.collection:collection:1.0.0 -> 1.1.0
26. |    |    |         |    |         \--- androidx.annotation:annotation:1.1.0
27. |    |    |         |    \--- androidx.collection:collection:1.0.0 -> 1.1.0 (*)
28. |    |    |         +--- androidx.documentfile:documentfile:1.0.0
29. |    |    |         |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
30. |    |    |         +--- androidx.loader:loader:1.0.0
31. |    |    |         |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
32. |    |    |         |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
33. |    |    |         |    +--- androidx.lifecycle:lifecycle-livedata:2.0.0
34. |    |    |         |    |    +--- androidx.arch.core:core-runtime:2.0.0
35. |    |    |         |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
36. |    |    |         |    |    |    \--- androidx.arch.core:core-common:2.0.0 -> 2.1.0 (*)
37. |    |    |         |    |    +--- androidx.lifecycle:lifecycle-livedata-core:2.0.0
38. |    |    |         |    |    |    +--- androidx.lifecycle:lifecycle-common:2.0.0 -> 2.2.0 (*)
39. |    |    |         |    |    |    +--- androidx.arch.core:core-common:2.0.0 -> 2.1.0 (*)
40. |    |    |         |    |    |    \--- androidx.arch.core:core-runtime:2.0.0 (*)
41. |    |    |         |    |    \--- androidx.arch.core:core-common:2.0.0 -> 2.1.0 (*)
42. |    |    |         |    \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0 -> 2.1.0
43. |    |    |         |         \--- androidx.annotation:annotation:1.1.0
44. |    |    |         +--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
45. |    |    |         |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
46. |    |    |         \--- androidx.print:print:1.0.0
47. |    |    |              \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
48. |    |    +--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.0.0
49. |    |    |    \--- com.google.code.gson:gson:2.8.6
50. |    |    +--- com.mapbox.mapboxsdk:mapbox-android-gestures:0.7.0
51. |    |    |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
52. |    |    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
53. |    |    +--- com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0
54. |    |    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
55. |    |    +--- com.mapbox.mapboxsdk:mapbox-sdk-turf:5.0.0
56. |    |    |    \--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:5.0.0 (*)
57. |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
58. |    |    +--- androidx.fragment:fragment:1.0.0 -> 1.1.0
59. |    |    |    +--- androidx.annotation:annotation:1.1.0
60. |    |    |    +--- androidx.core:core:1.1.0 (*)
61. |    |    |    +--- androidx.collection:collection:1.1.0 (*)
62. |    |    |    +--- androidx.viewpager:viewpager:1.0.0
63. |    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
64. |    |    |    |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
65. |    |    |    |    \--- androidx.customview:customview:1.0.0
66. |    |    |    |         +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
67. |    |    |    |         \--- androidx.core:core:1.0.0 -> 1.1.0 (*)
68. |    |    |    +--- androidx.loader:loader:1.0.0 (*)
69. |    |    |    +--- androidx.activity:activity:1.0.0
70. |    |    |    |    +--- androidx.annotation:annotation:1.1.0
71. |    |    |    |    +--- androidx.core:core:1.1.0 (*)
72. |    |    |    |    +--- androidx.lifecycle:lifecycle-runtime:2.1.0 -> 2.2.0 (*)
73. |    |    |    |    +--- androidx.lifecycle:lifecycle-viewmodel:2.1.0 (*)
74. |    |    |    |    \--- androidx.savedstate:savedstate:1.0.0
75. |    |    |    |         +--- androidx.annotation:annotation:1.1.0
76. |    |    |    |         +--- androidx.arch.core:core-common:2.0.1 -> 2.1.0 (*)
77. |    |    |    |         \--- androidx.lifecycle:lifecycle-common:2.0.0 -> 2.2.0 (*)
78. |    |    |    \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0 -> 2.1.0 (*)
79. |    |    \--- com.squareup.okhttp3:okhttp:3.12.3 (*)
80. |    +--- com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0
81. |    |    +--- androidx.appcompat:appcompat:1.0.0
82. |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
83. |    |    |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
84. |    |    |    +--- androidx.collection:collection:1.0.0 -> 1.1.0 (*)
85. |    |    |    +--- androidx.cursoradapter:cursoradapter:1.0.0
86. |    |    |    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
87. |    |    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
88. |    |    |    +--- androidx.fragment:fragment:1.0.0 -> 1.1.0 (*)
89. |    |    |    +--- androidx.vectordrawable:vectordrawable:1.0.0
90. |    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
91. |    |    |    |    \--- androidx.core:core:1.0.0 -> 1.1.0 (*)
92. |    |    |    \--- androidx.vectordrawable:vectordrawable-animated:1.0.0
93. |    |    |         +--- androidx.vectordrawable:vectordrawable:1.0.0 (*)
94. |    |    |         \--- androidx.legacy:legacy-support-core-ui:1.0.0
95. |    |    |              +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
96. |    |    |              +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
97. |    |    |              +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
98. |    |    |              +--- androidx.customview:customview:1.0.0 (*)
99. |    |    |              +--- androidx.viewpager:viewpager:1.0.0 (*)
100. |    |    |              +--- androidx.coordinatorlayout:coordinatorlayout:1.0.0
101. |    |    |              |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
102. |    |    |              |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
103. |    |    |              |    \--- androidx.customview:customview:1.0.0 (*)
104. |    |    |              +--- androidx.drawerlayout:drawerlayout:1.0.0
105. |    |    |              |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
106. |    |    |              |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
107. |    |    |              |    \--- androidx.customview:customview:1.0.0 (*)
108. |    |    |              +--- androidx.slidingpanelayout:slidingpanelayout:1.0.0
109. |    |    |              |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
110. |    |    |              |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
111. |    |    |              |    \--- androidx.customview:customview:1.0.0 (*)
112. |    |    |              +--- androidx.interpolator:interpolator:1.0.0
113. |    |    |              |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
114. |    |    |              +--- androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
115. |    |    |              |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
116. |    |    |              |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
117. |    |    |              |    \--- androidx.interpolator:interpolator:1.0.0 (*)
118. |    |    |              +--- androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
119. |    |    |              |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
120. |    |    |              |    \--- androidx.core:core:1.0.0 -> 1.1.0 (*)
121. |    |    |              \--- androidx.cursoradapter:cursoradapter:1.0.0 (*)
122. |    |    \--- com.mapbox.mapboxsdk:mapbox-android-sdk:9.0.0 -> 9.2.0 (*)
123. |    +--- com.mapbox.mapboxsdk:mapbox-android-plugin-localization-v9:0.12.0
124. |    |    +--- androidx.appcompat:appcompat:1.0.0 (*)
125. |    |    +--- com.mapbox.mapboxsdk:mapbox-android-sdk:9.0.0 -> 9.2.0 (*)
126. |    |    \--- com.jakewharton.timber:timber:4.7.1
127. |    |         \--- org.jetbrains:annotations:16.0.1
128. |    \--- io.flutter:flutter_embedding_release:1.0.0-9d5b21729ff53dbf8eadd8bc97e0e30d77abec95
129. |         +--- androidx.lifecycle:lifecycle-common:2.2.0 (*)
130. |         +--- androidx.lifecycle:lifecycle-common-java8:2.2.0
131. |         |    +--- androidx.lifecycle:lifecycle-common:2.2.0 (*)
132. |         |    \--- androidx.annotation:annotation:1.1.0
133. |         +--- androidx.lifecycle:lifecycle-runtime:2.2.0 (*)
134. |         +--- androidx.fragment:fragment:1.1.0 (*)
135. |         \--- androidx.annotation:annotation:1.1.0
136. +--- project :flutter_mapbox_navigation
137. |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.72 (*)
138. |    +--- com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.43.0-alpha.1
139. |    |    +--- com.mapbox.mapboxsdk:mapbox-android-navigation:0.43.0-alpha.1
140. |    |    |    +--- com.mapbox.mapboxsdk:mapbox-sdk-services:4.9.0
141. |    |    |    |    +--- com.mapbox.mapboxsdk:mapbox-sdk-core:4.9.0
142. |    |    |    |    |    +--- com.google.code.gson:gson:2.8.5 -> 2.8.6
143. |    |    |    |    |    +--- com.squareup.retrofit2:retrofit:2.4.0
144. |    |    |    |    |    |    \--- com.squareup.okhttp3:okhttp:3.10.0 -> 3.12.3 (*)
145. |    |    |    |    |    +--- com.squareup.retrofit2:converter-gson:2.4.0
146. |    |    |    |    |    |    +--- com.squareup.retrofit2:retrofit:2.4.0 (*)
147. |    |    |    |    |    |    \--- com.google.code.gson:gson:2.8.2 -> 2.8.6
148. |    |    |    |    |    \--- com.squareup.okhttp3:logging-interceptor:3.11.0
149. |    |    |    |    |         \--- com.squareup.okhttp3:okhttp:3.11.0 -> 3.12.3 (*)
150. |    |    |    |    \--- com.mapbox.mapboxsdk:mapbox-sdk-geojson:4.9.0 -> 5.0.0 (*)
151. |    |    |    +--- com.mapbox.mapboxsdk:mapbox-sdk-turf:4.9.0 -> 5.0.0 (*)
152. |    |    |    +--- com.mapbox.mapboxsdk:mapbox-android-core:1.3.0 -> 2.0.1
153. |    |    |    +--- com.mapbox.mapboxsdk:mapbox-android-telemetry:4.5.1 -> 5.0.1 (*)
154. |    |    |    +--- com.mapbox.navigator:mapbox-navigation-native:6.2.1
155. |    |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50 -> 1.3.72 (*)
156. |    |    |    +--- androidx.appcompat:appcompat:1.0.0 (*)
157. |    |    |    \--- com.jakewharton.timber:timber:4.7.1 (*)
158. |    |    +--- com.mapbox.mapboxsdk:mapbox-android-sdk:8.2.1 -> 9.2.0 (*)
159. |    |    +--- com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0
160. |    |    |    +--- com.mapbox.mapboxsdk:mapbox-android-sdk:8.0.0 -> 9.2.0 (*)
161. |    |    |    \--- androidx.appcompat:appcompat:1.0.0 (*)
162. |    |    +--- com.google.android.material:material:1.0.0
163. |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
164. |    |    |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
165. |    |    |    +--- androidx.legacy:legacy-support-core-ui:1.0.0 (*)
166. |    |    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
167. |    |    |    +--- androidx.fragment:fragment:1.0.0 -> 1.1.0 (*)
168. |    |    |    +--- androidx.transition:transition:1.0.0
169. |    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
170. |    |    |    |    \--- androidx.core:core:1.0.0 -> 1.1.0 (*)
171. |    |    |    +--- androidx.appcompat:appcompat:1.0.0 (*)
172. |    |    |    +--- androidx.cardview:cardview:1.0.0
173. |    |    |    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
174. |    |    |    \--- androidx.recyclerview:recyclerview:1.0.0
175. |    |    |         +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
176. |    |    |         +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
177. |    |    |         \--- androidx.legacy:legacy-support-core-ui:1.0.0 (*)
178. |    |    +--- androidx.recyclerview:recyclerview:1.0.0 (*)
179. |    |    +--- androidx.constraintlayout:constraintlayout:1.1.3
180. |    |    |    \--- androidx.constraintlayout:constraintlayout-solver:1.1.3
181. |    |    +--- androidx.cardview:cardview:1.0.0 (*)
182. |    |    +--- androidx.lifecycle:lifecycle-extensions:2.0.0-rc01
183. |    |    |    +--- androidx.lifecycle:lifecycle-runtime:2.0.0-rc01 -> 2.2.0 (*)
184. |    |    |    +--- androidx.arch.core:core-common:2.0.0-rc01 -> 2.1.0 (*)
185. |    |    |    +--- androidx.arch.core:core-runtime:2.0.0-rc01 -> 2.0.0 (*)
186. |    |    |    +--- androidx.fragment:fragment:1.0.0-rc01 -> 1.1.0 (*)
187. |    |    |    +--- androidx.lifecycle:lifecycle-common:2.0.0-rc01 -> 2.2.0 (*)
188. |    |    |    +--- androidx.lifecycle:lifecycle-livedata:2.0.0-rc01 -> 2.0.0 (*)
189. |    |    |    +--- androidx.lifecycle:lifecycle-process:2.0.0-rc01
190. |    |    |    |    \--- androidx.lifecycle:lifecycle-runtime:2.0.0-rc01 -> 2.2.0 (*)
191. |    |    |    +--- androidx.lifecycle:lifecycle-service:2.0.0-rc01
192. |    |    |    |    \--- androidx.lifecycle:lifecycle-runtime:2.0.0-rc01 -> 2.2.0 (*)
193. |    |    |    \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0-rc01 -> 2.1.0 (*)
194. |    |    +--- com.squareup.picasso:picasso:2.71828
195. |    |    |    +--- com.squareup.okhttp3:okhttp:3.10.0 -> 3.12.3 (*)
196. |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
197. |    |    |    \--- androidx.exifinterface:exifinterface:1.0.0
198. |    |    |         \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
199. |    |    \--- com.jakewharton.timber:timber:4.7.1 (*)
200. |    \--- io.flutter:flutter_embedding_release:1.0.0-9d5b21729ff53dbf8eadd8bc97e0e30d77abec95 (*)
201. +--- io.flutter:flutter_embedding_release:1.0.0-9d5b21729ff53dbf8eadd8bc97e0e30d77abec95 (*)
202. +--- io.flutter:armeabi_v7a_release:1.0.0-9d5b21729ff53dbf8eadd8bc97e0e30d77abec95
203. \--- io.flutter:arm64_v8a_release:1.0.0-9d5b21729ff53dbf8eadd8bc97e0e30d77abec95
```
After digging a bit, I see that the problem is due to the dependencies on Line 80 and Line 159. This page https://developer.android.com/studio/build/dependencies#resolution_errors mentions how to remove duplicate dependencies, but I haven't managed to make it work. @ulrichbjerre  @jtpdev

**Comment by amucunguzi** [comment]
configurations {
    all*.exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-plugin-annotation-v8'
}

In `android/gradle.build` seems to the issue.

**Comment by jtpdev** [comment]
I also couldn't get it to work without the google maps, but all I needed of the mapbox was the navigation step-by-step.

**Comment by gadishimwe** [comment]
Thanks @amucunguzi for taking your time and fix the issue

**Comment by gadishimwe** [comment]
> Well, I'm uncertain what you want to accomplish - other than "just to implement a map" (in this case google maps).
> Is it the seamless refresh/loading of the GL map you're going for?
> 
> Anyway, in my case I use the MapBox directions web service to calculate and draw the route on the leaflet map. Then, whenever this plugin is ready, I'll be able to plan and navigate along a route with up to 25 waypoints.

Hey @ulrichbjerre, Don’t know what you meant by "seamless refresh/loading of the GL map", can you please help compare that gl map and leaflet? I don’t know much about maps. Thanks.

**Comment by ulrichbjerre** [comment]
> > Well, I'm uncertain what you want to accomplish - other than "just to implement a map" (in this case google maps).
> 
> > Is it the seamless refresh/loading of the GL map you're going for?
> 
> > 
> 
> > Anyway, in my case I use the MapBox directions web service to calculate and draw the route on the leaflet map. Then, whenever this plugin is ready, I'll be able to plan and navigate along a route with up to 25 waypoints.
> 
> 
> 
> Hey @ulrichbjerre, Don’t know what you meant by "seamless refresh/loading of the GL map", can you please help me compare that gl map and leaflet? I don’t know much about maps :) Thanks.

Well....not knowing much about it I'm sort of guessing?
But, I'm under the impression the GL maps load/refresh faster than the leaflet maps - I honestly don't know. 🤷🏼‍♂️

So if you need some specific functionality from the GL plugin - then you off course need to use it. 😊

**Comment by gadishimwe** [comment]
> > > Well, I'm uncertain what you want to accomplish - other than "just to implement a map" (in this case google maps).
> > 
> > 
> > > Is it the seamless refresh/loading of the GL map you're going for?
> > 
> > 
> > > 
> > 
> > 
> > > Anyway, in my case I use the MapBox directions web service to calculate and draw the route on the leaflet map. Then, whenever this plugin is ready, I'll be able to plan and navigate along a route with up to 25 waypoints.
> > 
> > 
> > Hey @ulrichbjerre, Don’t know what you meant by "seamless refresh/loading of the GL map", can you please help me compare that gl map and leaflet? I don’t know much about maps :) Thanks.
> 
> Well....not knowing much about it I'm sort of guessing?
> But, I'm under the impression the GL maps load/refresh faster than the leaflet maps - I honestly don't know. 🤷🏼‍♂️
> 
> So if you need some specific functionality from the GL plugin - then you off course need to use it. 😊

Oh yeah. I think I misunderstood what you meant😅. I thought you were saying that it loads so slow.

**Comment by ealong** [comment]
Ran into a similar issue with newer versions of mapbox_gl and flutter_mapbox_navigation. This time duplicated class was 'mapbox-android-telemetry'.

So solution for me was:

configurations {
    all*.exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-telemetry'
}

Thanks @amucunguzi !

**Comment by scortumee** [comment]
@amucunguzi  @ealong There is no such file `gradle.build` in `android/app/`. If you guys are referencing `build.gradle` instead, where should I put `configurations{...}`  in it. Thanks

**Comment by RichardSV15** [comment]
> 

The proper setup is in: android/app/build.gradle

android {
   ...
   configurations {
        all*.exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-telemetry'
    }
  ...
}

**Comment by Hi99simon** [comment]
not working for new version plugin flutter_mapbox_navigation 0.1.6
Duplicate class com.mapbox.android.core.location.LocationEngine found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineCallback found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineProvider found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineRequest found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineRequest$1 found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineRequest$Builder found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.location.LocationEngineResult found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.permissions.PermissionsListener found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.permissions.PermissionsManager found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)
     Duplicate class com.mapbox.android.core.permissions.PermissionsManager$AccuracyAuthorization found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)

**Comment by marciotisouza** [comment]
Hi everyone, I have the same problem with flutter_mapbox_navigation ^0.1.7 and mapbox_gl: ^0.16.0 , any solution?

**Comment by Venum693** [comment]
hi everyone , i got same error, i tried including this
configurations {
    all*.exclude group: 'com.mapbox.common',  module: 'common'
}
the error is gone but app is not installing . it crashes immediately showing the the dialog box

NAVIGATIONAPP has stopped

**Comment by sKY02644** [comment]
> not working for new version plugin flutter_mapbox_navigation 0.1.6 Duplicate class com.mapbox.android.core.location.LocationEngine found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0) Duplicate class com.mapbox.android.core.location.LocationEngineCallback found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0) Duplicate class com.mapbox.android.core.location.LocationEngineProvider found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0) Duplicate class com.mapbox.android.core.location.LocationEngineRequest found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0) Duplicate class com.mapbox.android.core.location.LocationEngineRequest$1 found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0) Duplicate class com.mapbox.android.core.location.LocationEngineRequest$Builder found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0) Duplicate class com.mapbox.android.core.location.LocationEngineResult found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0) Duplicate class com.mapbox.android.core.permissions.PermissionsListener found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0) Duplicate class com.mapbox.android.core.permissions.PermissionsManager found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0) Duplicate class com.mapbox.android.core.permissions.PermissionsManager$AccuracyAuthorization found in modules jetified-common-23.2.3-runtime (com.mapbox.common:common:23.2.3) and jetified-mapbox-android-core-5.0.0-runtime (com.mapbox.mapboxsdk:mapbox-android-core:5.0.0)

Any solution with this??

**Comment by dhaq** [comment]
Facing this issue with latest version, please help
