### ISSUE TITLE
Restrictions on non-SDK interfaces(Android)

### ISSUE THREAD

**Issue by gadishimwe** [eopeter/flutter_mapbox_navigation#63]
Hello @eopeter. I'm getting this error which I searched that it is being caused by restrictions on non-SDK interfaces which google introduced starting from Android 9. I was testing my app on android 10 and the error appears every time I call startNavigation() method and the navigation doesn’t start. Do you know what might be causing it?
`Accessing hidden method Lcom/android/org/conscrypt/ConscryptEngineSocket;->setUseSessionTickets(Z)V (blacklist,core-platform-api, reflection, denied)`

**Comment by eopeter** [comment]
try again with latest version
