### ISSUE TITLE
Problem importing

### ISSUE THREAD

**Issue by dmanzanomartin** [eopeter/flutter_mapbox_navigation#64]
Hi, first sorry because I'm new on flutter, but while I'm importing I have this problem:

The plugin `flutter_mapbox_navigation` doesn't have a main class defined in /Users/davidmanzano/.pub-cache/git/flutter_mapbox_navigation-e7ac6a4d917acb1e08a2d752d1666355198dbc18/android/src/main/java/com/dormmom/flutter_mapbox_navigation/FlutterMapboxNavigationPlugin.java or /Users/davidmanzano/.pub-cache/git/flutter_mapbox_navigation-e7ac6a4d917acb1e08a2d752d1666355198dbc18/android/src/main/kotlin/com/dormmom/flutter_mapbox_navigation/FlutterMapboxNavigationPlugin.kt. This is likely to due to an incorrect `androidPackage: com.dormmom.flutter_mapbox_navigation` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile. 
exit code 1

Thank you.

**Comment by eopeter** [comment]
try again with latest version

**Comment by rossbroom99** [comment]
What do you mean by latest version? I have this issue as well. Is that the latest kotlin version you mean?

Cheers
