### ISSUE TITLE
Unhandled Exception: type 'String' is not a subtype of type 'FutureOr<bool>'

### ISSUE THREAD

**Issue by gadishimwe** [eopeter/flutter_mapbox_navigation#68]
### Hello @eopeter, I'm getting this error on ios when I reach the destination.
V0.0.12

<img width="801" alt="Screen Shot 2020-09-20 at 13 29 50" src="https://user-images.githubusercontent.com/52411901/93710271-8d4a6680-fb45-11ea-86c2-2dbdc75118d4.png">

**Comment by eopeter** [comment]
Fixed in latest
