### ISSUE TITLE
finishNavigation and call back not working on android

### ISSUE THREAD

**Issue by mo-ah-dawood** [eopeter/flutter_mapbox_navigation#7]
The method finishNavigation is not working on android
the callback for onRouteProgress not working on android

not tested on ios

**Comment by eopeter** [comment]
Currently only implemented in iOS.

**Comment by neliousness** [comment]
I've been struggling with this for a while now.. thank goodness i found this post. But will it be implemented any time soon on android? @eopeter

**Comment by francoisrenier** [comment]
Same here ! Any chance we could have this on android ? It would be awesome ! Great work on the overall plugin btw !

**Comment by thomasstas** [comment]
> Currently only implemented in iOS.

Would love to see this working on Android as well! Let me know if you want some help to implement it.

**Comment by SwaggyNico** [comment]
Just discovered your work a few days ago and it is AMAZING !!! Nevertheless, I think that if you were implementing the mentioned features, it could be even greater ! Keep up the good work :)

**Comment by julcharton** [comment]
> Currently only implemented in iOS.

I would love to see it working on Android too 😀

**Comment by hafiz703** [comment]
https://github.com/mapbox/mapbox-navigation-android/issues/1902 Could this be the issue?

**Comment by brad007** [comment]
has this not been worked on yet?

**Comment by paopp2** [comment]
Any updates on this issue yet? Great plugin btw :)

**Comment by AnasSafi** [comment]
Any updates?

**Comment by umair-ilyas** [comment]
Yes kindly update it for android as well so that more people can get benefit of it.

**Comment by lc-heia** [comment]
Hi guys,

Because I needed the finishNavigation method on Android, I done a workaround to add this fonctionnality. For those who are interrested, I created a [pull request](https://github.com/eopeter/flutter_mapbox_navigation/pull/41) on this project.
I did few researchs. Currently, Mapbox offer two ways to create a navigation system: Do your own activity with a NavigationView or use the NavigationLauncher (used by this plugin) which is a lightweight solution. Unfortunately, the launcher do not provide a way to finish the activity that is started.
My workaround is just a copy of the NavigationLauncher where I added a method to finish the activity.

**Comment by eopeter** [comment]
this workaround will only work if you call finishNavigation() manually. the route progress to detect when the route completes to auto call finishNavigation() as shown in the example is not working as the NavigationLauncher does not emit route progress events. If there is a fix for this, I will be happy to accept a pull request.

**Comment by morganchorlton3** [comment]
does this new push now make it possible to end navigation in flutter (for android) if so how do I do it?

**Comment by Matthuffy** [comment]
I will assume that by the lack of answer that this feature does not work even though the update states "Done finishNavigation successfully" however obviously has not. I think it i best to find another solution as this is poorly maintained and clearly not going anywhere.

**Comment by eopeter** [comment]
You can submit a pull request with your requested feature. It’s open for contribution.

**Comment by Matthuffy** [comment]
> You can submit a pull request with your requested feature. It’s open for contribution.
> […](#)
> On Jun 1, 2020, at 5:00 PM, Matthuffy ***@***.***> wrote: ﻿ I will assume that by the lack of answer that this feature does not work even though the update states "Done finishNavigation successfully" however obviously has not. I think it i best to find another solution as this is poorly maintained and clearly not going anywhere. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

You were asked a question above by morganchorlton3 on 23rd April.

**Comment by MomenElzeiny172** [comment]
@eopeter 
how to finishNavigation() manually ?

**Comment by kostricanitechnology** [comment]
I am getting a duplicate voiceover when I refresh the page or when I lock the phone and unclock again. Does anyone have a solution for this?

Seems that finishNavigation() doesn't work
