### ISSUE TITLE
Getting an exception when closing navigation view(Android)

### ISSUE THREAD

**Issue by gadishimwe** [eopeter/flutter_mapbox_navigation#70]
<img width="1440" alt="Screen Shot 2020-09-21 at 08 59 40" src="https://user-images.githubusercontent.com/52411901/93739621-051d9d00-fbe9-11ea-8f64-6bbafe85ab42.png">

**Comment by eopeter** [comment]
What version of the package are you using?

**Comment by gadishimwe** [comment]
> What version of the package are you using?
> […](#)
> On Sep 21, 2020, at 3:06 AM, Gad Ishimwe ***@***.***> wrote: ﻿ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I'm using the latest version(0.0.14)

**Comment by eopeter** [comment]
Please make sure you check the string you pass to Text() widget is not null. VoiceInstruction or other texts could be null. This error does not happen on the example code.
