### ISSUE TITLE
Unhandled Exception: FormatException: Unexpected character (at character 40) (Android)

### ISSUE THREAD

**Issue by gadishimwe** [eopeter/flutter_mapbox_navigation#71]
### I'm getting this error when reached at the destination 
<img width="847" alt="Screen Shot 2020-09-21 at 08 57 40" src="https://user-images.githubusercontent.com/52411901/93739429-92acbd00-fbe8-11ea-948e-36392873d8a7.png">

**Comment by eopeter** [comment]
This is fixed in v0.0.15
