### ISSUE TITLE
mapbox navigation

### ISSUE THREAD

**Issue by gaurav472** [eopeter/flutter_mapbox_navigation#72]
how can i implement the route preview before navigation 

and how can i use the mapbox gl with it in same project

when i use https://github.com/messenger2011/flutter-mapbox-gl with navigation it shows duplicate filels erros like this 

I am using 3 sdks in single project which are as below,

mapbox_gl: ^0.8.0
mapbox_gl_platform_interface: ^0.8.0
flutter_mapbox_navigation: ^0.0.11
And getting error as below

Note: Some input files use or override a deprecated API. Note: Recompile with -Xlint:deprecation for details. Note: Some input files use unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

What went wrong: Execution failed for task ':app:checkDebugDuplicateClasses'.
1 exception was raised by workers: java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Annotation found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager$1 found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager$1$1 found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager$MapClickResolver found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.BuildConfig found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Circle found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.CircleElementProvider found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.CircleManager found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.CircleOptions found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.ConvertUtils found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.CoreElementProvider found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.DraggableAnnotationController found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.DraggableAnnotationController$1 found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.DraggableAnnotationController$AnnotationMoveGestureListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Fill found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.FillElementProvider found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.FillManager found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.FillOptions found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Line found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.LineElementProvider found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.LineManager found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.LineOptions found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnAnnotationClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnAnnotationDragListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnAnnotationLongClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnCircleClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnCircleDragListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnCircleLongClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnFillClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnFillDragListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnFillLongClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnLineClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnLineDragListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnLineLongClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnSymbolClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnSymbolDragListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.OnSymbolLongClickListener found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Options found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.Symbol found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.SymbolElementProvider found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.SymbolManager found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0) Duplicate class com.mapbox.mapboxsdk.plugins.annotation.SymbolOptions found in modules classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0) and classes.jar (com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v9:0.8.0)

Go to the documentation to learn how to Fix dependency resolution errors.

Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 12s Exception: Gradle task assembleDebug failed with exit code 1

**Comment by gadishimwe** [comment]
Hey @gaurav472, I think you may have a look at this quick fix in the meantime.
https://github.com/eopeter/flutter_mapbox_navigation/issues/62#issuecomment-685203144

**Comment by gaurav472** [comment]
Thanks for solution  issue solved

**Comment by lexprimost** [comment]
hi have you find how to implement the route preview ?
