### ISSUE TITLE
Turn by turn voicing,  units and voicing quality

### ISSUE THREAD

**Issue by ulrichbjerre** [eopeter/flutter_mapbox_navigation#73]
Thank you for a GREAT plugin!
It really helps mw with my desired functionality!
The recent multi-waypoint navigation is just awesome...however...

I have a few issues using versions 0.0.11, 0.0.12 and 0.0.13 (I've never tried the earlier versions).
Tested on an iOS13 simulator and iPhone 8 with iOS 13.7
The problem relates to a combination with voicing and units.

This is the code I'm using when starting the navigation.

    await _directions.startNavigationWithWayPoints(
        wayPoints: routePoints, (an array of WayPoint objects)
        mode: mode, (set to walking mode)
        simulateRoute: true,
        language: "en",
        allowsUTurnAtWayPoints: true,
        isOptimized: false,
        units: VoiceUnits.metric);

English voicing:
With the code above I get instructions in English but the the 'metric' unit is ignored - thus units are shown and spoken as miles and feet (imperial) rather than kilometer and meters (metric).
I've also tried with the language set to 'English' and 'english'.

Danish voicing:
With the code above I get instructions in Danish but the voicing is English i.e. the Danish instructions are spoken with an English pronunciation. The metric units are metric, maybe because the language has metric unit as default.
Setting units to imperial is ignored.
I have tried with the language set to "da", "danish" and "Danish" - nothing resolve to a voice with Danish pronunciation.

Voice quality:
When testing on an iOS simulator the spoken voice is a female voice with high quality.
When testing on a physical device the spoken voice is a male low quality robot-like voice.

Best regards
Ulrich Bjerre

**Comment by eopeter** [comment]
Please try the latest version for the voices. That is weird. For the poor voice quality, maybe your data connection is not very good? Can you try on real device?

The language should be the 2-digit ISO format

**Comment by ulrichbjerre** [comment]
I don't know what has happened?
I updated from version 13 to 15 - now then navigation doesn't work anymore?
It's skips in between waypoints both when I simulate and I test on physical device.

The sound quality is still terrible...I'm on the same network when I test on simulator and on physical device.
I doubt that the network quality should affect that the voice changes from a female voice to a male voice?
And the danish language is not supported...

**Comment by ulrichbjerre** [comment]
Here are some more comments...with regards to my latest post...

First of all this is the code I'm using both examples, when starting the multi-point navigation:

 await _directions.startNavigationWithWayPoints(
        wayPoints: routePoints,
        mode: mode, //walking
        simulateRoute: _simulate, //true
        language: _language, //"da"
        allowsUTurnAtWayPoints: _allowUTurn, //true
        isOptimized: false,
        units: VoiceUnits.imperial);

**Here are a few screenshot using version 13.**
The route is calculated through the Mapbox webservice and drawn on a leaflet map.
The waypoints are then used as input to the startNavigationWithWaypoints(...)
Although rotated, it is clear to see, that the planned route is the same calculated route in the navigation window:
![IMG_5506](https://user-images.githubusercontent.com/30419460/94069866-98292380-fdf1-11ea-8457-741a792065db.PNG)
![IMG_5505](https://user-images.githubusercontent.com/30419460/94069895-a1b28b80-fdf1-11ea-89b3-a4d4faa2e54e.PNG)


**Here** are the same screenshot using version 15
The planned route is the same, however the calculated route in the navigation window has completely changed - the only waypoint is the first - the last is ignored.
![IMG_5506](https://user-images.githubusercontent.com/30419460/94070020-ceff3980-fdf1-11ea-92ff-c4159cfd118a.PNG)
![IMG_5509](https://user-images.githubusercontent.com/30419460/94070043-d6264780-fdf1-11ea-8ea0-6dea875cb078.PNG)
