### ISSUE TITLE
Unwanted Dialog (and Toast) when arriving at point on Android

### ISSUE THREAD

**Issue by sandyscoffable** [eopeter/flutter_mapbox_navigation#74]
Hi,
I'm using `startNavigationWithWayPoints()`, and when I arrive at a waypoint, I get a dialog like this:
<img src="https://user-images.githubusercontent.com/20515901/93900673-94ac7400-fced-11ea-904c-c1380af0d887.png" width="320" />

There is no way that I can see to turn that dialog off, or customise the dialog? 
There is also a Toast that says "You have arrived!", which is also not ideal.

I've inspected the source, and these things seem to be [hardcoded into the Activity](https://github.com/eopeter/flutter_mapbox_navigation/blob/master/android/src/main/kotlin/com/dormmom/flutter_mapbox_navigation/activity/NavigationActivity.kt#L262)

**Comment by eopeter** [comment]
This is fixed in v 0.0.15. You now have the choice to set "PauseAtWayPoint" which is false by default
