### ISSUE TITLE
Voicing and quality

### ISSUE THREAD

**Issue by ulrichbjerre** [eopeter/flutter_mapbox_navigation#77]
The voicing and quality is very poor on physical iOS device.

I have tested with version 11, 13, and 15.
I have tested on iOS simulator and Physical phone (not on Android).

iOS simulator: the voice is a high quality female voice.
Physical device: the voice is a low quality robot-like male voice

Both tests are performed on the same wireless network.

**Comment by eopeter** [comment]
I cannot replicate this. I always get a female voice. Maybe CDN issues with Polly

**Comment by ulrichbjerre** [comment]
I NEVER get a female voice.....what could I do then?
