### ISSUE TITLE
Missing Danish spoken instructions

### ISSUE THREAD

**Issue by ulrichbjerre** [eopeter/flutter_mapbox_navigation#78]
When attempting to use danish language the instructions are in danish, but the spoken language is English.
Thus, the pronunciation is like an English person reading danish text/instructions.

I have tested version 11, 13 and 15.
I have tried on an iOS simulator and a physical iOS device (not android)

I have tried using: "da", "danish", "Danish" - none of them works.

The attached screenshots shows the instructions in danish at the top - but the voicing is in English.
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-25 at 00 20 17](https://user-images.githubusercontent.com/30419460/94206129-025ec880-fec5-11ea-876f-3f89c8eea035.png)

**Comment by eopeter** [comment]
I am getting a Danish voice with instruction on the latest version
