### ISSUE TITLE
VoiceUnits.metric does not override imperial units

### ISSUE THREAD

**Issue by ulrichbjerre** [eopeter/flutter_mapbox_navigation#79]
Using language "en" and units: VoiceUnits.metric does not present distances in metric.
The attached screenshot shows the imperial units - although the units is set to metric.
The language is set to "en".
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-25 at 00 22 19](https://user-images.githubusercontent.com/30419460/94206316-74371200-fec5-11ea-8297-026592813ab9.png)

**Comment by eopeter** [comment]
I do not see this issue in the latest version, please try again.
![device-2020-09-26-100734](https://user-images.githubusercontent.com/2012979/94342625-42669e00-ffe0-11ea-8a5a-8246b4230405.png)
