### ISSUE TITLE
Navigation window does not display entire route when using multiples waypoints

### ISSUE THREAD

**Issue by ulrichbjerre** [eopeter/flutter_mapbox_navigation#80]
As of version 15, when starting the navigation with multiple waypoints the complete route is no longer displayed in the navigation window (pauseAtWaypoints set to default = false).
The first screenshots below shows 1: the calculated route (overview) in a leaflet map.
This is followed by the navigation window - a screenshot for each sub-section of the route.

Pre-drawn (entire) route:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-25 at 00 25 36](https://user-images.githubusercontent.com/30419460/94206810-9aa97d00-fec6-11ea-9b5b-5cf44fa597c7.png)

First sub-section:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-25 at 00 25 44](https://user-images.githubusercontent.com/30419460/94206874-bdd42c80-fec6-11ea-97d7-e81145056255.png)

Second sub-section:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-25 at 00 26 08](https://user-images.githubusercontent.com/30419460/94207005-fecc4100-fec6-11ea-8503-70f06d95c189.png)

Third sub-section:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-25 at 00 26 57](https://user-images.githubusercontent.com/30419460/94207015-025fc800-fec7-11ea-8048-de37202c416d.png)

Fourth (and final) sub-section:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-25 at 00 27 22](https://user-images.githubusercontent.com/30419460/94207022-07247c00-fec7-11ea-8f2c-306c3f3e9d7b.png)

When simulating the route the entire route is traversed - although only one section is visible at a time.
When reaching the last waypoint the last instructions are "you have arrived at [whatever the name is]" - however, the popup displays another name.

In this case - the name of the that last waypoint is "your destination" where as the name of the second waypoint (out of 5) is "Waypoint 1".
Thus - the top instructions are correct, but the bottom text is wrong:
![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-09-25 at 00 28 15](https://user-images.githubusercontent.com/30419460/94207119-36d38400-fec7-11ea-8613-f3354bbc0df5.png)

**Comment by eopeter** [comment]
fixed in 0.0.16

**Comment by axelasa** [comment]
The multiple navigation might have an issue in the  flutter_mapbox_navigation package version  flutter_mapbox_navigation: ^0.2.2:
when you enter in multiple points, it shows you all your stops but when you click button to start your journey or preview your journey (simulate route)
it actually only shows a blank screen

![image](https://github.com/eopeter/flutter_mapbox_navigation/assets/30687283/0d995e7a-bdaa-4b70-93d3-d51423923477)

the image below shows the map showing all stops

![image](https://github.com/eopeter/flutter_mapbox_navigation/assets/30687283/f60991b8-ccb1-446e-8572-890671e160dc)

when the sefult purple button on the right is pressed, the route navigates perfectly well as shown below

https://github.com/eopeter/flutter_mapbox_navigation/assets/30687283/0f10ae4d-29fe-49e6-bf2c-2ca7b94875cf

but when i press on my own custom buttons i.e. start and preview, I get back a black screen with a voice but no visual


https://github.com/eopeter/flutter_mapbox_navigation/assets/30687283/4e70c9bf-8673-40d5-b49a-23353f2dabfd

this only happens for multiple routes, but the rest works fine.

my buttons implementation

child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  ElevatedButton(
                    child: const Text("Start "),
                    onPressed: () async {
                      _isMultipleStop = true;
                      var wayPoints = <WayPoint>[];
                      wayPoints.add(_home);
                      wayPoints.add(_stop1);
                      wayPoints.add(_stop2);
                      wayPoints.add(_stop3);
                      wayPoints.add(_stop4);
                      wayPoints.addAll(_destinationWayPoints);
                      var opt = MapBoxOptions.from(_navigationOption);
                      opt.simulateRoute = false;
                      opt.alternatives = true;
                      opt.isOptimized = true;
                      opt.allowsUTurnAtWayPoints = true;
                      opt.enableRefresh = true;
                      opt.mode = MapBoxNavigationMode.drivingWithTraffic;
                      opt.animateBuildRoute = true;
                      opt.mapStyleUrlDay = 'https://url_to_day_style';
                      opt.mapStyleUrlNight = 'https://url_to_night_style';
                      opt.voiceInstructionsEnabled = true;
                      opt.bannerInstructionsEnabled = true;
                      opt.showReportFeedbackButton = true;
                      opt.showEndOfRouteFeedback = true;
                      opt.units = VoiceUnits.imperial;
                      opt.language = "en";
                      //opt.tilt = 60;
                      await MapBoxNavigation.instance
                          .startNavigation(wayPoints: wayPoints, options: opt);
                    },
                  ),
                  const SizedBox(
                    width: 10,
                  ),
                  ElevatedButton(
                    child: const Text("preview"),
                    onPressed: () async {
                      // _isMultipleStop = true;
                      var wayPoints = <WayPoint>[];
                      wayPoints.add(_home);
                      wayPoints.add(_stop1);
                      wayPoints.add(_stop2);
                      wayPoints.add(_stop3);
                      wayPoints.add(_stop4);
                      wayPoints.addAll(_destinationWayPoints);
                      var opt = MapBoxOptions.from(_navigationOption);
                      opt.simulateRoute = true;
                      opt.alternatives = true;
                      opt.isOptimized = true;
                      opt.allowsUTurnAtWayPoints = true;
                      opt.mode = MapBoxNavigationMode.drivingWithTraffic;
                      opt.enableRefresh = true;
                      opt.animateBuildRoute = true;
                      opt.mapStyleUrlDay = 'https://url_to_day_style';
                      opt.mapStyleUrlNight = 'https://url_to_night_style';
                      opt.voiceInstructionsEnabled = true;
                      opt.bannerInstructionsEnabled = true;
                      opt.showReportFeedbackButton = true;
                      opt.showEndOfRouteFeedback = true;
                      opt.units = VoiceUnits.imperial;
                      opt.language = "en";
                      await MapBoxNavigation.instance
                          .startNavigation(wayPoints: wayPoints, options: opt);
                    },
                  ),
                ],
              ),


void _buildRoute() {
  if (_routeBuilt) {
    _controller.clearRoute();
  } else {
    var wayPoints = <WayPoint>[];
    wayPoints.add(_home);
    wayPoints.add(_stop1);
    wayPoints.add(_stop2);
    wayPoints.add(_stop3);
    wayPoints.add(_stop4);
    wayPoints.addAll(_destinationWayPoints);
    _isMultipleStop = wayPoints.length > 2;
    _controller.buildRoute(
      wayPoints: wayPoints,
      options: _navigationOption,
    );
    debugPrint('Here Are All The Waypoints: $wayPoints');
  }
}
how my routes are built.
