### ISSUE TITLE
Different behaviour 

### ISSUE THREAD

**Issue by ulrichbjerre** [eopeter/flutter_mapbox_navigation#81]
I am experiencing different results depending on the physical device.
I'm also experiencing problems that "shouldn't happen".

I don't know how to describe it clear in text - thus I have recorded these three videos (let me know if you can't access them):
https://drive.google.com/drive/folders/19p-EMTvwuHn3_md8jzWEbq51mzCpZdsM?usp=sharing 

First of all - the app shown is the example app.
I've inserted buttons at the top to change navigation mode between: walking, cycling and driving.
I've recorded a video of each three modes - using the exact same code as in the example thus the exact same coordinates/waypoints including the danish language (thank you for testing this for me!!!!)

The devices I'm testing on are:
- Left: Lenovo K6 Lite running Android 7.0
- Middle: iPhone 8 running iOS 13.7
- Right: Huawei P20 lite running Android 8.0.0

I believe the videos speak for them selves, however I'd like to emphasise the following:

The language of the downloaded instructions are all in Danish (accordingly to the settings in the demo app).
The spoken language on the Android devices is a female Danish voice in high quality.
The spoken language on the iOS device is a mail English very low-quality voice. (odd because the other two devices work perfectly - BTW the iOS simulator makes use of the femail voice - in English though - which is even more odd! - yes the simulator and device language is set to Danish).
The route behaves differently on all devices.
The route on the Lenovo (left device) seems to have a life of its own now and then!?
The route on the iPhone and Huawei seems to be somewhat the same - but the appearance is obviously different.
And, the route finishises too soon in some modes on some devices.

What to do?
The example app behaves inconsistent across these three devices without having made any changes (beside the buttons in the top).
They are all connected to the same WiFi network.
And, they are making use of the exact same waypoints and "Multi stop" method.

I'm looking very much forward for your reply.

Best regards
Ulrich Bjerre
Being a fan of this plugin I really hope, that there's a solution to my experiences.

PS: I'm sorry for the crackling audio - don't know why.

**Comment by eopeter** [comment]
What is the default TextToSpeech (TTS) voice native to the iPhone? When the device is not able to load the default voice engine, it falls back to the default TTS engine for the device which could be the low quality voice you hear. 

The behavior depends on multiple factors. There is differences between the implementation for iOS and Android and the way the OS handles network availability but
It is possible to override the VoiceController to ensure it is always consistent. I could look into that.

**Comment by ulrichbjerre** [comment]
I would appreciate if you could take a look at it. However, when I use Apple's built in navigation the default voice is a female (danish) voice although different voicing compared to the ones on my Android devices. 
I've actually never heard this low quality male voice before and I have made other apps that make use of the built in TTS. 

I actually believe that this default female (English) voice might be the one I hear in the iOS simulator?...but I'm in doubt. If relevant I'll check it when possible. 

But, even so - what would explain that the simulation chooses an English voice while all other devices does in fact use the danish voice?best regards 
Ulrich Bjerre

**Comment by ulrichbjerre** [comment]
I'm filing a few new issues related to this based on the latest release - so I'll close this issue.

**Comment by marcellodesales** [comment]
This is absolutely amazing!
