### ISSUE TITLE
rerouting 

### ISSUE THREAD

**Issue by gaurav472** [eopeter/flutter_mapbox_navigation#82]
rerouting is not working

**Comment by eopeter** [comment]
I will need more details than just "not working". What OS? physical device or simulator? Please provide more context

**Comment by gaurav472** [comment]
Hello eopeter,

OS: android 
Device : All Andorid device not working

I am using below method in flutter



await _directions.startNavigation(
        origin: _origin,
        destination: _destination,
        mode: MapBoxNavigationMode.driving,
        language: "English",
        simulateRoute: false);
		
		
		
Let me know Incase any further information required from my side.

**Comment by eopeter** [comment]
Not using latest code
