### ISSUE TITLE
Problem with multiple waypoints

### ISSUE THREAD

**Issue by dmanzanomartin** [eopeter/flutter_mapbox_navigation#86]
Hi, when I start the "startNavigation" in IOS it works perfectly, but when I start it on Android, it just add me one waypoint, do you know how can I fix it???

Thanks a lot.

**Comment by eopeter** [comment]
Allow it to run through the entire navigation. Android does one WayPoint at a time. Does not show them all at once. As you arrive, it begins the next waypoint
