### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by gaurav472** [eopeter/flutter_mapbox_navigation#88]
app crash when run in ios devices

**Comment by eopeter** [comment]
What’s your IOS version? If IOS 14, you must build in Profile or Release configuration.

**Comment by gaurav472** [comment]
i have changed the version of navigation it works fine on ios but its working as simulator either it is false or true and also rerouting is not working

**Comment by eopeter** [comment]
That’s a separate issue and close issues that you think are resolved.
