### ISSUE TITLE
simulation issue 

### ISSUE THREAD

**Issue by gaurav472** [eopeter/flutter_mapbox_navigation#89]
latest version of app working as simulator either it is false or true and also rerouting is not working

**Comment by eopeter** [comment]
Did you set the SimulateRoute to false? What was the result. Rerouting does not work on iOS?

**Comment by gaurav472** [comment]
yes but its still in simulation mode and rerouting doesn't work on any os its showing rerouting with loader and keep spinning

**Comment by eopeter** [comment]
The following example sets the SimulationMode to false and it does not simulate. If True, it simulates. Does this not work for you?

`await _directions.startNavigation(
                                wayPoints: wayPoints,
                                options: MapBoxOptions(
                                    simulateRoute: false));`

**Comment by gaurav472** [comment]
Yes, right 
below method not working for me

await _directions.startNavigation(
                                      origin: _origin,
                                      destination: _destination,
                                      mode: MapBoxNavigationMode.driving,
                                      simulateRoute: false);

**Comment by eopeter** [comment]
Upload a video that shows it’s not working

**Comment by eopeter** [comment]
That method has been deprecated. Please use latest version

**Comment by gaurav472** [comment]
ok i will try after upgrading version

**Comment by eopeter** [comment]
Not using latest code
