### ISSUE TITLE
Make navigation direction based on polylines

### ISSUE THREAD

**Issue by MrMagloire** [eopeter/flutter_mapbox_navigation#9]
Hello, Thank you already for the work done, but I would like to know if there is a possibility of plotting the route to follow according to points already defined like Bus route (polyline) by example.

**Comment by kururu-abdo** [comment]
@MrMagloire  plz i need to complete example

**Comment by joaovmeneses** [comment]
Probably i have the same issue. I have a list of coordinates and i use that list to draw a route with polyline. Can i take that polyline or coordenate's list to use in route of Mapbox Navigation or just with two Location() objects in attributes "origin" and "destination"? Thanks !

**Comment by eopeter** [comment]
coming in v0.12

**Comment by basvdijk** [comment]
> coming in v0.12

Do you have an example how this was implemented? Thanks!
