### ISSUE TITLE
Custom Routes

### ISSUE THREAD

**Issue by HelloJowet** [eopeter/flutter_mapbox_navigation#90]
Hi,

thank you for your nice work.
Is it possible to add a custom route to the navigation like explained in this mapbox documentation page (https://docs.mapbox.com/android/navigation/overview/custom-routes/)? 

Kind Regards,
Jonas

**Comment by eopeter** [comment]
This seems pretty easy to implement.

**Comment by HelloJowet** [comment]
Thank you for your respond.
I've never programmed natively before. I would be very grateful if you would integrate this functionality into the plugin.
Unfortunately, custom routes cannot be easily integrated for IOS: https://github.com/mapbox/mapbox-navigation-ios/issues/717. If you could find a way to integrate the functionality for IOS too, that would be awesome. But only Android would also be sufficient.

**Comment by eopeter** [comment]
no plans for this at the moment
