### ISSUE TITLE
finishNavigation not closing the navigation view on Android

### ISSUE THREAD

**Issue by KiwiArch** [eopeter/flutter_mapbox_navigation#91]
Calling finish navigation from the on_arrival or progress_change events is not closing the navigation view, the only way to exit navigation seems to be the user explicitly closing the window.

**Comment by bossbeagle1509** [comment]
Yeah and even the user cancelling navigation causes a blank screen to show, although from what I saw in my emulator it didn't exactly crash

**Comment by MaheshPeri19** [comment]
Below line is working in Android when i place in case MapBoxEvent.on_arrival:

```
MapBoxNavigation _directions; 
await _directions.finishNavigation();
```

After arrival, it is removing that navigation screen and going back to my app screen.

I am using google map and only using mapbox for navigation, so below line with _controller is not working. 
`await _controller.finishNavigation();
`

**Comment by eopeter** [comment]
Should be working now
