### ISSUE TITLE
route not build

### ISSUE THREAD

**Issue by gaurav472** [eopeter/flutter_mapbox_navigation#92]
D/NetdClient(28052): netdClientConnect netId:0, uid:10465, nid:0, addr:::ffff:13.227.136.83, lan:0, localhost:0, sa_family:10, sockfd:147, thread:.mapbox.com/...
D/Mbgl-HttpRequest(28052): [HTTP] Cancel request https://api.mapbox.com/v4/mapbox.mapbox-incidents-v1/11/368/803.vector.pbf?access_token=pk.eyJ1IjoibWF1bGlrbmFpayIsImEiOiJja2ViMHYydnEwNDlrMnBwOHQ0OWtveDIzIn0.2YvAS6zXaqhtGupcAM0LzA&sku=100kg915od6ec18df1b73a54b46a25bbea7d7589f66
D/Mbgl-HttpRequest(28052): [HTTP] Cancel request https://api.mapbox.com/v4/mapbox.mapbox-incidents-v1/14/2949/6426.vector.pbf?access_token=pk.eyJ1IjoibWF1bGlrbmFpayIsImEiOiJja2ViMHYydnEwNDlrMnBwOHQ0OWtveDIzIn0.2YvAS6zXaqhtGupcAM0LzA&sku=100kg915od6ec18df1b73a54b46a25bbea7d7589f66
D/Mbgl-HttpRequest(28052): [HTTP] Cancel request https://api.mapbox.com/v4/mapbox.mapbox-incidents-v1/14/2949/6427.vector.pbf?access_token=pk.eyJ1IjoibWF1bGlrbmFpayIsImEiOiJja2ViMHYydnEwNDlrMnBwOHQ0OWtveDIzIn0.2YvAS6zXaqhtGupcAM0LzA&sku=100kg915od6ec18df1b73a54b46a25bbea7d7589f66
I/Mbgl-HttpRequest(28052): Request failed due to a connection error: Socket closed 
D/Mbgl-HttpRequest(28052): [HTTP] Cancel request https://api.mapbox.com/v4/mapbox.mapbox-incidents-v1/14/2950/6426.vector.pbf?access_token=pk.eyJ1IjoibWF1bGlrbmFpayIsImEiOiJja2ViMHYydnEwNDlrMnBwOHQ0OWtveDIzIn0.2YvAS6zXaqhtGupcAM0LzA&sku=100kg915od6ec18df1b73a54b46a25bbea7d7589f66
D/Mbgl-HttpRequest(28052): [HTTP] Cancel request https://api.mapbox.com/v4/mapbox.mapbox-incidents-v1/14/2950/6427.vector.pbf?access_token=pk.eyJ1IjoibWF1bGlrbmFpayIsImEiOiJja2ViMHYydnEwNDlrMnBwOHQ0OWtveDIzIn0.2YvAS6zXaqhtGupcAM0LzA&sku=100kg915od6ec18df1b73a54b46a25bbea7d7589f66
I/Mbgl-HttpRequest(28052): Request failed due to a connection error: Socket closed 
I/Mbgl-HttpRequest(28052): Request failed due to a connection error: Socket closed 
I/Mbgl-HttpRequest(28052): Request failed due to a connection error: Socket closed 
I/Mbgl-HttpRequest(28052): Request failed due to a connection error: Socket closed 
I/Mbgl-HttpRequest(28052): Request failed due to a connection error: Socket closed 
W/com.deleiver(28052): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (greylist,core-platform-api, reflection, allowed)
D/Mbgl-HttpRequest(28052): [HTTP] Request with response = 304: Not Modified
D/Mbgl-HttpRequest(28052): [HTTP] Cancel request https://api.mapbox.com/v4/mapbox.mapbox-incidents-v1.json?access_token=pk.eyJ1IjoibWF1bGlrbmFpayIsImEiOiJja2ViMHYydnEwNDlrMnBwOHQ0OWtveDIzIn0.2YvAS6zXaqhtGupcAM0LzA&secure&sku=100kg915od6ec18df1b73a54b46a25bbea7d7589f66

MapBoxEvent.route_build_failed

**Comment by eopeter** [comment]
This is not an issue with the plug-in but you connection

**Comment by gaurav472** [comment]
Can you please help me for route draw between two location ?

**Comment by eopeter** [comment]
What code do you have now to draw the route?

**Comment by gaurav472** [comment]
issue resolved but can i  get the pin on source and destination points?

**Comment by gaurav472** [comment]
any idea about set  multi pin in mapbox navigation?
