### ISSUE TITLE
Example broken for MapBoxNavigationView

### ISSUE THREAD

**Issue by oiime** [eopeter/flutter_mapbox_navigation#95]
Hello, I'm attempting to evaluate the library using the provided example, i noticed that `on_arrival` is never called when the embedded navigation is being used instead of the drop in UI, that causes the view to hang at the end of the first leg. 
also, it seems have an additional marker on the view and no compass arrow in the current location

![image](https://user-images.githubusercontent.com/14926758/96364714-a7776480-1144-11eb-98dc-cc452a5d0dd9.png)

**Comment by eopeter** [comment]
Are you still having this issue?
