### ISSUE TITLE
MapBoxNavigationView widget does not open Navigation view on Android

### ISSUE THREAD

**Issue by aamirki** [eopeter/flutter_mapbox_navigation#98]
I'm building a route with the following options:
```
MapBoxOptions(
      initialLatitude: widget.origin.lat,
      initialLongitude: widget.origin.lng,
      zoom: 13.0,
      tilt: 0.0,
      bearing: 0.0,
      enableRefresh: false,
      alternatives: true,
      voiceInstructionsEnabled: true,
      bannerInstructionsEnabled: true,
      allowsUTurnAtWayPoints: true,
      mode: MapBoxNavigationMode.drivingWithTraffic,
      units: VoiceUnits.imperial,
      simulateRoute: false,
      language: 'en',
 )
```
with the widget configured like this:
```
MapBoxNavigationView(
        options: _options(),
        onCreated: (MapBoxNavigationViewController controller) async {
          this.controller = controller;
          this.controller.initialize();
          if (widget.isNavigating) {
            _startNavigation();
          } else {
            _exitNavigation();
          }
        },
      )
```
Where _startNavigation() simply calls `this.controller.buildRoute(wayPoints: this.stops)` with a set of two stops and then calls `this.controller.startNavigation(options: _options())`. This works fine on iOS and does navigate properly. On Android, only the route shows on the map and navigation mode is never entered into. I do not see any errors pop up in the debug console.

**Comment by devtjandra** [comment]
Having this issue too. On Android, it just shows a top-down view of the map.

**Comment by Cybernetics354** [comment]
any updates on this?

**Comment by skamal16** [comment]
Same issue

**Comment by ralmarri12** [comment]
same issue here.

**Comment by eopeter** [comment]
The package is still very early and needs more contributions. I cannot reproduce this issue
