### ISSUE TITLE
 The imported library ''package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart'' can't have a part-of directive.

### ISSUE THREAD

**Issue by Reet0709** [eopeter/flutter_mapbox_navigation#99]
I have added Following Permission->

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

and added Token Here->

          <resources>
            <string name="app_name">Navigation map</string>
            <string name="mapbox_access_token" 
         translatable="false">ADD_MAPBOX_ACCESS_TOKEN_HERE</string>
               <string name="user_location_permission_explanation">This app needs location permissions to show its functionality.</string>
                      <string name="user_location_permission_not_granted">You didn\'t grant location permissions.</string>
              </resources>

Added this dependency in the pubspec.yaml and  Installing it->
              flutter_mapbox_navigation: ^0.0.18

But when I am importing this-

          import 'package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart';

It is Showing the following error ->

The imported library ''package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart'' can't have a part-of directive.

What else i need to do?

**Comment by eopeter** [comment]
Please follow the import directive in the pub spec installing section or look at how it was imported in the example.

**Comment by KaiChieh-Kenneth-Huang** [comment]
I had the same problem. We should use import 'package:flutter_mapbox_navigation/library.dart'; instead of ''package:flutter_mapbox_navigation/flutter_mapbox_navigation.dart'' as stated in the import directive in pub spec installing section.
